### ISSUE TITLE
[Question] varied mob textures support?

### ISSUE THREAD

**Issue by OtherMongrel** [SHsuperCM/CITResewn#10]
hi there i was wondering if this mod added support for varied mob textures so i can run this resource pack - if not do you know of a mod that does? 
https://www.planetminecraft.com/texture-pack/recrafted-mobs/

**Comment by SHsuperCM** [comment]
Nah, sorry, that is not planned for CIT Resewn.

Here's what I use to find optifine feature replacements:
https://gist.github.com/LambdAurora/1f6a4a99af374ce500f250c6b42e8754

There seems to be a mod for it in the list.
