### ISSUE TITLE
BUG: Some resource packs do not work.

### ISSUE THREAD

**Issue by EvilAragon** [SHsuperCM/CITResewn#101]
Some resource packs no longer run with the mod, e.g. the resource pack "New Default +". Minecraft tries to load the pack as usual, but stops just before the end of the loading bar, tries again and then fails with the message: "Reload resources failed."
The same message also appears if you load the resource pack without the mod and then restart Minecraft with the mod.

**Comment by SHsuperCM** [comment]
New Default+ has broken paths.

More info available here:
https://citresewn.readthedocs.io/usage/help/
https://citresewn.readthedocs.io/usage/config/
