### ISSUE TITLE
Limited amount of models per item

### ISSUE THREAD

**Issue by ben2chicken** [SHsuperCM/CITResewn#103]
when trying to make the netherite sword nameable as any of the other sword models I created, there seems to be a limit of 2 CITs linked to the netherite sword
![issue](https://user-images.githubusercontent.com/99366394/153296031-2af506c8-0729-4cca-9d82-f9aebfdf5ae7.PNG)
.
![2022-02-09_11 50 43](https://user-images.githubusercontent.com/99366394/153296200-878d308a-9ff0-48fe-b893-b4fa8f7a4166.png)
![2022-02-09_11 51 12](https://user-images.githubusercontent.com/99366394/153296210-9b9bb36a-7388-40eb-9890-918ca2907fbc.png)

**Comment by SHsuperCM** [comment]
CITs are the actual `properties` files and I only see you using two there.
There shouldn't be any limit to the amount of CITs that an item type can have, I'll need you to send the pack you think has an issue so I could take a look.

Also, `nbt.display.Name` is using a `:` separator instead of `=` which will not work with CIT Resewn v1.

**Comment by ben2chicken** [comment]
i previously had 5 files in the cit/items directory. moving the "file containing the stone swords into the file containing the diamond swords allowed the stone sword to work. for some reason the code does not like the file names "tengen," "uzui," or "zenitsu."
i didn't even change anything... i just moved the .json, .properties. and .png files to a different folder and they started working.

**Comment by SHsuperCM** [comment]
Yeah I couldn't find an issue with the pack, if you manage to recreate the problem, please let me know, provide your logs and I'll reopen the issue.

**Comment by ben2chicken** [comment]
an interesting thing is that this pack isn't working in optifine either...
and for some reason the golden sword still isn't working

**Comment by ben2chicken** [comment]
AND MOVING THE GOLD SWORD TO MY "ARMOR" FOLDER FIXED IT????
