### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by DarkblooM-SR** [SHsuperCM/CITResewn#106]
Tried loading Ghoulcraft and Mizuno 16 CIT, didn't work
Yes I made sure both packs were compatible and yes I tried them with Optifine and they both worked fine

**Comment by SHsuperCM** [comment]
Send your logs

**Comment by DarkblooM-SR** [comment]
How do I get them?

**Comment by SHsuperCM** [comment]
I just saw the pack names, do you have Broken Paths enabled in the config? If not, enable it amd it will be fixed.
