### ISSUE TITLE
Breaks with Inspecio's quiltified fabric api

### ISSUE THREAD

**Issue by Justsnoopy30** [SHsuperCM/CITResewn#107]
See https://github.com/Queerbric/Inspecio/issues/66
LambdAurora says not to rely on the implementation class.

**Comment by SHsuperCM** [comment]
Of course it's bad to rely on an implementation class but currently that part of the api is lacking.
There is already a plan to handle this but not any time soon.

CIT Resewn never claims to support this "quiltified fabric api" and if mods want to support other things, they shouldn't bundle a FAPI that is not the official Fabric API implementation.

**Comment by SHsuperCM** [comment]
Support will be considered again after the v1 rewrite is published.

**Comment by SHsuperCM** [comment]
Just thought of a better solution.

**Comment by SHsuperCM** [comment]
Ok, I removed the usage of impl fapi. This should be fixed now(still targeting the v1 release tho).
