### ISSUE TITLE
Support for optifine Anim name space

### ISSUE THREAD

**Issue by AlsoNiko** [SHsuperCM/CITResewn#11]
Optifines Anim and by extension anim.properties fall very closely to CIT, allowing for overriding the armor model and such, might make sense to include it here instead of a separate mod

**Comment by SHsuperCM** [comment]
I've considered this already and decided it is outside of the mod's scope.
Just want to remind that CIT Resewn is not here to re-implement all of MCPatcher/Optifine.
There are multiple mods out there to do that and CIT Resewn is just one of them.

I look at this list if I want a feature from optifine:
https://gist.github.com/LambdAurora/1f6a4a99af374ce500f250c6b42e8754
There's a mod called moremcmeta which allows resourcepacks to animate more textures.
