### ISSUE TITLE
broken with iris-mc1.18.2-

### ISSUE THREAD

**Issue by fractures202** [SHsuperCM/CITResewn#110]
broken with iris-mc1.18.2-1.2.1-rc2-0cc372f0-dirty in 1.18.2，please update the mod，thanks

**Comment by SHsuperCM** [comment]
The issue will be reopened when logs are provided.

**Comment by fractures202** [comment]
my Crash Report: https://bytebin.lucko.me/Qn2JTPiaGf

**Comment by SHsuperCM** [comment]
What led you to believe that this had anything to do with CIT Resewn? The logs show that iris itself is the one causing the crash, no other mod.
