### ISSUE TITLE
Crashing on launch when no config directory is present

### ISSUE THREAD

**Issue by HeatwaveDaGreat** [SHsuperCM/CITResewn#114]
When trying to launch CIT Resewn it crashes
[New Paste 1.txt](https://github.com/SHsuperCM/CITResewn/files/8239126/New.Paste.1.txt)

**Comment by SHsuperCM** [comment]
It crashed because the mc directory didnt have a config folder. Just create a folder named `config` there in the meantime.

**Comment by SHsuperCM** [comment]
Will be fixed with v1.
