### ISSUE TITLE
Infinite resource reloading loop with Secret Rooms

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [SHsuperCM/CITResewn#117]
**MC** 1.18.2
**Fabric API** 0.48.0
**[Secret Rooms](https://www.curseforge.com/minecraft/mc-mods/secret-rooms-fabric)** 1.3.1
**CITResewn** 1.0.0

To reproduce:

1. Install FAPI, Secret Rooms and CITResewn
2. Launch the game
3. Observe an infinite resource reloading loop

Version 0.9.1 of CITResewn doesn't have this issue.

Log: https://gist.github.com/Footage2-Amply-Pounce/adddeb0a0f63465dd510cb6aa0e6a922

**Comment by SHsuperCM** [comment]
Fixed in [v1.0.1](https://modrinth.com/mod/cit-resewn/version/1.0.1+1.18.2)
