### ISSUE TITLE
wierd issue

### ISSUE THREAD

**Issue by nEONcReepER990** [SHsuperCM/CITResewn#119]
pack:
[§2§lFurf§b§lSky.zip](https://github.com/SHsuperCM/CITResewn/files/8305834/2.lFurf.b.lSky.zip)

log:
[latest.log](https://github.com/SHsuperCM/CITResewn/files/8305841/latest.log)

Edit from the original issue text:
> Yes, hello, its me again... I have ran into an issue, mainly the player_head and black_stained_gass_pane but there like wierd ones like coal and coal block https://user-images.githubusercontent.com/95697642/159031631-758b95e1-4149-4958-a380-2767e1e8a5f1.png
> 
> before update to CITResewn-1.0.1+1.18.2.jar (on version CITResewn-0.9.1+1.18.1.jar) https://user-images.githubusercontent.com/95697642/159032734-365be0e6-ceec-4ced-b95c-a0f14d5d99f4.png
> 
> after update to CITResewn-1.0.1+1.18.2.jar (newest) https://user-images.githubusercontent.com/95697642/159031475-f0e1430e-780a-4469-b26d-b7d6741d0c41.png

**Comment by SHsuperCM** [comment]
The pack has too many issues to even count. It looks to be made prior to 1.13 and a lot of it is breaking.
I have no idea how it even managed to load with v0.9 but it shouldn't work regardless.

Also the logs you sent were with v0.9. That's unrelated to v1 and will not be looked into until you update.

**Comment by nEONcReepER990** [comment]
[latest.log](https://github.com/SHsuperCM/CITResewn/files/8306308/latest.log)

**Comment by SHsuperCM** [comment]
Same issue. The pack is just very old.
The specifics of the errors are listed in the logs.

**Comment by nEONcReepER990** [comment]
So you're saying I should try to fix it or just leave it and live with it?
