### ISSUE TITLE
Elytra CIT gets replaced by cape elytra texture

### ISSUE THREAD

**Issue by Julienraptor01** [SHsuperCM/CITResewn#121]
While the CIT is fine on the item it doesn't show up on the player when equiped

![2022-03-19_21 35 59](https://user-images.githubusercontent.com/49841713/159137875-03fd8dc1-96db-4fb5-a30a-dc66c7f1d06f.png)
![2022-03-19_21 36 26](https://user-images.githubusercontent.com/49841713/159137882-c50674b0-0841-407d-8f2d-edbf70fc16d9.png)
This is the expected behavior (screenshot taken on 0.9.1)

![2022-03-19_21 45 35](https://user-images.githubusercontent.com/49841713/159137912-867f711f-6f00-4633-9df2-8aaeb975afb9.png)
![2022-03-19_21 45 45](https://user-images.githubusercontent.com/49841713/159137915-2600557b-115e-4fce-8e0f-4baa58a77889.png)
And this is what happen (screenshot taken on 1.0.1)

**Comment by SHsuperCM** [comment]
Send your logs and the pack in question to reopen the issue.

**Comment by SHsuperCM** [comment]
Wait.. does this happen when you turn off your cape?

**Comment by Julienraptor01** [comment]
It work without my cape and i noticed that when i have my cape i can see the cit for like 1 frame and then it is overriden by the cape texture.

**Comment by SHsuperCM** [comment]
Can you try this version and confirm if it's fixed with the cape on?
[CITResewn-1.0.2+SNAPSHOT+1.18.2.jar](https://drive.google.com/uc?export=download&id=1KjdeLHXQcJW3tIxlU_AAu6D0txdWO5q4)

I don't have a cape to test this with :p

**Comment by Julienraptor01** [comment]
> Can you try this version and confirm if it's fixed with the cape on?
> [CITResewn-1.0.2+SNAPSHOT+1.18.2.jar](https://drive.google.com/uc?export=download&id=1KjdeLHXQcJW3tIxlU_AAu6D0txdWO5q4)
> 
> I don't have a cape to test this with :p

I'm gonna do that this afternoon

(You don't have the migrator cape ?)

**Comment by SHsuperCM** [comment]
Oh apparently I do, did not know that lol

I'll test it myself in a bit

**Comment by SHsuperCM** [comment]
Will be fixed with v1.0.1
