### ISSUE TITLE
Crash when reloading textures

### ISSUE THREAD

**Issue by LazyKB** [SHsuperCM/CITResewn#122]
Just got this mod and tried it out with some basic Glint recoloring. When I reload my textures (f3t) the game will crash in a few seconds.
Doing a little bit of testing it seems to be crashing when the files that are being reloaded are also opened somewhere else on your computer, like when viewing the CIT pack in file explorer or having assets opened in Photoshop.
Here's the crash report, the item it says is being rendered in the StackTrace sometimes changes between crashes, so I don't think its relevant.
[crash-2022-03-20_20.45.57-client.txt](https://github.com/SHsuperCM/CITResewn/files/8312649/crash-2022-03-20_20.45.57-client.txt)
.

**Comment by SHsuperCM** [comment]
```
...
citresewn: CITResewn 0.9.0+1.18.1
...
```
The crash report says you're using the beta. This version is outdated and issues for it will not be fixed.
If the issue still occurs in the latest version I can reopen the issue.

**Comment by LazyKB** [comment]
I updated to the latest version and it has the same issue as well as an
additional one.

**Comment by SHsuperCM** [comment]
I'm gonna need the full logs, the issue as you described it simply does not happen to me, I've tested and reloaded during development enough and it never crashed on my end.

**Comment by SHsuperCM** [comment]
Better yet, I need exact reproducible steps to cause the issue on my end in order to fix it.

**Comment by LazyKB** [comment]
Of course. All I'm doing is f3t with a CIT pack where the folder it's in is
named Optifine, which the docs say are fine, and the textures working back
up.
Here is a crash Report (it's the same as it was with the beta version) . I
also made a clean log file by closing the game, opening it, joining a world
and loading resources.

https://paste.ee/p/yMbqH (Crash Report)

As far as I can tell the log is just the crash report in this case though.

**Comment by SHsuperCM** [comment]
Can I also get the pack you had while reloading?

I can take a look later today

**Comment by LazyKB** [comment]
Cool thanks. Here it is the issue happened when there were only enchantment
glints in it so if it's related to the pack specifically it's probably
something with enchant glints not with the item changing.
You'll probably need to unzip it.

**Comment by SHsuperCM** [comment]
> Here it is

You didn't actually send the pack :p

I cannot seem reproduce this, I've tried multiple combinations of things happening(including having editors open for both the enchantment image and its properties file) and it never crashed for me.

**Comment by chsiao58** [comment]
I have been running into same issue. After some experimenting, I have pinpoint that this reload crash occurs when I am using Iris Shaders, it does not crash at all with just Fabric+CIT+Sodium. The mysterious part is that it only occurred occasionally, but still frequent enough that it's very bothersome when I am tinkering with glint function. Given the [logs](https://drive.google.com/file/d/1R6vJllmn0oNN4XgGCKFHDXPuDl4Wcsdd/view?usp=drive_link) and the nature of crash, it might have something to do with race condition when it is trying to load custom glint texture with "texture": "texture_name.png".

To reproduce the issue: 

1. Use [these](https://drive.google.com/drive/folders/1Qq-fWEvhUZ3-I40fDTML4_T2Nfhcp7ev?usp=drive_link) mods and sample resource pack.
2. Open up game and a test world
3. Move the sample resource pack to selected in option (Sometime the crash happens in this step)
4. Press F3 + T to reload resource pack, this might need to be done multiple times to trigger the crash.

Opened [issue](https://github.com/IrisShaders/Iris/issues/2604) to Iris Shader repository as well.
