### ISSUE TITLE
Support for emissive items and armor?

### ISSUE THREAD

**Issue by googlescientificnameforapig** [SHsuperCM/CITResewn#123]
Are you planning on adding emissive items and armor because I have a fire aspect sword texture but it does not look very fiery with the fire part glowing.

**Comment by googlescientificnameforapig** [comment]
without*

**Comment by SHsuperCM** [comment]
Out of scope. Emissives is something for other devs to tackle.

**Comment by googlescientificnameforapig** [comment]
Other devs of this mod or devs of other mods?

**Comment by googlescientificnameforapig** [comment]
Do you know any mod trying to add emissives? If you do can you give me the mod name?
