### ISSUE TITLE
CIT type : music disc sound file

### ISSUE THREAD

**Issue by tdapost** [SHsuperCM/CITResewn#126]
I was looking trough the project board and maybe another idea for a CIT type could be the sound file of a music disc. While it is not visual, it does seem within the idea of a CIT: something that could be overwritten with a normal resource pack, but now does so conditionally.

**Comment by SHsuperCM** [comment]
Need to check if jukeboxes sync to clients properly first but yeah, I don't see why not.

**Comment by SHsuperCM** [comment]
Sadly it seems that the disc item is not synced to the client. Only the record type is synced and so I can't apply CIT checks on it..

A shame really, could've been cool....
