### ISSUE TITLE
Add map textures?

### ISSUE THREAD

**Issue by googlescientificnameforapig** [SHsuperCM/CITResewn#130]
When you rename a map the texture changes. It only does it for maps in the inventory and hud but not in hand or item frame

**Comment by SHsuperCM** [comment]
Held maps have a very unique renderer to handle whatever's displayed on them and it's quite messy.

I don't think I'll let the normal `item` type change them by default. Instead I've added a future `map` type to the idea list in [Projects](https://github.com/SHsuperCM/CITResewn/projects/1).
