### ISSUE TITLE
CIT bug with 3D models

### ISSUE THREAD

**Issue by NovaXCIV** [SHsuperCM/CITResewn#134]
Screens: https://imgur.com/a/Uw0iqDj
Texture used in the screen: https://www.planetminecraft.com/texture-pack/the-doggos/

Mods used:
CITResewn-1.0.1+1.18.2
sodium-fabric-mc1.18.2-0.4.1+build.15
lithium-fabric-mc1.18.2-0.7.9
iris-mc1.18.2-1.2.2-build.32

**Comment by SHsuperCM** [comment]
That resourcepack uses CEM, CIT Resewn does not provide support for CEM.
Without CEM support, the pack simply removes wolf textures. 
(look in `The Doggos v0.2.zip\assets\minecraft\textures\entity\wolf`)


For other optifine features I recommend this list(which contains a CEM alternative)
https://lambdaurora.dev/optifine_alternatives/
