### ISSUE TITLE
Model doesn't change if hand property is specified

### ISSUE THREAD

**Issue by KPidS** [SHsuperCM/CITResewn#135]
Expected behavior (Optifine): even when hand property is specified, the model still changes when the item is not in hand or in an item frame https://imgur.com/a/MrFJGfF

CIT Resewn: https://imgur.com/a/UHEPoNK

Logs: https://paste.gg/p/anonymous/baf2c1fc12d64418a803df46988509ed

Resource pack: https://drive.google.com/file/d/1N2s0dunlQtx31ODTiLMh70g_vhXFFnLN/view?usp=sharing

**Comment by SHsuperCM** [comment]
Oh right. This is not on parity with optifine because I treated "any" hand to be at least in one of the hands.

I'll see what I can do.
