### ISSUE TITLE
A sound condition.

### ISSUE THREAD

**Issue by googlescientificnameforapig** [SHsuperCM/CITResewn#136]
For example, if you want an item texture to only be displayed when a certain sound plays. Like blocks getting darker when there are cave sounds. Or, only when a certain sound in your sounds folder plays. For example a sounds.json file path. E.g 
<img width="429" alt="image" src="https://user-images.githubusercontent.com/100143295/164862422-6e25e193-5982-47dc-9492-3f385ce0eed2.png">

**Comment by SHsuperCM** [comment]
Neat idea, will probably use the sound id instead of the sound path though.

Added to the idea board.

**Comment by SHsuperCM** [comment]
Hmm.. Maybe even allow checking either, not sure yet.

**Comment by googlescientificnameforapig** [comment]
Maybe add a option in the properties file that lets you choose the sound path in the sounds.json file. E.G Soundpaths=1,3
![164862422-6e25e193-5982-47dc-9492-3f385ce0eed2](https://user-images.githubusercontent.com/100143295/167906961-c88bb3b4-d724-4372-b2fb-ee1689bfe72a.png)
