### ISSUE TITLE
Compatibility issue with litematica mod

### ISSUE THREAD

**Issue by EGOIST1372** [SHsuperCM/CITResewn#138]
https://pastebin.com/mf6P3qP1
java.lang.ClassCastException: class fi.dy.masa.litematica.world.WorldSchematic cannot be cast to class net.minecraft.class_638 (fi.dy.masa.litematica.world.WorldSchematic and net.minecraft.class_638 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @604c5de8)
    at shcm.shsupercm.fabric.citresewn.ActiveCITs.getItemModelCached(ActiveCITs.java:137)

That's the CITResewn mod trying to cast the schematic world into a ClientWorld without checking first that it is one (which it's not).

more info in the link below
https://github.com/maruohon/litematica/issues/501

**Comment by SHsuperCM** [comment]
Duplicate of #108

**Comment by SHsuperCM** [comment]
Already fixed and you're using an old version
