### ISSUE TITLE
Custom Elytra doesn't work

### ISSUE THREAD

**Issue by Felix14-v2** [SHsuperCM/CITResewn#140]
**Description**
One of the mod's users reported to me that custom elytra (by renaming) don't work with the resource pack of his server. I checked it, compared to Optifine, this feature really does not work as expected.

<details>
 <summary>Optifine</summary>

![image](https://user-images.githubusercontent.com/75726196/167311813-4b284d0c-d4f8-45f2-a676-9d568323f686.png)
</details>

<details>
 <summary>CIT Resewn</summary>

![image](https://user-images.githubusercontent.com/75726196/167311702-a188ce5e-b2bd-4427-8737-2186dafb1704.png)
</details>

**Used resource pack**
[Example Pack.zip](https://github.com/SHsuperCM/CITResewn/files/8647632/Example.Pack.zip)

**Technical Info**
- Minecraft: 1.18.2
- CIT Resewn: latest from Modrinth (1.0.1)
- Fabric Loader: 0.13.3
- Fabric API: 0.50.0
- Windows 10

**Additional**
Also tested with [CITResewn 1.0.2 SNAPSHOT](https://github.com/SHsuperCM/CITResewn/issues/121#issuecomment-1078697954), but the result was the same.

**Comment by SHsuperCM** [comment]
Every single one of the elytra texture cits have a stray `elytra` in their 2nd line. (`bee.properties`, `niki.properties` & `yoohoo.properties`) 

Not sure why optifine's properties wouldn't ignore that but with the nature of my `.properties` interpreter I won't let it through in CIT Resewn.

If removing them still doesn't fix the issue I'll need logs.

**Comment by Felix14-v2** [comment]
> removing them still doesn't fix the issue

This really worked in a clean install (only CIT Resewn and LazyDFU), but when I checked in the main installation with the rest of the mods, the result returned to the start point.

It looks like this is an incompatibility with the [MinecraftCapes mod](https://www.curseforge.com/minecraft/mc-mods/minecraftcapes-mod) or with the cape as such. In that case, CITResewn 1.0.2 SNAPSHOT didn't fix the problem described in #121.

**Comment by SHsuperCM** [comment]
> If removing them still doesn't fix the issue I'll need logs.

**Comment by SHsuperCM** [comment]
If this really only happens with MinecraftCapes installed, I can't help you here.

I cannot(and will not) add explicit support for closed-source mods.
