### ISSUE TITLE
Painfully Slow

### ISSUE THREAD

**Issue by CuboidRaptor** [SHsuperCM/CITResewn#141]
Now, there's not much to explain, basically when loading minecraft and/or changing resource packs, I notice that MC takes forever to load. While minecraft was churning away, I decided to check logs and noticed that in all cases (I think) CIT Resewn was doing something to make it take forever to load.

However, I did tamper with the caching speed in the settings, so if I broke something or did something wrong please let me know.

**Comment by SHsuperCM** [comment]
Going to need the logs to see if there is anything out of the ordinary.

**Comment by CuboidRaptor** [comment]
Right.
My bad.

**Comment by CuboidRaptor** [comment]
I grabbed my logs for when minecraft was trying to load a resource pack.
They should be [here](https://pastebin.com/ER3T4WZe).
If it may interest you, the CIT resource pack I'm using is called [Hypixel+](https://www.planetminecraft.com/texture-pack/hypixel-1-8-9-1-12-1-16/).

**Comment by CuboidRaptor** [comment]
Yeah, I turned it up to 32 ticks from 1 tick.
