### ISSUE TITLE
CIS (Custom item sounds)

### ISSUE THREAD

**Issue by googlescientificnameforapig** [SHsuperCM/CITResewn#142]
You could create sound ids. For example, in the properties file entity.player.attack.sweep=citresewn.sweep. Like if you had a music disc and you wanted to change the sound, and then you use a sounds.json file to create the soundpath.

**Comment by SHsuperCM** [comment]
Sadly I cannot do music discs because the exact item in the jukeboxes is not synced to clients.

However maybe some item related sound events could be a neat addition.

Added to the idea board(in [Projects](https://github.com/SHsuperCM/CITResewn/projects/1))
