### ISSUE TITLE
color.properties is Unsupported

### ISSUE THREAD

**Issue by ic22487** [SHsuperCM/CITResewn#143]
CIT Resewn doesnt seem to check for or read color.properties, which is used to change the hardcoded color of some items like Spawn Eggs, as well as many other things like map colors and exp orbs

**Comment by SHsuperCM** [comment]
That is because Custom Colors are not a part of CIT.

Look here for other alternatives: https://lambdaurora.dev/optifine_alternatives/
I believe the one you are looking for is called "Colormatic".
