### ISSUE TITLE
CIT Suspicious Stew Not Working

### ISSUE THREAD

**Issue by JustAHuman-xD** [SHsuperCM/CITResewn#144]
CIT Suspicious stew doesnt work:

Steps to reproduce:
- Download: https://www.curseforge.com/minecraft/texture-packs/visual-stews
- Equip texture pack
- Look at stews

**Comment by SHsuperCM** [comment]
Fixed for v1.1.1 but the pack author should still replace the `iregex` checks with direct numbers which will make performance significantly better on resewn.
