### ISSUE TITLE
Crossbows don't work

### ISSUE THREAD

**Issue by Mr-Jeany** [SHsuperCM/CITResewn#145]
So I have resource pack that make crossbow different texture. It works fine with OptiFine but it doesn't work with CITResewn. Is it an issue?

**Comment by KPidS** [comment]
I had a similar issue. Fixed it by removing the line with `crossbow_standby` model in the properties file. Maybe it's the same issue, but it's just a guess, since you didn't leave a link to the resource pack.

**Comment by SHsuperCM** [comment]
KPidS is right, can't help without both the pack and your logs.
