### ISSUE TITLE
Iregex doesn't work with Russian letters [BUG]

### ISSUE THREAD

**Issue by Zgoly** [SHsuperCM/CITResewn#146]
Well, to be more precise, case insensitive doesn't work with Russian letters.

So, I created `white.properties` file with that text:
```
type=item
matchItems=netherite_sword
texture=white
nbt.display.Name=iregex:abcd
```

And everything works great.
![2022-05-25_15 39 56](https://user-images.githubusercontent.com/46041044/170245428-0db7ac6e-e654-47d1-8903-e364c673e681.png)
✅

![2022-05-25_15 40 12](https://user-images.githubusercontent.com/46041044/170245457-cb14bb45-770d-4739-a5c4-e5641386e52f.png)
✅

But not with Russian letters
```
type=item
matchItems=netherite_sword
texture=white
nbt.display.Name=iregex:абвг
```
![2022-05-25_15 41 29](https://user-images.githubusercontent.com/46041044/170245508-76140f7c-e0a1-429a-9137-6e5f08ee14bd.png)
✅

![2022-05-25_15 44 41](https://user-images.githubusercontent.com/46041044/170245535-c64c3b02-28f4-4176-939f-de978d324068.png)
❌

As you can see, in the first case, everything works, but in the second, the texture does not change. 
I want to note that if you change `iregex` to `ipattern`, everything will start working as it should.

**Comment by SHsuperCM** [comment]
Fixed by PR #139 
Not approved yet because of the reasons in the issue titled CIT Resewn
