### ISSUE TITLE
Resource Pack Reload Error

### ISSUE THREAD

**Issue by morbidrot** [SHsuperCM/CITResewn#147]
Whenever enabling CIT resewn and attempting to add CIT resource packs I should usually be able to use in regular vanilla MC with optifine will not reload. It gives me a Resource Pack Reload Error, and disables all my resource packs.
This only happens with CIT resewn, and not with optifine. I have no other mods enabled that could be causing this issue as well as I only have upmost 4-5 mods.

This happens with Ghoulcraft CIT and Hananacraft CIT more particularly.

**Comment by SHsuperCM** [comment]
Cant help you without logs but I'm assuming it's just broken paths again, there are other issues addressing this.
