### ISSUE TITLE
Model Shows Correctly but Icon Doesn't [1.17.1]

### ISSUE THREAD

**Issue by Minemaker0430** [SHsuperCM/CITResewn#148]
![2022-05-28_21 46 45](https://user-images.githubusercontent.com/85040155/170851352-96ce16f2-708e-4bf9-9801-cf70a4fa68c4.png)

CIT's are working on Item Models but not the actual Item Icons for some reason
The Netherite Sword & Shield should be showing an icon corresponding to the model but they aren't. This isn't just an issue with enchantment CITs, it happens with normal CITs as well

Modlist:
![image](https://user-images.githubusercontent.com/85040155/170851399-28323204-a376-435a-a3ec-1b44c477f61c.png)

**Comment by SHsuperCM** [comment]
The mod "eating animation" has an incompatibility with CIT(both Resewn's and optifine's)

**Comment by Minemaker0430** [comment]
Alright, Thanks!
