### ISSUE TITLE
CIT Type Enchantment

### ISSUE THREAD

**Issue by SHsuperCM** [SHsuperCM/CITResewn#15]
Need to implement

**Comment by SHsuperCM** [comment]
Need to find a working pack example and/or reverse engineer mcpatcher's implementation because the docs for this are shit

**Comment by fogggyhead** [comment]
Try xali's enchanted books if you need an example pack, it's pretty comprehensive as I believe it covers every enchantment at every level.

**Comment by SHsuperCM** [comment]
> Try xali's enchanted books if you need an example pack, it's pretty comprehensive as I believe it covers every enchantment at every level.

Yeah but that pack is not using type=enchantment, it's just replacing enchanted book visuals using type=item and I'm looking for packs that used to replace the glint.png texture.

**Comment by tauin** [comment]
what about 

https://www.curseforge.com/minecraft/texture-packs/enchanted-tools

https://www.curseforge.com/minecraft/texture-packs/enchanted-weapons

https://www.curseforge.com/minecraft/texture-packs/enchanted-armors

**Comment by fogggyhead** [comment]
> what about
> 
> https://www.curseforge.com/minecraft/texture-packs/enchanted-tools
> 
> https://www.curseforge.com/minecraft/texture-packs/enchanted-weapons
> 
> https://www.curseforge.com/minecraft/texture-packs/enchanted-armors

That's not what SHsuperCM is looking for, it's a separate thing I guess. I don't know of any packs that replace the enchant glint.

**Comment by SHsuperCM** [comment]
Yep, it seems to me like there arent any packs for this because it's been a broken feature for so long in optifine..

Gonna need something like.. mcpatcher level of old texturepacks and just play with it in an old mc version.. that is, if I cant figure out how it was implemented back then from mcpatcher's code which is luckily available.

**Comment by AlsoNiko** [comment]
From the sounds of the MCPatcher docs, it disables the enchantment glint from vanilla, and instead overlays a new glint texture. 
So if I use
 type = enchantment
 texture = optifine/glint/white_glint.png (path of texture) 
 speed = 100 (texture scroll speed) (optional)
 rotation = 0 (angle of rotation) (optional)
 layer = 1 (specify a layer for multiple glints at a time) (optional) 
 weight=6 (if two enchants use the same layer, weight is then taken to determine which to render) (optional)
 (not sure how `duration=<seconds>` `blend=<blend method>` work)
it would overlay a new glint 
This affect seems to be closely linked to anim.properties, hence why it says 
# The enchantment texture can be any resolution.  To animate an enchantment,
# use the anim/*.properties method with

**Comment by AlsoNiko** [comment]
As for why MCPatcher used this format? Probably because anim itself was just a simple solution to the issue

**Comment by SHsuperCM** [comment]
@AlsoNiko please stop suggesting that. anim is not required for enchantment glints and it will not be added to CIT Resewn.
(removing in a few)

**Comment by SHsuperCM** [comment]
> From the sounds of the MCPatcher docs, it disables the enchantment glint from vanilla, and instead overlays a new glint texture.

I get that but the part that is not documented well is the multiple layers that it allows(as well as support to layer on top of the vanilla glint

**Comment by Moyme** [comment]
I'd suggest Misa's Realistic Texture Pack, I makes heavy use of MCPatcher/Optifine features and had custom enchantment glints in 1.7.
Link to the 1.7 version: https://www.mediafire.com/file/so06m43621fp23k/Misa%252B.zip/file

**Comment by SHsuperCM** [comment]
Documentation soon

**Comment by SHsuperCM** [comment]
`method`, `fade` and `duration` will all work in v0.9.0

**Comment by Moyme** [comment]
Just noticed that MCPatcher handled it less like actual enchantment glints, more like an overlay. Maybe add an `animation` option or something similar.

MCPatcher:
https://user-images.githubusercontent.com/61115715/160247447-9ae5501b-4811-40b0-addd-0e84bfcc2779.gif

CITResewn:
https://user-images.githubusercontent.com/61115715/160247479-bd67fc35-ae34-48c8-b9c1-e8688e7d35e8.gif

(I hope I ported the pack correctly)

**Comment by SHsuperCM** [comment]
@Moyme 
> Just noticed that MCPatcher handled it less like actual enchantment glints, more like an overlay. Maybe add an `animation` option or something similar.
> 
> MCPatcher: https://user-images.githubusercontent.com/61115715/160247447-9ae5501b-4811-40b0-addd-0e84bfcc2779.gif
> 
> CITResewn: https://user-images.githubusercontent.com/61115715/160247479-bd67fc35-ae34-48c8-b9c1-e8688e7d35e8.gif
> 
> (I hope I ported the pack correctly)

I'm going to need the pack before and after your port to compare. A lot of mcpatcher's handling of this had to be written from scratch to work with modern mc so there's definitely some differences.

**Comment by Moyme** [comment]
I reduced the properties files and changed `enchantmentIDs` to the new ones

Original (also mentioned above):
https://www.mediafire.com/file/so06m43621fp23k/Misa%252B.zip/file

My port:
[Enchantment Tests.zip](https://github.com/SHsuperCM/CITResewn/files/8355903/Enchantment.Tests.zip)

I also just noticed it may have something to do with the `blur` option, I think in MCPatcher when it was false it also disabled the slow scrolling animation.

**Comment by SHsuperCM** [comment]
@Moyme 
> I reduced the properties files and changed the numerical `enchantmentIDs` to the new ones
> 
> Original (also mentioned above): https://www.mediafire.com/file/so06m43621fp23k/Misa%252B.zip/file
> 
> My port: [Enchantment Tests.zip](https://github.com/SHsuperCM/CITResewn/files/8355903/Enchantment.Tests.zip)
> 
> I also just noticed it may have something to do with the `blur` option, I think MCPatcher also disables the slow scrolling animation when it is false.
> 
> Edit: I used Animatica for custom animated textures.

Ok so I got it working like in mcpatcher.. sorta....
First to stop the texture from scrolling, I noticed that the default scroll speed in CIT Resewn is `1.0` and apparently in mcpatcher the default was `0.0` so that needs fixing. You should probably set it manually with `speed=0` as well to have it explicitly defined.

Then also it seems that mcpatcher offset the texture by half a Y unit so it matches with the item. 
![image](https://i.vgy.me/SRKAcA.gif)

There isn't a way to do that with CITR yet so I tried just doing it in code quickly to check and it seems to work fine now.
![image](https://i.vgy.me/bRajpK.gif)

I'll open an issue for those to get a permanent solution going and probably target v1.1.0.
