### ISSUE TITLE
CIT doesn't show up on items (1.17.1)

### ISSUE THREAD

**Issue by StickyChannel92** [SHsuperCM/CITResewn#150]
I have CIT Resewn 1.17.1. Here is my screenshot of the game:
![2022-06-04_16 35 30](https://user-images.githubusercontent.com/48563620/172026183-216dcff5-43d7-4b22-ba05-88ffb06dfe42.png)

* Here is the CIT and model data:
[amethyst_piano.zip](https://github.com/SHsuperCM/CITResewn/files/8838890/amethyst_piano.zip)
* My path is C:\Users\<user>\AppData\Roaming\.minecraft\resourcepacks\StickyChannel92's Custom Textures\assets\minecraft\citresewn\cit\10-23-2021
* or C:\Users\<user>\AppData\Roaming\.minecraft\resourcepacks\StickyChannel92's Custom Textures\assets\minecraft\mcpatcher\cit\10-23-2021
* My mods (folders don't count):
![image](https://user-images.githubusercontent.com/48563620/172026321-7af87637-1889-444a-8e6c-e00759924a58.png)
* latest.log
[latestlog.txt](https://github.com/SHsuperCM/CITResewn/files/8838990/latestlog.txt)
* Here is the texture pack I'm trying to get to work (my own pack):
[StickyChannel92's Custom Textures.zip](https://github.com/SHsuperCM/CITResewn/files/8839152/StickyChannel92.s.Custom.Textures.zip)

Any idea how to get the model to work?

**Comment by SHsuperCM** [comment]
The properties' 3rd line is 
```properties
model=optifine/cit/10-23-2021/amethyst_piano
```
even though you renamed the optifine directory in the pack to `citresewn`.

You also appear to have Eating Animations installed which has bugs related to CITs not showing up. You'll have to remove it to fix the issue as well.

**Comment by StickyChannel92** [comment]
> The properties' 3rd line is
> 
> ```ini
> model=optifine/cit/10-23-2021/amethyst_piano
> ```
> 
> even though you renamed the optifine directory in the pack to `citresewn`.
> 
> You also appear to have Eating Animations installed which has bugs related to CITs not showing up. You'll have to remove it to fix the issue as well.

OMG. Thank you for the help! This fixes my problems with CITs not loading in. Now I have to go and fix my item models. ;)
