### ISSUE TITLE
Different case for Russian names is not supported.

### ISSUE THREAD

**Issue by DearFox** [SHsuperCM/CITResewn#157]
I was adapting the resource pack for clothes and added Russian language support to nbt.display.Name
here is an example:
nbt.display.Name=iregex:.*(jarl|\u044F\u0440\u043B).*
i use https://itpro.cz/juniconv/ to turn russian letters into a special code, otherwise the names won't work, at least in optifine
"\u044F\u0440\u043B" - "ярл"
But in this case, when renaming an item in Russian,
CITResewn does not support arbitrary case.
![image](https://user-images.githubusercontent.com/59219907/173001999-1fe50fef-f592-4d98-bee4-71b4f9b18143.png)
![image](https://user-images.githubusercontent.com/59219907/173002035-a2af2209-b2a1-4b60-a1a7-eada42e5e57c.png)
but arbitrary case in english is still supported:
![image](https://user-images.githubusercontent.com/59219907/173003245-7de90a29-1043-42f1-93c8-65abef1baa94.png)
![image](https://user-images.githubusercontent.com/59219907/173003267-f01eec2e-9669-4995-877a-2610937d8ee6.png)

**Comment by SHsuperCM** [comment]
You have some impeccable timing there, I literally just merged a PR to fix this.

Will be fixed in 1.1.0 that'll release soon for 1.19 and then later for 1.18

**Comment by DearFox** [comment]
> You have some impeccable timing there, I literally just merged a PR to fix this.
> 
> Will be fixed in 1.1.0 that'll release soon for 1.19 and then later for 1.18

Yes I just noticed it 😸
sorry for carelessness
