### ISSUE TITLE
Broken paths showing up when it isn't supposed to

### ISSUE THREAD

**Issue by osfanbuff63** [SHsuperCM/CITResewn#160]
I'm getting a broken paths error on [this pack](https://www.dropbox.com/s/w0ax2fvd46hd16j/osfanpack63.zip?dl=0), but this pack works completely fine with regular OptiFine. Specifically tested with the Fabulously Optimized mod pack, which includes this mod.

**Comment by osfanbuff63** [comment]
It works fine now. I think this was due to having a namespace behind the `/assets/minecraft/optifine/cit/` folder, e.g. `/assets/minecraft/optifine/cit/osfanpack63/`, which *could* be a bug, but idk

**Comment by SHsuperCM** [comment]
Optifine completely bypasses the issue that is broken paths which is simply not something that I can/will do with Resewn. There is a config you could enable in Resewn to use broken paths but it is known to cause other issues and I would recommend reporting this to the pack creator instead.

If there is anything else you think should be working but isnt, I'll need logs.
