### ISSUE TITLE
Torch edge stitching bug?

### ISSUE THREAD

**Issue by dbrighthd** [SHsuperCM/CITResewn#161]
I have been getting a strange bug with torches, where they look like they don't connect at the seams. Today I decided to go through all my mods and find out what is causing it.

Turns out when CITResewn is installed with sodium, the bug appears

I have no clue why this is happening, because a torch is a placed block and not a CIT Item, but it seems to be happening nonetheless

This is with CITResewn, Sodium, and FabricAPI: 
![image](https://user-images.githubusercontent.com/68525639/174198228-1bbc5bf9-3e4e-493e-a0b0-1e46dbb95eec.png)

And this is with just Sodium and FabricAPI:
![image](https://user-images.githubusercontent.com/68525639/174198238-b33deec1-f0ef-48e3-ae42-6e4068978554.png)

**Comment by SHsuperCM** [comment]
CIT Resewn does not mess with blocks at all. Only way this could happen is if CITR allowed the loading of a pack that contained a weird texture that messed up the texture atlas that contains the torch textures.

Gonna need logs and the active packs you have when the bug appears to look further into your case but for now this is just a vanilla/sodium bug.

**Comment by dbrighthd** [comment]
I checked my resource packs and I found the problem



![image](https://user-images.githubusercontent.com/68525639/176834383-7bec81e2-eb18-4c75-b5d4-b14dbfc12254.png)
this image was used in in one of my packs and its so large that it messed things up

deleting it fixed the problem!
