### ISSUE TITLE
enchantment glint not showing in GUI

### ISSUE THREAD

**Issue by Blveberry** [SHsuperCM/CITResewn#162]
the enchantment glint does not show up in any GUI, however it shows up just fine in 3rd person, on armor stands, and in item frames.

worked fine in 1.18.2, doesn't work in 1.19
a ss of my mods:
![image](https://user-images.githubusercontent.com/104537720/174214834-dc1025a0-6d51-48e4-a593-ef69790f1e0c.png)
ss of the problem:
![2022-06-16_20 49 26](https://user-images.githubusercontent.com/104537720/174215181-ff91f2ec-0f19-48f4-bdd4-da947cb38a46.png)
if there's any more info needed id be happy to supply it :)

**Comment by rocaN5** [comment]
Same problem :/

**Comment by SHsuperCM** [comment]
@hex-6666 
Enchantment glints show fine for me..
Gonna need the logs and the packs you have active to know what's going on.

**Comment by hex-6666** [comment]
[hex' cit pack v2.2.zip](https://github.com/SHsuperCM/CITResewn/files/9034043/hex.cit.pack.v2.2.zip)
[latest.log](https://github.com/SHsuperCM/CITResewn/files/9034044/latest.log)
heres both :)

**Comment by SHsuperCM** [comment]
So the pack works fine with the glints on my end. Gonna need you to start removing mods until you find which one causes the issue.

**Comment by hex-6666** [comment]
okay, sorry about the wait, I took a two month break from Minecraft; it seems like its an iris issue., tried with only citresewn, fabric api, and sodium and it worked fine, using iris with it makes the glints disappear
heres the logs for both:
[latest_IRIS.log](https://github.com/SHsuperCM/CITResewn/files/9740502/latest_IRIS.log)
[latest_NOIRIS.log](https://github.com/SHsuperCM/CITResewn/files/9740504/latest_NOIRIS.log)

**Comment by Blveberry** [comment]
looks like iris 1.5 has solved the issue, gg
