### ISSUE TITLE
Armor texture errors

### ISSUE THREAD

**Issue by ccyounga** [SHsuperCM/CITResewn#168]
Greetings! I would like to get more comments on the topic of armor textures in your mod. Previously, we used our armor textures through optifine without problems, now this mod gives a lot of errors and only displays icons, there are no armor textures themselves. I studied the brief documentation that was stated that the plugin can display armor textures.
Error log from the mod: https://www.toptal.com/developers/hastebin/sugivolaba

At the moment, this is the only thing that worries us. I would like to get working textures and enjoy the absence of lags from optifine.
If you can understand something, please help me understand. Ready to provide files, tell me which ones.

**Comment by ccyounga** [comment]
Thanks for getting back! I am sending you a link to a resource pack that I uploaded to a file hosting service.
I don't see any other way to upload here.
The archive contains a resource pack folder, it is stored as a folder and not as an archive for the game, since individual files are constantly updated on the server.
We can’t figure it out because this code works fine with Optifine, all textures are displayed.
Please try to investigate the issue and provide any specific indications of errors. We will fix all the configs and I will be happy with the result that we were finally able to replace optifine.
https://drive.google.com/file/d/1NuIT5XfP_IQL3HKZqtndOEAV1t7KPdTr/view?usp=sharing

**Comment by SHsuperCM** [comment]
Read the closing comment again. I listed a bunch of issues the pack has which need to be fixed for it to work.

Read your logs and read the docs.
