### ISSUE TITLE
Spawn eggs can't be changed using a texture CIT

### ISSUE THREAD

**Issue by Leolele99** [SHsuperCM/CITResewn#169]
This is an addendum to #167, in which I explain the error in detail. I checked this in other version of the mod and the same still holds up.

However I created this issue to make note of another issue that is likely connected to the first:

When creating two property files with different names, one of them applying to a spawnegg, the other to a normal item, but both referencing the same texture file, they will both break ingame (presumably only if the spawnegg property is applied first.

The spawnegg item will have its default texture while the normal item will have a white spawnegg texture as its item.

The two property files for reference:

type=item
matchItems=rabbit_spawn_egg
texture=bowblade

type=item
items=iron_sword
texture=bowblade

And the picture:
![image](https://user-images.githubusercontent.com/12782603/177306454-fb251f17-30a9-491e-9581-bd4ef1485c9d.png)

Why is this important? Spawneggs are some of the most used items in custom maps and often have additional CITs in adventure maps.

After some diffing apparently egg texturing works different, in which they layer 2 textures on top of each other with different tint indexes and then use color providers to change the colours of them.

**Comment by Leolele99** [comment]
Just to clarify, this fix applies to 1.18+ only? 
Then I will attempt to backport to thje 1.17 version

**Comment by Leolele99** [comment]
Nvm, fix is easily carried over into the 1.17.1 version of the mod, Ill open a pull request soon, thank you for your work!

**Comment by SHsuperCM** [comment]
I first fix on the main branch and then backport it to 1.18 for now.
I dont know if I'll backport to 1.17 tho as I dropped support for it.
