### ISSUE TITLE
Texture CIT replacing goat horn will not appear correctly when tooting

### ISSUE THREAD

**Issue by Wooferscoots** [SHsuperCM/CITResewn#170]
Tooting horn uses the goat horn model when tooting and doesnt display correctly

try optifine version which just changes the texture for an example
https://www.planetminecraft.com/texture-pack/goat-horns-32x/

the regular version is compatible with CITresewn and changes the model rather than just the texture

**Comment by SHsuperCM** [comment]
Sorry but I'm struggling to see where the issue is. The pack you sent works as expected.

**Comment by Wooferscoots** [comment]
Using texture CIT, not expected
![image](https://user-images.githubusercontent.com/67754858/178374129-691811d8-f0b4-431c-a921-1dd4a18af616.png)

Using model in CIT, expected
![image](https://user-images.githubusercontent.com/67754858/178374150-61c616bc-6688-4c98-90e2-117cd81f317b.png)


Interestingly optifine works with just the texture swap and does not work with a model
CITResewn works with a model but not a texture.
I tested this on version 1.1.1+1.19 and the bug is still there

What I think is happening is when you are **using** the goathorn it uses the default display and not the one for the tooting goathorn
