### ISSUE TITLE
Optifine CIT not working

### ISSUE THREAD

**Issue by muluffel** [SHsuperCM/CITResewn#174]
In my Resourcepack I have custom item textures for different Axolotl buckets (babies and variants) and also for enchanted books. They are located under `assets\minecraft\optifine\cit\axolotl` and `assets\minecraft\optifine\cit\books` but when loading the pack, I am prompted with the broken paths error message and my CITs don't work. With Optifine they work fine. Did I do anything wrong? 
Please tell me if you need any further information and/or logs etc. I will provide them asap.

Edit: The enchanted books seem to work sometimes, but not reliable always with CIT Resewn

With CIT Resewn:
![2022-07-11_18 28 12](https://user-images.githubusercontent.com/65601356/178313353-8c998e1d-cda5-48b0-8f2e-63fc361dc8a9.png)

With Optifine:
![2022-07-11_18 32 32](https://user-images.githubusercontent.com/65601356/178313391-9bc57d2a-6013-4663-85f1-17804f50aa46.png)
![2022-07-11_18 32 34](https://user-images.githubusercontent.com/65601356/178313400-f2497c5d-9d16-42ac-a0bd-91f7298b9853.png)

**Comment by SHsuperCM** [comment]
Broken Paths is when the pack contains bad folder/file names that do not comply with minecraft's resourcepack formatting rules.

Seeing the logs would help.

**Comment by muluffel** [comment]
Don't know why u closed it but here's the logs
[latest.log](https://github.com/SHsuperCM/CITResewn/files/9103894/latest.log)

**Comment by SHsuperCM** [comment]
It doesn't actually say you have broken paths.

> [17:48:19] [Render thread/ERROR]: [citresewn] Caution! Broken paths is enabled!

It just warns that it is enabled(which may or may not cause issues).

What I'm more concerned with is the conflict lines(at the top) which say you have Eating Animation installed. 
> \- Mod 'CIT Resewn: Defaults' (citresewn-defaults) 1.1.0+1.19 conflicts with any version of mod 'Eating Animation' (eatinganimationid), which is present with the following versions: 1.8.1!
	 \- While this won't prevent you from starting the game, the developer(s) of mod 'CIT Resewn: Defaults' (citresewn-defaults) have found that this combination may cause issues. You should remove one of the mods or check for updates that resolve the issue.

Eating Animation breaks CIT.

**Comment by SHsuperCM** [comment]
The issue was closed because of the Missing Logs tag btw

**Comment by muluffel** [comment]
Thanks. I'm gonna try it without eating animation and I'll give feedback. Is it planned to make compatibility between tose two mods? I'd like to use both.

Oh and:
![image](https://user-images.githubusercontent.com/65601356/178782990-cb91dec1-90c6-4abb-92a2-02ba9a868c8c.png)

**Comment by SHsuperCM** [comment]
>  Is it planned to make compatibility between tose two mods? I'd like to use both.

Can't fix it on my end, it's a problem with eating animations and its dev knows already.

> Oh and: [image]

Again, it's just warning that there are broken paths in the pack. There are files that don't fit minecraft's naming structure in there that may cause issues but it will still try to load the broken path cits.

**Comment by muluffel** [comment]
It now more or less works. The babiy axolotls still don't show up as intended. Idk why. I hope there will be compatibility one day

**Comment by SHsuperCM** [comment]
> The babiy axolotls still don't show up as intended.

Gonna need the pack if you need help with that.

**Comment by muluffel** [comment]
I can't publish my whole pack because of license reasons but I'll give you my cit folder which is located under `packname\assets\minecraft\optifine\`:
[cit.zip](https://github.com/SHsuperCM/CITResewn/files/9112004/cit.zip)
