### ISSUE TITLE
texture shows as vanilla on hotbar

### ISSUE THREAD

**Issue by kittenvr** [SHsuperCM/CITResewn#175]
it looks like this in my hand 
![image](https://user-images.githubusercontent.com/103120356/178576562-01b1e716-7003-469b-a7a4-cf9e978c4621.png)
and like this in my hotbar 
![image](https://user-images.githubusercontent.com/103120356/178576671-618b602b-437b-434b-946d-7a74e88bf85b.png)
i am using [hypixel+ ](https://www.planetminecraft.com/texture-pack/hypixel-1-8-9-1-12-1-16/)resource pack so it might be the pack itself causing the issue [u can download it if u click this to look in the files](https://www.planetminecraft.com/texture-pack/hypixel-1-8-9-1-12-1-16/)

**Comment by SHsuperCM** [comment]
Need the logs to find out why this is happening but you're describing a common problem that comes with the mod "Eating Animations" if you have that installed.

**Comment by kittenvr** [comment]
> 

how do i find these?

**Comment by kittenvr** [comment]
> Need the logs to find out why this is happening but you're describing a common problem that comes with the mod "Eating Animations" if you have that installed.

how do i find this?
