### ISSUE TITLE
Some textures are not loaded, although everything works on Optifine

### ISSUE THREAD

**Issue by VladimirIAlexandrov** [SHsuperCM/CITResewn#176]
Some textures are not loaded, although everything works on Optifine
Here is the resource https://drive.google.com/file/d/1bB2zadoq1HsSF8k8x_hwDyCe-EBUhVj1/view?usp=sharing

**Comment by SHsuperCM** [comment]
The resourcepack link doesn't work. Need to see logs and need a specific example of something that isn't working.
