### ISSUE TITLE
CurseForge and Modrinth files are different

### ISSUE THREAD

**Issue by Madis0** [SHsuperCM/CITResewn#179]
I found that the CurseForge and Modrinth files are different. Why is that?

* [v1.1.1 on CurseForge](https://www.curseforge.com/minecraft/mc-mods/cit-resewn/files/3855030) - SHA256: 948FEBB6A5C9D0A6E67350ADC02A6D0C86E7E8B5ADDA8D763054799EB20C6A1B
* [v1.1.1 on Modrinth](https://modrinth.com/mod/cit-resewn/version/1.1.1%2B1.19) - SHA256: 3076E3D9BC522AD1C3FF0D65347247A5C375424F77A7CAC70949079F4A507A12

**Comment by SHsuperCM** [comment]
Only reason I could think that'd cause this is that I run the publishing tasks separately for modrinth and curse so it builds the jar once for each. 

Making a single task should probably fix this but either way this really shouldn't be that important.

**Comment by Madis0** [comment]
Thanks for the explanation.
