### ISSUE TITLE
Custom item not showing up in game

### ISSUE THREAD

**Issue by Caelitrum** [SHsuperCM/CITResewn#186]
I have made a custom texture pack where, If I rename a diamond sword to Undying, it will have a custom texture. 
My path file is 

> C:\MultiMC\instances\Fabric 1.19\.minecraft\resourcepacks\Custom Textures for Undying\assets\minecraft\citresewn\cit

I have tested this resource pack on Optifine, and there it works perfectly (Please note that I change the citresewn to optifine when I am using the resource pack with optifine)
Now when I use fabric with citresewn it simply doesn't change the texture from a diamond sword to my custom texture.
[pack.zip](https://github.com/SHsuperCM/CITResewn/files/9281371/pack.zip)
 
Heres a log file from using it and photo of my mods folder
[latest.log](https://github.com/SHsuperCM/CITResewn/files/9281379/latest.log)
![Skärmbild 2022-08-08 133600](https://user-images.githubusercontent.com/106313423/183409333-5c2751a1-cde3-4182-b36c-74672dc48118.png)

**Comment by SHsuperCM** [comment]
You're specifying the texture incorrectly. 
You probably meant to use:
```properties
texture=undying_sword
```

**Comment by Caelitrum** [comment]
Will this change make so it still works with optifine and CIT resewn?
