### ISSUE TITLE
CIT doesn't affect in GUI (Inventory, Chest, Furnace, etc. Interface)

### ISSUE THREAD

**Issue by Silvobi** [SHsuperCM/CITResewn#187]
Using CIT only affects in-hand item and dropped item
CIT doesn't affect in Inventory/crafting etc. (UI)

![image](https://user-images.githubusercontent.com/54009037/184049049-c43e4c33-30d2-46f0-8a82-b6f0b895410e.png)
On image:
  In green circle:
    Axolotl in a bucket texture is custom because NBT tag {Variant:4}
  In red circle:
    Axolotl texture stays default despite NBT tag {Variant:4} (Should appear like in green circle)

**Comment by SHsuperCM** [comment]
Need the logs to see what's wrong.

**Comment by Silvobi** [comment]
[latest.log](https://github.com/SHsuperCM/CITResewn/files/9331612/latest.log)

**Comment by SHsuperCM** [comment]
Either remove or update eating animations
