### ISSUE TITLE
missing CIT textures/models

### ISSUE THREAD

**Issue by Saiko125** [SHsuperCM/CITResewn#192]
hello there

I'm small resource pack creator that uses mainly CIT for packs to work

I'm making this issue because recently I saw that some of the items I rename to work with my pack don't change at all
even that other items do change and all of them have correctly written .properties files which had no issues on optifine

I would like if the fix would be implemented for both 1.18 and 1.19 versions
and if that bug is just oversight that can be fixed 

thank you

**Comment by SHsuperCM** [comment]
Cant help without seeing both the pack and your logs.
