### ISSUE TITLE
CITResewn Not reading some nbt.ench. rules

### ISSUE THREAD

**Issue by T0ED** [SHsuperCM/CITResewn#195]
Hi,

Looks like the following rules aren't registering:
nbt.ench.count=1 //How many enchants does this item have?
nbt.ench.0.id=17 //What enchant ID does this item have?
nbt.ench.0.lvl=1 //What level is the aforementioned enchant?

An example of these rules can be found in this CIT pack:
https://github.com/Shotbow/minez-official-textures
Then in:
\assets\minecraft\mcpatcher\cit\normal_melee\iron_axe

**I could've also done a bad job of reading the wiki.**
For now I've just replaced these nbt.enchant substitutes:
enchantments=smite
enchantmentLevels=1

**Comment by T0ED** [comment]
Update:
assets\minecraft\mcpatcher\cit\normal_armor\spire_enchanted\fire_protection

The .properties uses 
#Rules
nbt.ench.0.id=1
weight=-1

But still works. ¯\_(ツ)_/¯

**Comment by SHsuperCM** [comment]
> nbt.ench.count=1

Never knew that `count` was a thing in nbt conditions. I'll add it for the next version.


> nbt.ench.0.id=17

Ids are no longer numeric, you were right to change `17` to `smite`.
But, when checking nbt ids there is also a namespace that's added, in smite's case 
it is `minecraft` turning the id into `minecraft:smite`. 
Checking `nbt.ench.0.id=minecraft:smite` means it checks that the first enchantment on the item is smite.

> Update:
> assets\minecraft\mcpatcher\cit\normal_armor\spire_enchanted\fire_protection
> 
> The .properties uses
> #Rules
> nbt.ench.0.id=1
> weight=-1
> 
> But still works. ¯_(ツ)_/¯

That pack contains both `optifine` and `mcpatcher` folders. The one in `mcpatcher` isn't actually working(or at least isn't supposed to). The one in `optifine` works in its place.
