### ISSUE TITLE
Unable to Resolve Texture Reference?

### ISSUE THREAD

**Issue by swerrels** [SHsuperCM/CITResewn#196]
Hi! I most definitely did something wrong because all the cit items show up as pink and black blocks. Here what my logs say:
![unkndaddown](https://user-images.githubusercontent.com/112453902/187337944-a3720142-e47d-43ba-bc10-7d2bcaa4b9d9.png)
![unknewewown](https://user-images.githubusercontent.com/112453902/187338060-37947398-b8e5-4edf-9020-8354968adb68.png)

**Comment by swerrels** [comment]
[latest.log](https://github.com/SHsuperCM/CITResewn/files/9449212/latest.log)
 Here's my full log!

**Comment by SHsuperCM** [comment]
Seems like the pack just contains some weird/broken model files. I'll need to see a specific model file in the pack to help troubleshoot.
