### ISSUE TITLE
Channeling, Loyalty enchantment glints not working on trident

### ISSUE THREAD

**Issue by Anslean** [SHsuperCM/CITResewn#197]
Custom enchant glints designated by either the Channeling or Loyalty glints fail to render on a trident. The same enchantment glint with the same properties successfully renders if the enchantment is switched to Impaling. Enchanted book glints still working as intended.

Edit: also fails with Infinity in the same way.

**Comment by Anslean** [comment]
Update: also fails with Power (5) and Infinity on a bow

**Comment by SHsuperCM** [comment]
Cannot reproduce. Gonna need the logs and the pack.
