### ISSUE TITLE
Version 1.1.2 That's for 1.19-1.19.2 Works on 1.19.1, but NOT 1.19.2

### ISSUE THREAD

**Issue by R3DZ00M** [SHsuperCM/CITResewn#198]
Hello! This is my first github submission, I made an account for this :)

As you read in the title, Version 1.1.2 That's for 1.19-1.19.2 Works on 1.19.1, but NOT 1.19.2. I tested the popular addon pack "Additional Elytras" with CIT Resewn, works perfectly in 1.19.1. On 1.19.2, it sadly doesn't. Same environment in both tests.

The pack allows you to change Elytra skins by renaming it. The test case I used was "Demon Wings" Elytra. With same circumstances, on 1.19.1 it showed up in inventory AND as a model outside. Worked flawlessly. Sadly, nothing happened on 1.19.2.

I hope we can find a fix for the issue soon! Thank you for what you're doing :)

**Comment by R3DZ00M** [comment]
Another note: Same happened with my friend. I was on 1.19.1, my friend was on 1.19.2, with the same version of CIT Resewn. Using textures from the same resource pack "Additional Elytras", which includes Invisible armor if you rename it to "invisible", I could see both our renamed "Invisible" armors as invisible, while my friend couldn't!

**Comment by SHsuperCM** [comment]
Works perfectly fine for me on 1.19.2. Gonna need you to send the logs if you want help troubleshooting.

**Comment by SHsuperCM** [comment]
The log isn't saying anything, it's irrelevant to the issue.
Open the game and load the pack fully, then close the game and send the logs from that.

**Comment by R3DZ00M** [comment]
Yep! Here's the logs: https://paste.ee/p/XbjEL

**Comment by SHsuperCM** [comment]
There isn't anything that should stop it from working, I've tested and had the demon wings working on 1.19.2(albeit with broken paths enabled in the config).

Something interesting that caught my eye though is that citresewn isn't reporting anything during resource loading, can you send the config file for cit resewn? (`config/citresewn.json`)
