### ISSUE TITLE
CIT Resewn Not working on 1.19.2 (WITH LOGS)

### ISSUE THREAD

**Issue by R3DZ00M** [SHsuperCM/CITResewn#199]
Hello! This is my first github submission, I made an account for this :)

As you read in the title, Version 1.1.2 That's for 1.19-1.19.2 Works on 1.19.1, but NOT 1.19.2. I tested the popular addon pack "Additional Elytras" with CIT Resewn, works perfectly in 1.19.1. On 1.19.2, it sadly doesn't. Same environment in both tests.

The pack allows you to change Elytra skins by renaming it. The test case I used was "Demon Wings" Elytra. With same circumstances, on 1.19.1 it showed up in inventory AND as a model outside. Worked flawlessly. Sadly, nothing happened on 1.19.2.

I hope we can find a fix for the issue soon! Thank you for what you're doing :)

https://paste.ee/p/GI85F

**Comment by SHsuperCM** [comment]
No need to open another issue, I can reopen #198 if I think it's necessary.
