### ISSUE TITLE
Cannot resolve path for model/texture with a path containing the assets/minecraft/ directory.

### ISSUE THREAD

**Issue by boerdereinar** [SHsuperCM/CITResewn#20]
For example: texture=assets/minecraft/textures/item/fortune3.png
This happens with the following resource pack:
https://www.curseforge.com/minecraft/texture-packs/xalis-enchanted-books

**Comment by SHsuperCM** [comment]
Fixed in [v0.5.3](https://modrinth.com/mod/cit-resewn/version/urCxXORI)
