### ISSUE TITLE
Firework CIT based on Flight Duration

### ISSUE THREAD

**Issue by SurfingDude-1182** [SHsuperCM/CITResewn#200]
[Logs](https://mclo.gs/lVBx2zk) (line 558 onwards)

fireworksI.properties file:
```
type=item
items=minecraft:firework_rocket
nbt.Fireworks.Flight=1
texture=firework_rocket_i.png
```

The texture I was using (in case this is needed):
![firework_rocket_i](https://user-images.githubusercontent.com/54537673/191670257-344e0110-b049-42f5-9a34-4c842c07a02d.png)

**Comment by SHsuperCM** [comment]
It's just saying that the original fireworks rocket model doesn't exist. I don't get the error on my end and it really should not even come up. Don't know why it is like that on your end. Could you try getting rid of mods until it works? One of them might be conflicting and I dont know which one.

<img src="https://i.vgy.me/l8gZqy.png" width="300">

**Comment by SurfingDude-1182** [comment]
Hmm I will try that asap then...
