### ISSUE TITLE
Carved Pumpkin not working for some reason

### ISSUE THREAD

**Issue by shizotoaster** [SHsuperCM/CITResewn#201]
Carved Pumpkin CIT is not working for some reason. No errors in game console, just no effect

Tested on:
- **Quilt 0.17.4 for 1.19.2; CITR 1.1.2+1.19.2; QSL 4.0.0 (Fabric API 0.61.0)**
- **Fabric 0.14 for 1.19.2; CITR 1.1.1+1.19.2; Fabric API 0.60.0**

**Comment by SHsuperCM** [comment]
Going to need both logs and a reproducible example of it not working.
