### ISSUE TITLE
Error: " CIT Resewn requires Cloth Config to be able to show the config.

### ISSUE THREAD

**Issue by MrFore7t** [SHsuperCM/CITResewn#205]
When i try to open config of mod i see error: " CIT Resewn requires Cloth Config to be able to show the config. But I have Cloth Config.
![image](https://user-images.githubusercontent.com/115803791/195870406-d4d4fd2d-fc9d-4497-ad6b-2fcb7c82d4f2.png)
![image](https://user-images.githubusercontent.com/115803791/195870447-807396ff-05ac-4441-9b78-c3ec95d83e47.png)
Full list of mods (if needed)
![image](https://user-images.githubusercontent.com/115803791/195870583-4936d754-21b9-4aea-905a-1754bf2c8706.png)

**Comment by SHsuperCM** [comment]
`cloth-config-8.2.88-forge.jar`
....
You downloaded forge cloth
