### ISSUE TITLE
Changing the name of the item

### ISSUE THREAD

**Issue by BaXyTostik** [SHsuperCM/CITResewn#209]
Hello, I ran into a problem that when changing the name, the texture should change, but it does not change in the inventory, and when you hold it, it is visible. Can you tell me how to fix it.

**Comment by SHsuperCM** [comment]
Gonna need logs as well as the pack.

**Comment by BaXyTostik** [comment]
[latest.log](https://github.com/SHsuperCM/CITResewn/files/10046957/latest.log)
[Pack (1).zip](https://github.com/SHsuperCM/CITResewn/files/10046958/Pack.1.zip)
version 1.19.2
