### ISSUE TITLE
Changing the name of the item 

### ISSUE THREAD

**Issue by BaXyTostik** [SHsuperCM/CITResewn#210]
https://github.com/SHsuperCM/CITResewn/issues/209
Log
[latest.log](https://github.com/SHsuperCM/CITResewn/files/10046961/latest.log)
texture pack 
[Pack (1).zip](https://github.com/SHsuperCM/CITResewn/files/10046963/Pack.1.zip)
version 1.19.2
![image](https://user-images.githubusercontent.com/106705598/202850673-abe58594-ed44-42fe-91bb-8337e94f42c1.png)
![image](https://user-images.githubusercontent.com/106705598/202850676-b7abd17a-a3a9-4c8b-9d31-5e326d1e6d91.png)

**Comment by SHsuperCM** [comment]
Sorry for the delay, could you try getting rid of eating animations and seeing if that works?

**Comment by BaXyTostik** [comment]
Sorry the problem was in Eating Animation
