### ISSUE TITLE
[Bug] Standby texture doesn't render when on standby

### ISSUE THREAD

**Issue by Thanos1716** [SHsuperCM/CITResewn#215]
This is an Optifine parity issue, as an example, when a texture is pointed to via the
`texture.bow_standby=` whilst the bow is in standby, the texture doesn't show up, however in Optifine, the texture will appear. A workaround is to just use the texture as `texture=` but this probably has edge cases as well.

**Comment by SHsuperCM** [comment]
Whoops, it was apparently set to `texture.bow_pulling_standby=` instead. Will be fixed in v1.1.3. lmk if it didnt
