### ISSUE TITLE
many enchantments not work

### ISSUE THREAD

**Issue by niemogewejsc** [SHsuperCM/CITResewn#221]
(sorry for my bad english)
if I put many enchantments, the texture doesn't work and I get warns in the console about "Invalid path in datapack"
(work on optifine)
example:
```excel
   type=item
   items=netherite_sword
   texture=fire1
   nbt.Enchantments=regex:.*(?=.*fire_aspect)(?=.*looting)(?=.*sharpness).*
   enchantmentLevels=5
   weight=4
```
warn message: "Invalid path in datapack: minecraft:optifine/cit/netherite/sword/!firesharploot/fire1.properties, ignoring"

**Comment by SHsuperCM** [comment]
The invalid path is because of the `!` that's in the folder name. Fix the broken paths prior to making an issue.

I'd need the full logs to help further.

**Comment by niemogewejsc** [comment]
[latest.log](https://github.com/SHsuperCM/CITResewn/files/10298355/latest.log)
