### ISSUE TITLE
Shulker textures broken with Visual Shulker Labels

### ISSUE THREAD

**Issue by MendingNights** [SHsuperCM/CITResewn#223]
I'm using Visual Shulker Labels resource pack on 1.19.3.  As soon as a label is applied to a shulker, the texture is broken.
![2023-01-02_10 40 10](https://user-images.githubusercontent.com/88418507/210258996-a6924813-3f63-405c-9f31-06859301339e.png)

**Comment by SHsuperCM** [comment]
I'm assuming that the pack creator hasn't updated to 1.19.3 yet.

Tell them to add the `entity/shulker` textures to the atlas if they want them to show up on item models.
If that's not the issue lmk and I can look into it again.

**Comment by MendingNights** [comment]
> I'm assuming that the pack creator hasn't updated to 1.19.3 yet.
> 
> Tell them to add the `entity/shulker` textures to the atlas if they want them to show up on item models. If that's not the issue lmk and I can look into it again.

Thanks for the quick replay.  You're correct, the creator hasn't updated to 1.19.3, yet.  I don't know the creator, so, I added the atlas myself and it works fine now.

**Comment by rikthedeveloper** [comment]
> Thanks for the quick replay. You're correct, the creator hasn't updated to 1.19.3, yet. I don't know the creator, so, I added the atlas myself and it works fine now.

Hi, can you explain in more detail how to do this? I am finding absolutely no resources in how to resolve the issue for myself.

**Comment by MendingNights** [comment]
> > Thanks for the quick replay. You're correct, the creator hasn't updated to 1.19.3, yet. I don't know the creator, so, I added the atlas myself and it works fine now.
> 
> Hi, can you explain in more detail how to do this? I am finding absolutely no resources in how to resolve the issue for myself.

Create a folder named "atlases" inside the "minecraft" folder of your resource pack.

Inside the "atlases" folder, create a .JSON file named "blocks" with the code below in it.

```
{
    "sources": [
        {
            "type": "directory",
            "source": "entity/shulker",
            "prefix": "entity/shulker/"
        }
    ]
}
```
