### ISSUE TITLE
CIT Resewn Error while loading some textures.

### ISSUE THREAD

**Issue by Palxz** [SHsuperCM/CITResewn#225]
i have been having trouble while using this with this texture pack.
[https://www.planetminecraft.com/texture-pack/slimefun-texture-by-raulh22/](https://www.curseforge.com/linkout?remoteUrl=https%253a%252f%252fwww.planetminecraft.com%252ftexture-pack%252fslimefun-texture-by-raulh22%252f)
the thing is i dont really know if its a CIT Resewn glitch or the texture but im pretty sure its CIT since i used this texture before and it worked.
i can send my log so you can also check if there is a incompatibility issue or smth.
https://drive.google.com/file/d/10cLVeReogJsV_ZXSmsH60Y0bHG32uPdq/view?usp=sharing (its long so pastebin didnt let me upload it)
if u need any more information u can ask and i will be here.
thx and have a nice day.

**Comment by ThebestkillerTBK** [comment]
You don't need CIT Resewn.

**Comment by SHsuperCM** [comment]
The pack is not even CIT.
