### ISSUE TITLE
Ghoulcraft Compatability

### ISSUE THREAD

**Issue by meromiro** [SHsuperCM/CITResewn#228]
Certain items, such as the parrot cage, budgie cage, and rat cage don't swap appearances as they should.
Here's my logs! I booted up the game and then attempted to rename the object and then closed it, so hopefully the log isn't too long for you. Thanks in advance for the help! So far it's worked fine with the other CIT packs in use.
[latest.log](https://github.com/SHsuperCM/CITResewn/files/10461497/latest.log)

**Comment by dbrighthd** [comment]
Hey it seems like there are spaces in the names of some items in this pack. Please try turning on the "Allow broken paths in resourcepacks" option, and restart your game. let me know if this works! 
![image](https://user-images.githubusercontent.com/68525639/215374240-9cdbfea0-b15c-4f72-8c9f-7651e5660c12.png)

**Comment by SHsuperCM** [comment]
If the suggested solution didnt fix it, lmk and I'll reopen the issue.
