### ISSUE TITLE
Poor optimization of texture replacement work, like optifine

### ISSUE THREAD

**Issue by ccyounga** [SHsuperCM/CITResewn#230]
Low fps from armor that replaces texture via cit resewn.
Hello, it's very unfortunate to report that we switched from optifine(optifabric) to this mod precisely because of better optimization, since the presence of replaced armor textures through optifine on the screen lowers fps in large numbers, often even below ten.(
Does the author have any ideas for optimizing the work of the mod or is it planned to work on this directly in the plugin itself in the future?

We put 8-12 sets of armor in front of us on the screen and compare the fps with the resource pack, which replaces the armor without it.
Without a resource pack with armor fps 140+, with it about 48-65. The Iris shader engine finishes off the fps, dropping it to 38-45 in idle and 15-27 when looking at the armor. Sometimes even up to 7 frames.
Our server is running with a lot of changed armor, we often have large squads of players together, arranging battles or peaceful events. Armor has a terrible effect on fps.(

**Comment by ccyounga** [comment]
It works, it's a must-have. Thank you!

**Comment by SHsuperCM** [comment]
There is not much I can do besides that really for optimization. I added the cache slider config after I noticed the performance issues with large packs as well. The default config is every 1 tick rather than realtime which seems to be the best option for most pack setups.
Of course, if you are using large packs you can increase that and you'll just have to let your players know to do that.

**Comment by DonFlymoor** [comment]
Perhaps in the cit config file you can specify the update rate so packs that need to change it can. With multiple packs the lowest cache refresh rate wins, and manually changing the slider from default overrides the pack configs

**Comment by SHsuperCM** [comment]
@DonFlymoor 
> Perhaps in the cit config file you can specify the update rate so packs that need to change it can. With multiple packs the lowest cache refresh rate wins, and manually changing the slider from default overrides the pack configs

Packs by default wont declare what cache rate they need, making the default be once a tick(like it is by default in the mod config).
Once a tick works great for most packs and computers, this should only really be changed if either is beyond the norm. (large packs or slow pcs)
