### ISSUE TITLE
Unsupported format of nbt.Enchantments

### ISSUE THREAD

**Issue by TYPOWYSEB4** [SHsuperCM/CITResewn#232]
As Example I will show bow with **flame** and **infinity**

Unsupported format of nbt.Enchantments
![image](https://user-images.githubusercontent.com/68444050/215141240-69b812a1-0990-440f-a40a-d059cc65b41c.png)

Working format of nbt.Enchantments
![image](https://user-images.githubusercontent.com/68444050/215141307-babd3957-4c0d-46a0-a05c-a74b3c56db2d.png)

**Comment by SHsuperCM** [comment]
Only numbers and strings can be matched using regex, whole nbt compounds or lists are not supported intentionally.
