### ISSUE TITLE
Packs that require OF doesnt work

### ISSUE THREAD

**Issue by Dragzyy** [SHsuperCM/CITResewn#234]
So idk if i understood how the mods work but i think that packs that require OF have to work without it if you have the mod on. So there is a durability pack that makes it so when ur armor piece is low it turns red and when it even more low it turns dark red and it requires OF but it doesnt when i dont have OF and the CIT mod on

**Comment by SHsuperCM** [comment]
The pack needs to use CIT, as this is what CIT Resewn adds. If the pack is cit it should work and if it doesnt you need to open an issue with both the logs and the pack in question.
