### ISSUE TITLE
What future of this mod in 1.20?

### ISSUE THREAD

**Issue by deceased-a** [SHsuperCM/CITResewn#235]
The question is about the same as the question with the existence of, for example, all the other visual resource packs (according to NBT information). Namely, in individual or complex elements (and even in parts of names), the potentially possible numbers of variations (almost to infinity). What the future will be like by 1.20?

**Comment by SHsuperCM** [comment]
What exactly are you asking about? If you are talking about armor trims the plan currently is to have the armor type work exactly as before, you could target and replace specific layers and tris shouldnt be any different.
