### ISSUE TITLE
I would love to use this version on the latest snapshots of Minecraft, will there ever be a snapshot build availible?

### ISSUE THREAD

**Issue by chrisizatt** [SHsuperCM/CITResewn#236]
I tried using the 1.19.3 version on the latest snapshot and it crashed.
Thank you!

**Comment by unit-a-user** [comment]
Please, unify my issue with that.
https://github.com/SHsuperCM/CITResewn/issues/235

**Comment by SHsuperCM** [comment]
I barely consider updating to 1.19.4 after the mess that mojank did, breaking every version semantics possible. No, the mod will not be officially ported to snapshots. 

The 1.19.3 version was never supposed to work on anything other than 1.19.3.

Any released version past 1.19.2 is a snapshot for 1.20 and they have no relation anymore to 1.19.
