### ISSUE TITLE
Bundle textures not compatible with optifine

### ISSUE THREAD

**Issue by MISMASJETU** [SHsuperCM/CITResewn#237]
So, hi.
Today, I tryed to retexture bundle with a specific name. However, I can't find a method that works on both CITResewn AND Optifine (since its supossed to be added onto my SMP, I need it to be compatible with both) I hope I can find out whats wrong, I just spent my entire afternoon working on this

The method working on CITResewn
`type=item`
`items=minecraft:bundle`
`model.bundle=item/tcg_emerald_open`
`model.bundle_filled=item/tcg_emerald`
`nbt.display.Name=ipattern:Om Nom Lands TCG: Emerald Booster Pack`

And this one is working on optifine
`type=item`
`items=minecraft:bundle`
`texture=tcg_booster_emerald`
`nbt.display.Name=ipattern:*Om Nom Lands TCG: Emerald Booster Pack*`
`nbt.Items=exists:true`

`type=item`
`items=minecraft:bundle`
`texture=tcg_booster_emerald_open`
`nbt.display.Name=ipattern:*Om Nom Lands TCG: Emerald Booster Pack*`

(Also, I am quite new to CIT, so there is a high chance I am missing something)

**Comment by SHsuperCM** [comment]
The official way would be to use `texture.bundle_filled`. That not working on optifine is an optifine issue.

If however you want to use the latter approach, the `exists:` check is not in cit resewn yet. Follow issue #204 to know what happens with it.
