### ISSUE TITLE
crashed when rendering custom elytras

### ISSUE THREAD

**Issue by lcy0804** [SHsuperCM/CITResewn#239]
Hi, I'm having an issue when the game rendering the optifine CIT elytras pack, my game crashes with rendering entity in world.
![image](https://user-images.githubusercontent.com/126999572/222939044-5aaa0c92-20a2-423f-b70e-4cf53627d275.png)

**Comment by SHsuperCM** [comment]
Pack has broken paths. Fix the pack or enable broken paths in the config. 
If the issue persists no further support will be provided.
