### ISSUE TITLE
texture.bow_pulling_{0,1,2} not implemented/broken

### ISSUE THREAD

**Issue by boerdereinar** [SHsuperCM/CITResewn#24]
Skipping sub cit: No such sub item model "bow_pulling_0" in Squishy's+Enchanted+Items.zip -> optifine/cit/0_bow/properties/flame.properties

Bow pulling item textures are throwing errors in this resource pack:
https://www.curseforge.com/minecraft/texture-packs/squishys-enchanted-bows

**Comment by SHsuperCM** [comment]
Can you provide the full logs please?

**Comment by boerdereinar** [comment]
https://pastebin.com/9d8DF8jc

**Comment by SHsuperCM** [comment]
Running it in a clean setup with just that resourcepack running it works fine, I think I know what causes this and I already made #19 because of that. I'm closing this issue because a sub item rewrite is already a thing I'm working on. You might want to enable notifications for #19.
