### ISSUE TITLE
Colored Displaynames Not Possible [Feature Parity]

### ISSUE THREAD

**Issue by Jayryn** [SHsuperCM/CITResewn#244]
There's currently no option that I know of using CITResewn to detect colored displaynames (In Optifine possible)

When using the following property, Optifine renders the custom texture but CITResewn doesn't
nbt.display.Name=ipattern:\u00a74\u00a7oMy Sword

**Comment by SHsuperCM** [comment]
The correct way would be to check against the name's json instead of its plaintext representation. The section symbol formatting is long deprecated and should not be used when possible in Minecraft. 

Take a look at your sword's name nbt with `/data` and match against that instead.
