### ISSUE TITLE
1.19.4 Item textures not loading but Models do. (Fixed) From 1.19.3 item directory change

### ISSUE THREAD

**Issue by RCX15** [SHsuperCM/CITResewn#247]
I wanted to update CIT from optifine to CIT resewn since im now using fabric and i noticed my item textures not working but the model of my elytra did while the items its-self did not.

i tried changing my old optifine to copy my CIT file to a new citresewn/cit file but that didn't work, i tried taking a look at different ways for the properties file to take "Items" as a property seeing there was a difference between either selecting "items" or "matchItems" for the texture i tried both and reloaded the texturepack and the game to test and it didn't work.

is this just because the version is so new and some things don't work or am i just being a dumb with the small pieces of code.

Elytra Model:
File Name: neolytra.properties

type=elytra
items=elytra
texture.elytra=neolytra
nbt.display.Name:ipattern:Neolytra

Elytra Item:
File Name: elytra.properties

type=item
matchItems=elytra
texture=neolytra
nbt.display.Name=ipattern:Neolytra

**Comment by NathZen** [comment]
This happened too on damage-based model. The Model is loaded, but the texture is not.

I just found out the Texture must inside textures/block. My previous texture path was a bit scattered like in textures/items, textures/hats, etc.


So the question is, **Do CIT Resewn is unsupporting texture paths other than textures/block**?
CIT Resewn v1.1.2 + 1.19.2 was still fine, but v1.1.3 + 1.19.4 is not

**Comment by SHsuperCM** [comment]
You can close your issues if they are no longer relavant fyi.
