### ISSUE TITLE
CIT items don't show in items frames in 1.19.4

### ISSUE THREAD

**Issue by dbrighthd** [SHsuperCM/CITResewn#248]
![image](https://user-images.githubusercontent.com/68525639/228771217-1ee6199c-5576-40e5-99aa-ac85e78af9ac.png)

**Comment by SHsuperCM** [comment]
Is this singleplayer or are you on a server?

**Comment by dbrighthd** [comment]
I tested it with both single player and multiplayer and got the same result. Once I get back home I can test it without any other mods to see if it is caused by a conflict

**Comment by dbrighthd** [comment]
didn't mean to close the issue, my bad

**Comment by dbrighthd** [comment]
Interesting, it seems to only happen when continuity is on

**Comment by dbrighthd** [comment]
It seems to only happen when using the Moreculling mod

this is a bit concerning just because I believe both CITR and Moreculling are included in the popular Fabulously Optimized modpack

**Comment by dbrighthd** [comment]
I did some research and I see this is a known issue, so ill close this
