### ISSUE TITLE
Custom elytra textures don't work

### ISSUE THREAD

**Issue by RyanCR03** [SHsuperCM/CITResewn#254]
elytra type textures dont render
there were no cit errors in the logs

```type=elytra
matchItems=minecraft:elytra
texture=broken_elytra
damage=431

**Comment by SHsuperCM** [comment]
Send the logs regardless, they show more than errors

**Comment by RyanCR03** [comment]
I realized later that there was an error in the logs sorry i forgot to update the post.
[latest.log](https://github.com/SHsuperCM/CITResewn/files/11258672/latest.log)
