### ISSUE TITLE
Multiple items in property files?

### ISSUE THREAD

**Issue by FrncoDz** [SHsuperCM/CITResewn#255]
Im playing on Minecraft 1.19.2, but the server Im connecting to is 1.8.9, I dont know how the plugins (ViaVersion?) or bridge work, but In my case I want to use a texture pack made for 1.8.9, but Im having issues with the dyes, stained glass and all those items that were changed on the flattening. 

Unless I misunderstood the wiki I read that it can have a list of items in the properties file and the one that matches is the one that gets the texture.
But it also says "Requires that the item is either of the ones listed. Separated by spaces." so what exactly does this means?

Like this?
```
items=minecraft:white_stained_glass_pane minecraft:orange_stained_glass minecraft:magenta_stained_glass etc
damage=5
nbt.display.Name=ipattern:*skyblock level **3
nbt.display.Lore.*=ipattern:*Reward*:*
texture=mcpatcher/cit/ui/textures/bottom_to_right_complete_bar_green
```
Or this?
```
items=minecraft:white_stained_glass_pane
items=minecraft:orange_stained_glass
items=minecraft:magenta_stained_glass
items=minecraft:light_blue_stained_glass
items=minecraft:yellow_stained_glass
items=minecraft:lime_stained_glass
items=minecraft:pink_stained_glass
items=minecraft:gray_stained_glass
items=minecraft:light_gray_stained_glass
items=minecraft:cyan_stained_glass
items=minecraft:purple_stained_glass
items=minecraft:blue_stained_glass
items=minecraft:brown_stained_glass
items=minecraft:green_stained_glass
items=minecraft:red_stained_glass
items=minecraft:black_stained_glass
damage=5
nbt.display.Name=ipattern:*skyblock level **3
nbt.display.Lore.*=ipattern:*Reward*:*
texture=mcpatcher/cit/ui/textures/bottom_to_right_complete_bar_green
```

Note: All the other textures are working and loading fine, the only issues are with the items mentioned that were changed on the flattening

**Comment by SHsuperCM** [comment]
First one, they are separated by spaces in one items property.

The damage line however is weird since glass panes are not damagable.

**Comment by FrncoDz** [comment]
The glass damage is just a property that the item has for some reason, not sure why. Some of the items don't have their textures applied. I used the first one and none of the items listed in there have the texture. Is there a specific way it assigns the texture when multiple ones are selected? I'd like to know how it's done and which is the priority. 

For example, I have two textures for glass, one that is green and one that is red for all glass_panes, and based on NBT that it contains I set the texture.

skyblock_level_1.properties
items=minecraft:all_stained_glass_pane 
damage=5
nbt.display.Name=ipattern:*skyblock level **1
texture=mcpatcher/cit/ui/textures/sb_level_1

skyblock_level_2.properties
items=minecraft:all_stained_glass_pane 
damage=5
nbt.display.Name=ipattern:*skyblock level **2
texture=mcpatcher/cit/ui/textures/sb_level_2

**Comment by SHsuperCM** [comment]
See if you can replicate that item in singleplayer, glass panes just dont have the ability to be damaged in modern minecraft and they may be using some tricks to create that item. (Obviously assuming you didnt actually put in `items=minecraft:all_stained_glass_pane` as that's not an item)

I am closing the issue for now because this is not a possible scenario afaik, let me kniw if you think it should be reopened.
