### ISSUE TITLE
Game crash when trying to render an enchanted book in inventory

### ISSUE THREAD

**Issue by kamild1996** [SHsuperCM/CITResewn#26]
Triggered by:
- `/give @a minecraft:enchanted_book`
- seeing the book in any inventory (player incl. creative, chests and other containers)
- seeing the book in REI

Logs attached - modlist and resourcepack visible inside.
[2021-09-15-7.log.gz](https://github.com/SHsuperCM/CITResewn/files/7172858/2021-09-15-7.log.gz)

[crash-2021-09-15_21.47.05-client.txt](https://github.com/SHsuperCM/CITResewn/files/7172838/crash-2021-09-15_21.47.05-client.txt)

Instance exported from GDLauncher (FTB format?): [Modded Client-Only 1.17.1-1.01.zip](https://github.com/SHsuperCM/CITResewn/files/7172890/Modded.Client-Only.1.17.1-1.01.zip)

**Comment by SHsuperCM** [comment]
The fix will be in next version but for now you can use this: https://mega.nz/file/4aYzGIaZ#L7iTkZcPK6hcKscu2ZfPGvCTJiJ-H-7_Gar-Eg_tcIo

**Comment by SHsuperCM** [comment]
Fixed in [v0.5.4](https://modrinth.com/mod/cit-resewn/version/Pqmm2TG5)
