### ISSUE TITLE
This mod breaks mipmaps

### ISSUE THREAD

**Issue by I-like-Portal-2** [SHsuperCM/CITResewn#263]
**Version: 1.19.3 and 1.19.4**
**Mod loader: both Quilt and Fabric**

So, when I use this mod, the mipmapping doesn't work. Completely.

**With CITResewn:**
![2023-05-14_19 46 17](https://github.com/SHsuperCM/CITResewn/assets/99472757/00a58c50-889f-4f3a-8a72-fe2bb2b6fd25)
![image](https://github.com/SHsuperCM/CITResewn/assets/99472757/ea9a2e62-4f63-4ea8-97a2-8ffd636bf489) 
![image](https://github.com/SHsuperCM/CITResewn/assets/99472757/f33456c7-7da7-4d7a-8614-cf2a50367768)

**How it suppoused to look lile:**
![image](https://github.com/SHsuperCM/CITResewn/assets/99472757/e109af97-28f0-4249-8f59-ece3cb9fea1e)
![image](https://github.com/SHsuperCM/CITResewn/assets/99472757/764e03ac-6435-4812-b727-528a1b2ca048)
![image](https://github.com/SHsuperCM/CITResewn/assets/99472757/e79a9715-b9d9-4030-bf6c-561f7913e252)

Mipmapping _is_ enabled in settings. And I tried disabling the NVIDIA 3D parameters, also didn't help.

Maybe I'm doing something wrong? I don't know, but without this mod everything works just fine. Any help would be appreciated! :)

**Comment by SHsuperCM** [comment]
I honestly didn't know people actually used mipmaps, but sure, this needs to be looked into. Do you have any packs active or is it just with CIT Resewn installed? 

Only thing that could cause iirc this is if a texture that mipmaps couldnt handle is being used(and iirc only in the block atlas), CIT Resewn doesnt mess with mipmaps beyond the possibility of loading extra textures.

**Comment by I-like-Portal-2** [comment]
It looks like it was, in fact, an issue with resource packs. I'm sorry. I was so sure i disabled every texture pack i had. Or maybe i did, but upgrading my pc somehow fixed it. Either way, thank you, even if the problem was me.
