### ISSUE TITLE
CIT resewn can't pickup the model textures

### ISSUE THREAD

**Issue by Sunknight136** [SHsuperCM/CITResewn#265]
It shows as purple and black textures.

**Comment by DTarxan** [comment]
Exactly the same problem

**Comment by SHsuperCM** [comment]
There's not nearly enough information to work with here. Provide the pack, provide your logs, show which item is not working as intended.

At a glance this seems to just be that the textures arent in the atlas which is required in vanilla minecraft now and packs that have textures in weird places need to let the game know. The packs just need to be updated.
