### ISSUE TITLE
Crashes on start

### ISSUE THREAD

**Issue by Fritz-Turner** [SHsuperCM/CITResewn#267]
The only other mods I have is sodium and iris which you said should compatible. When using fabric versions ~0.14.15 or newer, the mod fails to recognize fabric and crashes with the error, "CITResewn is missing dependency fabric, install any version of fabric" any older versions creates another crash with a much less explicit crash report.

**Comment by SHsuperCM** [comment]
![fabric is the modid for fabric api](https://i.vgy.me/7XPtBx.png)
