### ISSUE TITLE
Custom Textures for Animated Items 

### ISSUE THREAD

**Issue by Sylnin** [SHsuperCM/CITResewn#271]
Trying to get a CIT for a recovery compass, but the image remains static, and the needle doesn't move. I feel like I'm missing something here, and I'm not sure how to call the functions that cause the texture to shift with the moving needle. I've attached the resource pack I've been working on...

[Sylnin's Compass.zip](https://github.com/SHsuperCM/CITResewn/files/11793197/Sylnin.s.Compass.zip)

**Comment by SHsuperCM** [comment]
Right now you seem to be targeting items that dont exist in the `items` condition("recovery_compass_26" for example) when there's only one real item which is called `recovery_compass`.

The proper way to do this would be to use actual item models and only have a single CIT to replace the main compass. Take a look at how compass models are set up with model predicates in vanilla.

There's also the `texture.<texture id>=` approach but that's only here for legacy support and I can't recommend it.
