### ISSUE TITLE
CITResewn doesnt works.

### ISSUE THREAD

**Issue by RIllEX0** [SHsuperCM/CITResewn#277]
FreshAnimations - doesnt works
Transform ArmorStand to Player model - doesnt works
Capybara pigs - doesnt works

I dont know why it doesnt, works but theres my modlist:
1.19.4 (Fabric)

Animatica
Appleskin
Architectury
Capes
Chat Heads
CITResewn
Cloth-config
EasyAuth
Essential
Fabric api
Fabric language kotlin
Freelook
Indium
Inventory
Iris
ItemScroller
ItemSwapper
LibIPN
Lithium
Malilib
Modmenu
NoFog
OkBoomer
OwoLib
PlasmoVoice
Reese's Sodium Options
RoughlyEnoughItems (REI)
SmoothBoot
Sodium Extra
Sodium
ViaFabric
Viewmodel Changer
WaveyCapes
WorldEditCUI

**Comment by FlameFire26** [comment]
these textrues works on _Custom Entity Models_ or _Entity Model Features_ with _Entity Texture Features_.
_CITResewn_ is not for them.

**Comment by SHsuperCM** [comment]
Not nearly enough information here. What do you mean it "doesnt work" :/

Show exactly what you think should be happening and isnt happening and send logs. If you crash you need to show your logs as well.
