### ISSUE TITLE
Not visible in the frame

### ISSUE THREAD

**Issue by RevMirin** [SHsuperCM/CITResewn#280]
Not visible in the frame
![image](https://github.com/SHsuperCM/CITResewn/assets/65037385/f7c6f804-a189-4022-af4b-20a274156d58)

**Comment by SHsuperCM** [comment]
I am going to need a lot more information than that. 

Show the item, nbt as well if you are able to.

Show the properties file.

Show your logs.

Is this on a server? Single player? Is the server on paper or modded in any way?

**Comment by RevMirin** [comment]
https://drive.google.com/file/d/1-uzDxFY_6CS9LQWaFffxtCxRAtTqXkKA/view

**Comment by RevMirin** [comment]
Server and single

**Comment by RevMirin** [comment]
[latest.log](https://github.com/SHsuperCM/CITResewn/files/12012871/latest.log)

**Comment by RevMirin** [comment]
Fabric loader

**Comment by SHsuperCM** [comment]
I see that you have more culling, maybe this is related to #288? Try without it
