### ISSUE TITLE
[Suggestion] Add CIT properties for overlays

### ISSUE THREAD

**Issue by Angryfishdonut** [SHsuperCM/CITResewn#282]
I'm a dev on Pu,pkins+, and I think it'd be cool if we could change the shadowy pumpkin overlay based on the rename too so that we don't have to just remove that game feature in order to make our cosmetics usable in-game. Plus, it'd be fun to add things like iron man helmets.

**Comment by SHsuperCM** [comment]
Already in the list of planned features
https://github.com/users/SHsuperCM/projects/3?pane=issue&itemId=17261208
