### ISSUE TITLE
[SUGGESTION] player/mob attacking condition

### ISSUE THREAD

**Issue by Angryfishdonut** [SHsuperCM/CITResewn#284]
I think it'd be cool to change the item texture when the player or mob holding the item attacks. That way I could do sword to mace or sword to nunchuck renames that animate when attacking.

isattacking=true/false
attackduration=(# in ticks or frames the texture lasts before reverting to the original texture)

**Comment by SHsuperCM** [comment]
Holder attacking or not sounds interesting, it could possibly need special handling in terms of caching tho as attacking or not changes frequently and it doesnt modify the item to invalidate the CIT cache.

Attack duration is out of scope, this should be a binary condition and not a case for animations. Should probably be done in a different mod that constantly modifies models or handles animations.
