### ISSUE TITLE
[SUGGESTION] "Distance from" condition

### ISSUE THREAD

**Issue by Angryfishdonut** [SHsuperCM/CITResewn#285]
I wanted to make swords from LOTR that glow blue when orcs are nearby. (in this case, I would make it glow if there were any undead mobs within a certain radius of the player/mob holding the item.)

entitydistancefrom=(specific entity, specific entity 2, example:zombie)|(# of blocks radius)
mobtypedistancefrom=(mob type, mob type 2, example:undead)|(# of blocks radius)
blockdistancefrom=(BlockID, BlockID 2, example:stone)|(# of blocks radius)

I would say it's gamebreaking, but technically you can already make resource packs that give you x-ray or that warn you of durability, so I just want the cool feature lol

**Comment by SHsuperCM** [comment]
You are completely right in saying this is gamebreaking, I could just make a diamond compass and do xray super easily. Not to mention the mob esp this becomes.

Besides that, it also doesnt quite fit the scope CIT Resewn is working in imo. This feature is something a mod should add, not a resourcepack. Regardless of how neat and clean it would be to do in a rcp.

My suggestion would be to make the CIT redirect into a FRAPI model and do this sort of logic in there instead. Or.. just make your own item at that point /shrug
