### ISSUE TITLE
Cit Items Not Showing Up

### ISSUE THREAD

**Issue by sokkawithanokka** [SHsuperCM/CITResewn#287]
Hello!
I have downloaded some cit packs into my resource pack folder and have them selected. Whenever I rename various items in the anvil they do change, however when I place them down onto invisible item frames the original texture appears not the changed one from the cit pack. I have also tried multiple item frame mods but the result is still the same.
My minecraft version is 1.19.2 and I am playing on the better minecraft modpack.
Thanks for the consideration.

**Comment by SHsuperCM** [comment]
There's not enough information to go off of here. I'll need to see logs as well as a reproducible example.
Also I need to know if this is on a server or not and if that server is modded in any way(paper servers for example have this issue)
