### ISSUE TITLE
Emissive textures dont work with armor trims

### ISSUE THREAD

**Issue by gv01d** [SHsuperCM/CITResewn#289]
using prefix _e on trims does not make them emissive

**Comment by SHsuperCM** [comment]
How exactly is this relavant to CIT Resewn? CITR does not do anything with trims nor does it with emissive textures.

**Comment by Cboxhero** [comment]
As mentioned in issue #123 you say that other devs should tackle emissive textures because it's out of scope for you, yet having any plugin that enables emissives is completely negated by CITResewn. (such as https://github.com/PepperCode1/Continuity)
