### ISSUE TITLE
Infinite Loading Loop

### ISSUE THREAD

**Issue by SnowBlizzard1** [SHsuperCM/CITResewn#29]
I am trying to use this mod in a Fabric modpack, but when I boot it up, Minecraft just ends up in a loading loop, as in, the bar would get to the end, the menu would show for a split second, it would start loading from the beginning again, and repeat.

**Comment by SHsuperCM** [comment]
Apologies, for some reason this issue did not show up for me. I cannot help without the logs though, please make the game do that again and send `latest.log` through a service like [pastebin.com](https://pastebin.com).

**Comment by SHsuperCM** [comment]
I'll re open the issue when logs are provided
