### ISSUE TITLE
No Enchantement CIT's for Armor 

### ISSUE THREAD

**Issue by FrogFarming** [SHsuperCM/CITResewn#293]
In Uhc there are packs that make it possible to see the prot level of ur enemy this doesn't work with CITResewn it only shows the CIT on the item and not the armor itself

**Comment by SHsuperCM** [comment]
There is no way currently to replace all textures in the armor type, you must specify the layer replaced for now.

However a solution for this has been in the planned features for a while now in https://github.com/users/SHsuperCM/projects/3?pane=issue&itemId=17261228
