### ISSUE TITLE
[Suggestion] Custom layered textures (item overlays)

### ISSUE THREAD

**Issue by Angryfishdonut** [SHsuperCM/CITResewn#294]
I was thinking maybe there could be a type of texture that instead of just replacing the item, it overlays the texture over it. Like maybe adding a blue gem on a pickaxe, this would allow applying the same overlay texture to multiple items, resulting in a different texture per item. It would simply apply above whatever texture the item would otherwise be. 

overlay=true/false (there would be no use case for false)

Priority level could be assigned, to ensure overlays get properly placed on top of each other

priority=int (example: 1)

for conflict resolution, overlays with the same priority could replace each other with a separate value. smaller number being the one that would be chosen to be displayed.

replacement_priority=int (example :1)

**Comment by SHsuperCM** [comment]
Although it would be neat, it's not possible with either the current or the revisioned way item CITs work internally.
