### ISSUE TITLE
[Suggestion] Custom Color maps

### ISSUE THREAD

**Issue by Angryfishdonut** [SHsuperCM/CITResewn#295]
being able to apply color map tints to grayscaled parts of a texture. Like the foliage tint. saplings in the inventory could change their leaf color based on where the item is or where the player is when the item is in their inventory by applying the vanilla foliage colormap.

foliageTint=true/false

also you could add your own color maps and specify conditions under which a texture would be tinted

colormap=colormap.png
tintx=(x coordinate of color tint pixel to choose)
tinty=(same as above, but the y value)
tinterpolation=true/false (interpolates between tints instead of changing color instantly, also a good excuse to use the wordplay lol)
tinterpolationDuration=int (example:2) (defines duration of the interpolation, also it's fun to say)

**Comment by SHsuperCM** [comment]
A bit out of scope for defaults in my opinion, more of something that another mod should handle within the model json instead.
