### ISSUE TITLE
Crossbows

### ISSUE THREAD

**Issue by Wikinger8** [SHsuperCM/CITResewn#296]
I have tried using this pack but i doesnt work with CITResewn I have tried it with Optifine and everything worked great.

https://faithfulpack.net/addons/loaded-crossbows
https://cdn.discordapp.com/attachments/1124459983468253304/1124462232852504727/LoadedCrossbowsForCompliance.zip

**Comment by Celestia74** [comment]
I had the same problem.
Through a bunch of trial and error, I've found that the last version it works on is 1.18.2. I've tested 1.19 with versions 1.1.0-1.1.2 of the mod, doesn't seem to have any effect. 1.18.2 works fine on 1.1.1 so it must be a change in 1.19 of how the game processes the pack.
I have some ideas on ways to maybe fix this, will update if I find a solution.

**Comment by Celestia74** [comment]
[Loaded_Crossbows_For_Compliance.zip](https://github.com/SHsuperCM/CITResewn/files/13760805/Loaded_Crossbows_For_Compliance.zip)

sorry that took a while, things happened and stuff
I moved all of the textures into the main CIT folder, updated the paths in the .properties files, and it fixed things. I'm still not sure what happened in the game code that broke this, but at least it's fixed now.
