### ISSUE TITLE
Cannot build project

### ISSUE THREAD

**Issue by einmeterhecht** [SHsuperCM/CITResewn#297]
gradle always fails with the following message:
```
> Task :1.19.4:remapJar FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':1.19.4:remapJar'.
> A failure occurred while executing net.fabricmc.loom.task.RemapJarTask$RemapAction
   > Failed to remap, java.lang.IllegalArgumentException: Cannot nest jars into none mod jar citresewn-1.1.3+1.19.4.jar
```

When running with `--info`, it showed the following in the log:
```
> Task :1.19.4:compileJava NO-SOURCE
Skipping task ':1.19.4:compileJava' as it has no source files and no previous output files.
Resolve mutations for :1.19.4:processResources (Thread[#412,included builds,5,main]) started.
:1.19.4:processResources (Thread[#412,included builds,5,main]) started.

> Task :1.19.4:processResources NO-SOURCE
Skipping task ':1.19.4:processResources' as it has no source files and no previous output files.
Resolve mutations for :1.19.4:classes (Thread[#412,included builds,5,main]) started.
:1.19.4:classes (Thread[#412,included builds,5,main]) started.
```

Steps to reproduce:
```
git clone https://github.com/SHsuperCM/CITResewn/
cd CITResewn
gradlew build
```

I have been trying for 4.5 hrs by now, please help

**Comment by SHsuperCM** [comment]
Although it **is** odd that it wont build with pure gradle, any reason you're not using idea to run the tasks?

**Comment by einmeterhecht** [comment]
Good point, tried it out (didn't work right away last time) - still getting the same error...

**Comment by einmeterhecht** [comment]
Tried it again and this time it worked...
Whyever
Thank you very much!

**Comment by einmeterhecht** [comment]
Ok, I just saw it works with the 1.20.1 version but not the 1.19.4 one...

**Comment by SHsuperCM** [comment]
> Ok, I just saw it works with the 1.20.1 version but not the 1.19.4 one...

Are you using the task to properly switch to 1.19.4?

**Comment by einmeterhecht** [comment]
That was it - thanks a lot for pointing me to this stupid mistake

Note to anyone coming around here having the same issue in the future:
- Do not use the Tasks from the root project - use the ones in the folders (at the time of writing "1.19.4" and "1.20.1")
- Use the "stonecutter/Set active version to ..." task before building
