### ISSUE TITLE
CIT Resewn, texture issues and Mizunos decor items bugs

### ISSUE THREAD

**Issue by Animetheemo** [SHsuperCM/CITResewn#302]
![Screenshot_1](https://github.com/SHsuperCM/CITResewn/assets/122403126/be55a03d-3e81-47bd-969d-a558a1c9c24e)

Only one of the CIT packs are having the texture issues, Heritage CIT by HanaTheBanana on Planetminecraft. The models are there just the CIT textures are missing and Mizunos paintings specifically decor items are majorly bugging out. 

I've looked for broken paths in Heritage CIT and their all lowercased and formatted properly.

**Comment by SHsuperCM** [comment]
The pack is not updated for the new texture atlas changes in recent minecraft versions. The textures in the pack are just in the `/textures` folder and that folder's contents aren't in the `blocks` atlas by default so the textures are not being loaded.
