### ISSUE TITLE
1.20 not launching

### ISSUE THREAD

**Issue by Foodie947** [SHsuperCM/CITResewn#304]
The 1.20 version of this mod does not launch for some reason. I would try to start the game, and the mod would not let the game load. I do not know which mod it is incompatible with, but when I remove the mod the game launches normally. Also it looks like proxysoul on this issues page has the exact same problem as me.

**Comment by SHsuperCM** [comment]
There isnt any actionable information in this issue. I need a set of incompatible mods/resourcepacks that reproduce this issue and logs to even consider looking into it.
