### ISSUE TITLE
No textures

### ISSUE THREAD

**Issue by SubzeroManMoney** [SHsuperCM/CITResewn#308]
Hi! I have a problem: Item models are displayed in the resource pack, but textures are not! What could be the problem? I play through the official launcher, version 1.20.1, I have attached all the mods present.
![image](https://github.com/SHsuperCM/CITResewn/assets/143210082/2847dedb-fb15-4b01-93af-15a602a6f89a)
![image](https://github.com/SHsuperCM/CITResewn/assets/143210082/8dfd8cf8-5b64-4b19-a77a-c35624160fbe)

**Comment by SHsuperCM** [comment]
Most times the problem is to do with the pack not being updated and textures not being in the correct folders for the atlas to pick them up. I'd need to see the pack to verify. (also, logs are much more informative than a picture of the mods folder if you open issues in the future)
