### ISSUE TITLE
[feature request] allow CIT to use holding entity's name

### ISSUE THREAD

**Issue by EnderMelody** [SHsuperCM/CITResewn#312]
i would like to make a resource pack that changes the held item of other players based on their name. this would allow more variation in the tools/armor of other players without having to have them rename their tools.
for example, you could parse for the first letter and base the texture off that, so names starting with a-m would have texture 1, and players with n-z would have texture 2.

**Comment by SHsuperCM** [comment]
Added to [planned features](https://github.com/users/SHsuperCM/projects/3?pane=issue&itemId=58070994)
