### ISSUE TITLE
Custom items don't work

### ISSUE THREAD

**Issue by makerski** [SHsuperCM/CITResewn#317]
I have a resource packs with custom items (if diamond chestplate have protection 1 enchant it is blue, if have protection 2 it is white etc.) and i have CIT mod and texturepack dont show the textures, but the custom texture stick with knockback 4 enchant works good on CIT. 
Texturepack: https://www.mediafire.com/file/le05cx0ye977eqf/textures.zip/file

**Comment by SHsuperCM** [comment]
There're too many things in the resourcepack to look at it. Provide a narrowed down pack with what you believe the problem is as well as your logs.
