### ISSUE TITLE
The interface texture does not change

### ISSUE THREAD

**Issue by Waitner98** [SHsuperCM/CITResewn#319]
Hello, I would like to know how to use CIT to change the interface of shulkers, chests and other blocks that have an interface?
I'm playing with the colorful containers darkmode resource pack (https://www.curseforge.com/minecraft/texture-packs/colourful-containers-dark-mode-gui-optifine) which changes the game interface. But I encountered such a problem that without optifine, only the standard interface textures change, and the rest of the textures that are changed using .properties (like a shulker) do not change their texture. For example, a green shulker has the interface texture of a standard shulker, not a green one.
I went into the resource pack, into the .properties files and saw the following lines:
container=shulker_box
texture=green
colors=green
How can I change them so that everything works fine?

**Comment by SHsuperCM** [comment]
CITR only does CITs, not guis, guis is out of scope.

You are probably looking for [OptiGui](https://modrinth.com/mod/optigui)

**Comment by Waitner98** [comment]
Thank you very much
