### ISSUE TITLE
will there be a mod for version 1.16.5?

### ISSUE THREAD

**Issue by Myskatr** [SHsuperCM/CITResewn#322]
Will this mod be available on version 1.16.5, if so, approximately when?

**Comment by SHsuperCM** [comment]
![boogy-back](https://github.com/SHsuperCM/CITResewn/assets/22007921/1482d3b6-fb8a-43bb-a271-8e2b11e34c6d)

**Comment by SHsuperCM** [comment]
Duplicate of #120
