### ISSUE TITLE
Mods for versions 1.19.4 and 1.18.2 are very different

### ISSUE THREAD

**Issue by ccyounga** [SHsuperCM/CITResewn#325]
Hello. I used the mod on version 1.18.2, we installed models on the server with textures for accessories and weapons, armor, everything was fine, it read any optifine formats and paths. The updated mod for version 1.19.4 does not work like that at all. I wanted to update the server to this version, but most of the accessories turned out to be without textures, and some weapon models stopped working. There are too many changes and they are critical, we have a lot of models, it is impossible to try to fix it all by hand, it will take a lot of time. The fittings are provided from various authors from mcmodels and elitecreatures, everything is done correctly in terms of paths, all textures converge and work correctly on 1.18.2 with this mod.
Could you update a mod that was on 1.18.2 to 1.19.4 without your other changes? We cannot use this mod on newer versions.

**Comment by SHsuperCM** [comment]
First off, absolutely no? What you're suggesting I'd do is cursed af :/

2nd, missing textures usually means that you're using textures in paths that arent in the blocks atlas as is required in all 1.19.4 resourcepacks. Vanilla or CIT packs alike.

3rd, if you believe there is an issue with how your pack loads in 1.19.4, create an issue containing both the resourcepack and your logs showing you loading it.
