### ISSUE TITLE
asking

### ISSUE THREAD

**Issue by verixyt3** [SHsuperCM/CITResewn#327]
Hello, I'm asking you to make a version for _1.20.2 fabric or quilt on Modrinth_, **thank you very much!**

**Comment by verixyt3** [comment]
and it's not soon?

**Comment by FITFC** [comment]
We are waiting

**Comment by soystargaze** [comment]
CIT Resewn version 1.20.1 works perfectly in version 1.20.2
Just download the mod and put it in your Fabric modpack.
