### ISSUE TITLE
 Will it help to fix Broken Paths or create my own texture pack for boxpvp?

### ISSUE THREAD

**Issue by Oskar2008pl** [SHsuperCM/CITResewn#328]
Hello would @SHsuperCM help to create texture pack sword,pickaxe,castom armor for boxpvp mode all tutorials were on optifine. And the other texture packs I wanted to use had Broken Paths. Will it help to fix Broken Paths or create my own texture pack for boxpvp?

**Comment by SHsuperCM** [comment]
Apologies but no, I dont assist in making packs.
