### ISSUE TITLE
Resetting model to default

### ISSUE THREAD

**Issue by Rafii2198** [SHsuperCM/CITResewn#329]
I am fairly new to CIT and I was browsing the documentation to learn about it. I am creating an addon for a pack and was trying to change texture of an item which I was failing for a long time not knowing why untill I realized that the item I want to modify has a custom model attached to it.

I wanted to "undo" the custom model and use normal Minecraft item model but I can't find any information if that is possible and my intuition tells me there has to be a way and if that's true, I would appreciate if it was added into the Documentation.

**Comment by SHsuperCM** [comment]
It isnt possible if a pack changes the model with the vanilla approach of replacing the json file. The only way to get the vanilla model back is if you change it in the vanilla models in your addon pack and then have your pack above the pack that changes it.
