### ISSUE TITLE
Cant apply textureOverrideMap when model is specified

### ISSUE THREAD

**Issue by SHsuperCM** [SHsuperCM/CITResewn#33]
All texture properties are ignored if models are specified. 
Need to find a way to use the texture properties as an override map when model is specified.

(Opened after discussion in #32)

**Comment by SHsuperCM** [comment]
Just an update, I'm delaying this fix for after 0.7.0, this is a much more complex problem to solve than anticipated.

**Comment by SHsuperCM** [comment]
<img src="https://i.vgy.me/d9BrEr.png">
I believe I finally got a possible fix working, stress testing it and cleaning up

**Comment by Anfauglir-Jakob** [comment]
That’s great news! I’m looking forward to use the new version and see the models again ^^

**Comment by SHsuperCM** [comment]
Fixed in [v0.7.1](https://modrinth.com/mod/cit-resewn/version/DbOYaOvK)
