### ISSUE TITLE
Replace Fandom wiki with the new wiki

### ISSUE THREAD

**Issue by Rafii2198** [SHsuperCM/CITResewn#330]
Minecraft Wiki was transfered to [Minecraft.wiki](https://minecraft.wiki/) with the Fandom wiki being unmaintained. I think it would be good idea to update the links to new maintained wiki.

**Comment by SHsuperCM** [comment]
Correct me if I'm wrong but this is the only wiki link I found in the docs.

**Comment by Rafii2198** [comment]
Yeah, this is the only case. I created the issue at very late night and didn't search whole docs to check if there are other cases. Thanks for quick fix!
