### ISSUE TITLE
sides of CIT items do not render

### ISSUE THREAD

**Issue by Carsick48** [SHsuperCM/CITResewn#331]
I'm trying to make a CIT pack but parts of the sides just don't render. Is there a fix for this, or is this just a bug with the mod?

- The bug doesn't happen on optifine
- The bug doesn't happen on my other CIT resource pack

**CIT Resewn:**
![2023-10-09_14 54 59](https://github.com/SHsuperCM/CITResewn/assets/147460277/58698d0d-f870-4735-9b6a-41759bbccce9)
![2023-10-09_14 54 44](https://github.com/SHsuperCM/CITResewn/assets/147460277/b17be6a0-c9e7-4548-8227-ce7b4c71ce87)

**Optifine:**
![image](https://github.com/SHsuperCM/CITResewn/assets/147460277/ba9dac62-5222-49ec-9cbc-e41cf994a682)
![image](https://github.com/SHsuperCM/CITResewn/assets/147460277/d95f4f32-07ab-4703-ae82-430fa417e91e)

**Comment by SHsuperCM** [comment]
Send a pack of just the item that's giving you issues and I'll check it out when I'm able to.

**Comment by Carsick48** [comment]
here you go
[obsidian knife.zip](https://github.com/SHsuperCM/CITResewn/files/12852901/obsidian.knife.zip)

**Comment by Carsick48** [comment]
> Send a pack of just the item that's giving you issues and I'll check it out when I'm able to.

here you go
[obsidian knife.zip](https://github.com/SHsuperCM/CITResewn/files/12852912/obsidian.knife.zip)

**Comment by Oskar2008pl** [comment]
@Carsick48 do you know how to make custom sets on boxpvp?

**Comment by Carsick48** [comment]
> @Carsick48 do you know how to make custom sets on boxpvp?

no

**Comment by SHsuperCM** [comment]
Sorry for the delay, I cannot reproduce the issue. Will need logs to further investigate.

Reopen the issue with the new issue form if you still want help with it.
