### ISSUE TITLE
[1.20.1 Quilt] cit textures don't show up on custom cit models

### ISSUE THREAD

**Issue by glittermutt** [SHsuperCM/CITResewn#332]
log attached! it worked just a few days ago, no idea what happened ;;
[new_log.txt](https://github.com/SHsuperCM/CITResewn/files/12859438/new_log.txt)
![2023-10-10_21 15 02](https://github.com/SHsuperCM/CITResewn/assets/134949309/13ad9d14-b7c4-4a0b-93ae-9e6675e19e24)

**Comment by SHsuperCM** [comment]
Quilt was never supported.
