### ISSUE TITLE
[1.20.1 Fabric] cit models do not have textures

### ISSUE THREAD

**Issue by glittermutt** [SHsuperCM/CITResewn#333]
alright, i tested it out on fabric too (just fabric, the api and cit resewn) - the issue is still there. both with broken paths turned on and off
heres the log
[log1.txt](https://github.com/SHsuperCM/CITResewn/files/12860405/log1.txt)
![2023-10-10_22 59 15](https://github.com/SHsuperCM/CITResewn/assets/134949309/10f3433d-b038-41ef-8b0b-59b8210c0225)

and heres the resource pack, if you need it
[heritage-cit.zip](https://github.com/SHsuperCM/CITResewn/files/12860409/heritage-cit.zip)

**Comment by SHsuperCM** [comment]
The pack was not updated to 1.19.4 properly. The textures in the root `textures/` folders are not added to the blocks atlas by default and so you either move the textures to the items' or blocks' textures folders so they'll be loaded by the atlas or you add an atlas configuration entry to add those textures. (it's a vanilla resourcepack thing issue)
