### ISSUE TITLE
Lacks optimization

### ISSUE THREAD

**Issue by ccyounga** [SHsuperCM/CITResewn#335]
Greetings. I've been using the mod on version 1.18.2 for a long time. The only way that will help increase FPS is to increase cache_ms in the config. However, this is not an absolute solution and is far from ideal. I'm still looking at a few armored players with nbt stat tags from the mmoitems plugin that are taking 20 or 30 fps out of me.
Will there be another way to optimize?
I also wouldn’t want the author to abandon older versions, since you are still making a mod not only for yourself. Many server creators are on older versions because the newer versions contain a lot of problems. The same transition from version 1.18.2 to 1.20.2 is quite complex and long, in some places impossible.

**Comment by SHsuperCM** [comment]
> I also wouldn’t want the author to abandon older versions, since you are still making a mod not only for yourself. 

You are very much mistaken, I make this mod for myself first and foremost and I choose to let others to use it as well as access its source code and do what they want with it under the license. Please understand that I am not obligated to keep older versions updated nor am I obligated to update to newer versions.

As for the rest of the issue, it lacks substance. If you can find a way to optimize it further, please be my guest and open a PR.
