### ISSUE TITLE
 update 1.20.2 ?

### ISSUE THREAD

**Issue by filiporowy712** [SHsuperCM/CITResewn#336]
when will there be an update 1.20.2 
because I can't play without it. This is a great mod

**Comment by loopeniledam** [comment]
The 1.20 version is working for me in 1.20.2. Your mileage may vary however, depending on what other mods you have installed.

**Comment by ShrikerChestTree** [comment]
> when will there be an update 1.20.2 because I can't play without it. This is a great mod
I made this mod for version 1.20.2 and above!
Here is the link: https://github.com/ShrikerChestTree/CITResewn/releases/tag/1.20.2
I'm sorry to post it here because I can't post it in Pull Reguest.

**Comment by ShrikerChestTree** [comment]
> > > when will there be an update 1.20.2 because I can't play without it. This is a great mod
> > 
> > 
> > I made this mod for version 1.20.2 and above! Here is the link: https://github.com/ShrikerChestTree/CITResewn/releases/tag/1.20.2 I'm sorry to post it here because I can't post it in Pull Reguest.
> 
> So what did you change, because your fork seems to be just a fork with no changes?

Modifying fabric.mod file (>=1.20)

**Comment by WeegeeTheDoggo** [comment]
> I made this mod for version 1.20.2 and above! Here is the link: https://github.com/ShrikerChestTree/CITResewn/releases/tag/1.20.2 I'm sorry to post it here because I can't post it in Pull Reguest.

unfortunately this does not work at all. even with just this file and the fabric api, it just tries to load, then crashes immediately

**Comment by ShrikerChestTree** [comment]
> > I made this mod for version 1.20.2 and above! Here is the link: https://github.com/ShrikerChestTree/CITResewn/releases/tag/1.20.2 I'm sorry to post it here because I can't post it in Pull Reguest.
> 
> unfortunately this does not work at all. even with just this file and the fabric api, it just tries to load, then crashes immediately

Bro has already released a new version of the mod (or not) for the new version -.-
Well, if not, then in the search in Modrinth write "CIT Resewn".
