### ISSUE TITLE
1.20.1 - BUG - Consistent Crashes When Using CIT Armor (Attached)

### ISSUE THREAD

**Issue by EnderGamingFilms** [SHsuperCM/CITResewn#338]
Hello, I have encountered gaming crashing when using CIT with these textures (attached). They work fine with normal optifine and I was hoping you would be able to help resolve this issue.

Any and all help would be greatly appreciated and if you need anything from me just let me know!

Here is the crash report: https://pastebin.com/raw/gLdyHtzH

Resources: [minecraft_dungeons.zip](https://github.com/SHsuperCM/CITResewn/files/13038237/minecraft_dungeons.zip)

Version: 1.12.1
Fabric: 0.14.22
CIT: 1.1.3+120

**Comment by SHsuperCM** [comment]
Dont know what made you think this is to do with CIT Resewn as the first line in the stacktrace
```
	at me.pepperbell.continuity.client.resource.ResourceRedirectHandler.redirect(ResourceRedirectHandler.java:65)
```

says that it came from Continuity.
