### ISSUE TITLE
[BUG] 1.19.4 CIT pack dosent work in 1.20.1

### ISSUE THREAD

**Issue by AleksKhaos** [SHsuperCM/CITResewn#339]
in optifine it work, in CIT resewn dont. other 1.19.4 CIT pack works, only this dosent work proprely:

pack with CIT Resewn
![immagine_2023-10-19_173106842](https://github.com/SHsuperCM/CITResewn/assets/148472380/e69d60da-6d78-4c55-bf52-c3ac3cfb5afb)

pack with Optifine/Optifabric [how it should work]
![immagine_2023-10-19_174307962](https://github.com/SHsuperCM/CITResewn/assets/148472380/98e53126-dc85-4ad2-941d-09def422dcdd)

i need fabric bc of some mods, but Optifabric is giving me problems, so im searching for alternatives and now there is this problem, is there a fix for this? anything really, recoding or how to change version or other, here is the texture pack if someone needs it

[Dee's+Extended+Equipment.zip](https://github.com/SHsuperCM/CITResewn/files/13044724/Dee.s%2BExtended%2BEquipment.zip)

**Comment by SHsuperCM** [comment]
As of 1.19.3, textures in non-standard locations in resourcepacks are no longer automatically added to the blocks atlas. You have to specify the folders manually in the atlas json.
