### ISSUE TITLE
cit for bows

### ISSUE THREAD

**Issue by literallyducky** [SHsuperCM/CITResewn#342]
i transferred from optifine to citresewn i was trying to do textures for bows and when i try the same .properties it doesnt work and ive look around CIT Resewn's docs and cant find anything for bows here is the  .properties for the bow that works in optifine      type=item

items=minecraft:bow

texture.bow_standby=teleport_bow_standby.png

texture.bow_pulling_0=teleport_bow_0.png

texture.bow_pulling_1=teleport_bow_1.png

texture.bow_pulling_2=teleport_bow_2.png

nbt.display.Name=ipattern:*teleport bow*

**Comment by SHsuperCM** [comment]
Cannot help without seeing the logs.
