### ISSUE TITLE
bundle custom item texture is not working

### ISSUE THREAD

**Issue by n00naamee** [SHsuperCM/CITResewn#344]
I want to make texture icon for my saves items, but CIT dont working with bundle custom texture.

(Sorry, if my ask a incorrect, i don`t know English)
![image](https://github.com/SHsuperCM/CITResewn/assets/140509844/1ef1b9a2-6d71-4e02-bae2-fe2424896ccf)
![image](https://github.com/SHsuperCM/CITResewn/assets/140509844/109c89fd-cacf-44ed-b7de-6eb876c11400)
![image](https://github.com/SHsuperCM/CITResewn/assets/140509844/b958167e-08ba-4ad2-9887-bd60a30cd67b)

**Comment by SHsuperCM** [comment]
I'm not understanding what the issue is. In any case, know that textures and other resourcepack file names cannot have capital letters.

**Comment by Lucipo** [comment]
what mod provides that ui? very curious

> I want to make texture icon for my saves items, but CIT dont working with bundle custom texture.
> 
> (Sorry, if my ask a incorrect, i don`t know English) ![image](https://private-user-images.githubusercontent.com/140509844/279357071-1ef1b9a2-6d71-4e02-bae2-fe2424896ccf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNzU4NzgsIm5iZiI6MTcwNjA3NTU3OCwicGF0aCI6Ii8xNDA1MDk4NDQvMjc5MzU3MDcxLTFlZjFiOWEyLTZkNzEtNGUwMi1iYWUyLWZlMjQyNDg5NmNjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNFQwNTUyNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NmVlYzRhODNlNzViYjI4NjVhZDk5YWU0NjllNTBiOGUxODZlZTljM2Q0OTNlMjViM2FmYjc4ZGE4Mjk0MDgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.w7gWNNFnmmsLrH_vKHQ7S5Kxa4ftr6MpJPTbMH95-14) ![image](https://private-user-images.githubusercontent.com/140509844/279357143-109c89fd-cacf-44ed-b7de-6eb876c11400.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNzU4NzgsIm5iZiI6MTcwNjA3NTU3OCwicGF0aCI6Ii8xNDA1MDk4NDQvMjc5MzU3MTQzLTEwOWM4OWZkLWNhY2YtNDRlZC1iN2RlLTZlYjg3NmMxMTQwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNFQwNTUyNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MGM3MjhhNGM2NmUyN2U3MzMxNDM4ZjdkYzE5YjMxYzUwYmMzYmI2MzY1OGFhZTA0YmVkZGY1MzYwYjExMGY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gs7sK0eERPCcLJ5QPW19egnnK4DDsIQ0jiT9SrDjG0o) ![image](https://private-user-images.githubusercontent.com/140509844/279357176-b958167e-08ba-4ad2-9887-bd60a30cd67b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNzU4NzgsIm5iZiI6MTcwNjA3NTU3OCwicGF0aCI6Ii8xNDA1MDk4NDQvMjc5MzU3MTc2LWI5NTgxNjdlLTA4YmEtNGFkMi05ODg3LWJkNjBhMzBjZDY3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNFQwNTUyNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZTE1NmUwNzdiMTUzNDAxYTk3ZGFmNTI1YTBiZDJlYmZmYjRlZmU2NTlmYzA2OWM5YWFjYjNmYWIwMjAyMDY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.X510NQ96UQQ7U4XHx984ZMhS_se55KwfWgdKYbkvabs)
