### ISSUE TITLE
CIT Items show default textures when put in item frames

### ISSUE THREAD

**Issue by RachelleDraws** [SHsuperCM/CITResewn#345]
A renamed item that correctly displays in the player's hand.
![2023-11-01_19 50 59](https://github.com/SHsuperCM/CITResewn/assets/25173576/0091ce42-c539-4187-a826-1c46e867c4b7)

...Will not display its custom texture when placed in an item frame.
![2023-11-01_19 51 10](https://github.com/SHsuperCM/CITResewn/assets/25173576/a455f7f1-7775-482b-a27e-7f374c10f392)

This is despite Optifine's CIT displaying custom items in item frames correctly.

**Comment by RachelleDraws** [comment]
This is as of the most recent version, V1.1.3+1.20

**Comment by SHsuperCM** [comment]
Suspecting you have MoreCulling installed as I've seen this issue happen with that. If not, I cant help without seeing the logs.
