### ISSUE TITLE
Resource Reload Fail on seemingly "Non [a-z0-9/._-] character"

### ISSUE THREAD

**Issue by Zetsphiron** [SHsuperCM/CITResewn#35]
Resource reload fails on packs where a .properties file *seemingly* contains a non alphanumeric or comma/underscore/dash character.

The error line shows like this:
`java.util.concurrent.CompletionException: net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: minecraft:optifine/cit/custom elytras/after2020/a.properties`

The file's contents are these (a.properties):
```
type=elytra
matchItems=minecraft:elytra
texture=a
nbt.display.Name=iregex:(crimson elytra)
```

Another example (dancer's sword.properties; another error caught with another pack):
```
type=item
items=minecraft:diamond_sword minecraft:netherite_sword
model=optifine/cit/models/melee_scale_x32_dancer's_sword
texture=dancer's_sword
nbt.display.Name=pattern:Dancers Sword
```

**Comment by SHsuperCM** [comment]
Working as intended, pack format 3 enforces snake_case in resourcepacks.

To use the pack, either fix its paths or enable `Broken Paths` in CIT Resewn's config(requires a restart)

**Comment by Zetsphiron** [comment]
Ah, understood
I suppose OptiFine fixes/interprets them in the correct format by default then?

**Comment by SHsuperCM** [comment]
Optifine is a mess, I'm assuming they just didnt care about the specifications when format 3 came out and now they dont want to fix it because it'll break too many cit packs for them and also they mainly focus on shaders these days from what I can tell.
