### ISSUE TITLE
[Help Needed] Load entity textures in model

### ISSUE THREAD

**Issue by Disketaa** [SHsuperCM/CITResewn#352]
Hi! I want to ask, is it possible to load textures for model straight from textures/entity folder? 

```
	"textures": {
	    "0": "entity/cat/all_black"
	},
```

My custom item but textures are broken
![image](https://github.com/SHsuperCM/CITResewn/assets/76956762/2c0410ff-a30b-4bb6-bd98-b0cf4b0fd31c)

**Comment by SHsuperCM** [comment]
In modern minecraft versions, you need to specify to the game that you want a texture in the atlas for it to be added. Specifically for blocks/items you need to add the texture to the blocks atlas.

This is a vanilla resourcepack thing, there should be info online on how to do that.
