### ISSUE TITLE
Enchantment glint does not appear

### ISSUE THREAD

**Issue by iCreatedThisAccountForThisOneIssue** [SHsuperCM/CITResewn#355]
i am pretty sure there must be a way to activate the enchantment glint, i asked in every subreddit i could for help, but no one replied.
so i had to make a github account hoping i'll get an answer.
the issue is basically that, i don't see any enchantment glints and i have no idea how to activate them, i'm not even sure if i should post this, i think this place is for bug reports, but i am desperate.

**Comment by SHsuperCM** [comment]
What leads you to believe this is related to CIT Resewn? What about sending logs? there is not enough information to keep this open.

**Comment by iCreatedThisAccountForThisOneIssue** [comment]
> What leads you to believe this is related to CIT Resewn? What about sending logs? there is not enough information to keep this open.

When i remove CIT, the problem stops, this is why i believe the problem has to do with CIT, but if you think the problem might be something else, please tell me!
