### ISSUE TITLE
[Help Needed] Translatable names

### ISSUE THREAD

**Issue by Disketaa** [SHsuperCM/CITResewn#356]
Hi! Is there a way to set a localized string to an item name in CIT Resewn?

![image](https://github.com/SHsuperCM/CITResewn/assets/76956762/4faac7b8-fe34-47ed-a3a5-51d687a7f12f)
Something like this ^

**Comment by SHsuperCM** [comment]
Does what you had not work? also, send logs just in case there might be an error.

**Comment by Disketaa** [comment]
![image](https://github.com/SHsuperCM/CITResewn/assets/76956762/54a40fdd-40a9-40fa-b0b7-faafcaf24697)

**Comment by SHsuperCM** [comment]
Look at the item's nbt and make sure it uses a translatable component, just naming an it "Apple" in an anvil will only change the text to apple, it wont translate after

**Comment by Disketaa** [comment]
![image](https://github.com/SHsuperCM/CITResewn/assets/76956762/5f2c8317-cb42-4ac1-9d3b-49638fa62688)
![image](https://github.com/SHsuperCM/CITResewn/assets/76956762/bb2f7982-134d-4f94-bd31-7023c1efa8a5)

**Comment by Disketaa** [comment]
Yeah, thanks working! Thanks a lot! 🔥
But given item with `"italic": false` or `"color": "red"` it also should be written in cit properties
Can it somehow be optimized with `**` or `regex` idk

![image](https://github.com/SHsuperCM/CITResewn/assets/76956762/5cca509d-48ed-48e9-86b1-f864ec8bff80)

**Comment by SHsuperCM** [comment]
Closing as this appears to be resolved but definitely. You should be able to match with a regex and target the translatable component. Check the docs for how to match regex.
