### ISSUE TITLE
Crash on joining hyPixel skyblock

### ISSUE THREAD

**Issue by CuteistCat** [SHsuperCM/CITResewn#362]
it apears that at shcm.shsupercm.fabric.citresewn.defaults.cit.types.TypeEnchantment$Container.setContext(TypeEnchantment.java:219) causes a nullpointer expection

[log](https://mclo.gs/GqCKEaI)
Steps to repruduce:log into hypixel skyblock

**Comment by SHsuperCM** [comment]
CIT Resewn is wrutten for fabric and as such support will not be provided for quilt. If you can reproduce the issue with fabric I can take a look.
