### ISSUE TITLE
Vanilla Cape overrides custom elytra texture

### ISSUE THREAD

**Issue by Bowswa** [SHsuperCM/CITResewn#365]
Hello!

A bug i saw was fixed in a previous version, my custom elytra texture was blocked by the cape texture i was wearing. 

This is in the latest 1.20/1.20.1 version of the game.
Console log had no errors of any kind from this mod(i did find a few with other mods/packs though).

**Comment by SHsuperCM** [comment]
Logs tell much more than errors. I'll need them to check this out.
