### ISSUE TITLE
Crash exit Code -1 when launchign 1.20.4

### ISSUE THREAD

**Issue by maxrcobl** [SHsuperCM/CITResewn#366]
Whenever I try to launch 1.20.4 I get exit code -1, and I cant find anything a bout it online. It also launches fine whenever I don't have CIT resewn in the mod folder

**Comment by dicedpixels** [comment]
The mod isn't updated for 1.20.4.

**Comment by SHsuperCM** [comment]
As dicedpixels says, the mod is not out on 1.20.4 yet. Also exit codes are not useful without the logs.
