### ISSUE TITLE
Translucent Armor

### ISSUE THREAD

**Issue by Vitalitykai** [SHsuperCM/CITResewn#367]
I have been working on a texture pack for a plugin called slimefun. In this plugin there is an armor set called "Slime Armor". As the name says its made out of slime. So properly portray this armor i wanted to make the textures translucent. Is this possible using CIT?

**Comment by HiWord9** [comment]
I think u should use translucent texture to get it. As u draw in argb, u should be able to set opaque as alpha channel.

**Comment by SHsuperCM** [comment]
Not currently possible as the armor renderer uses cutout blending and as such does not support translucency. 
This might be a thing you could do later down the line when the armor cit type will get a rework but I cannot guarantee it.
