### ISSUE TITLE
CIT using an absurd amount of RAM and causing performance issues

### ISSUE THREAD

**Issue by Tempest-5ky** [SHsuperCM/CITResewn#368]
Pretty much what it says on the tin- CIT v1.1.3 in fabric 1.20.1 uses up to 4GB of memory at times, which adds up quickly on an already large modpack.

heapdump:
![image](https://github.com/SHsuperCM/CITResewn/assets/99220350/0df9342d-66ef-48cc-abfb-d1e74a338feb)
![image](https://github.com/SHsuperCM/CITResewn/assets/99220350/b7c8870f-71fb-4937-8446-04524cf1d0e9)
heap summary via Spark: https://spark.lucko.me/ByiMEADnbo

As you can see, the mod uses far more memory than it should, an issue that definitely needs addressing. Just removing this mod cut down the modpack's memory usage by 40-50%.

**Comment by SHsuperCM** [comment]
It's sadly a fight of performance vs ram usage that stems from the cache. 
Especially when there are a lot of items present.

Turning caching down to realtime in the config should help with ram usage.

If you have any ideas to address this, feel free to PR.
