### ISSUE TITLE
New Possible Feature?

### ISSUE THREAD

**Issue by Codehogg** [SHsuperCM/CITResewn#373]
This isn't so much of an issue as it is a bringing to light of the possibility of a new feature.
I've discovered this little known mod (only 100 downloads on modrinth) which has seemingly been abandoned at this point, but did achieve something great. The ability to change the model and texture of things like on-player armor and tridents via different nbt changes, much like CIT, CEM and the like.
I'm bringing this to the attention of the teams behind mods such as CIT, ETF, and EMF to hopefully garner a coherent way of achieving this same thing, but in a more reliable and rigorous manner, as what these 3 teams do is phenomenal. These 3 mods are commonly used in conjunction with one another when using texture packs that have many custom textured/modeled items/entities, go figure. I do believe that the reason for which this may not have been done already with things like the armor models and trident models is due to how they are coded into the game itself and the general consensus that it wasn't really possible. But due to this mod developer's contribution, it's clear that it is possible, but may need better execution. 
I will link the mod I am referencing at the end of this reading. 
This mod, the way it is coded, is not compatible with any of the other more established aforementioned mods, which is unfortunate. 
I hope that by bringing this to the attention of the mod teams behind the scenes of such great mods, I can trigger a revolution of nbt based customization. Now I have close to no idea how java works, if I had, I would have likely tried making this myself, but I hope that by at least bringing it to light something can be done.
https://modrinth.com/mod/predicate-custom-models
I wish you all luck in figuring out how this may function, if you do that is, and I hope to see this working in the future. 
If not, then so be it, the custom texture community has survived this long without it hasn't it?

**Comment by SHsuperCM** [comment]
Armor models through CIT is already planned, as well as tridents/spyglasses and elytras. Not that I could say when they'd be implemented though.
