### ISSUE TITLE
Backport to 1.20.4

### ISSUE THREAD

**Issue by Murchik0v** [SHsuperCM/CITResewn#374]
this mod not working in 1.20.4

**Comment by nco2k** [comment]
i understand that it can be annoying for devs to read such requests, but lets not forget that many important mods rely on this one to work.

**Comment by OCTAMIUM** [comment]
please update it

**Comment by MuhammadrizoDeveloper** [comment]
Pls update it, many mods and resource packs are not working

**Comment by SHsuperCM** [comment]
Duplicate of #358 
Do not open extra issues for updating please, all this does is delay the update.
