### ISSUE TITLE
the texure pack isn't working

### ISSUE THREAD

**Issue by Najiazs1** [SHsuperCM/CITResewn#375]
the texture pack isn't working when i change the name of the sword and axe what should i do since it isn't working

**Comment by YoussefKarim** [comment]
same here idk why

**Comment by YoussefKarim** [comment]
I downloaded the CIT resewn but no it's no use

**Comment by YoussefKarim** [comment]
for more insight on the problem the resource pack Cyber Experiements doesn't work with the mod

**Comment by SHsuperCM** [comment]
"the texturepack" is not nearly specific enough to provide any assistance. 
@YoussefKarim do not use existing issues without knowing if the problem is the same.
