### ISSUE TITLE
"Mixin apply for mod citresewn-defaults failed"

### ISSUE THREAD

**Issue by EmanYm** [SHsuperCM/CITResewn#378]
Greetings.
I know that CIT-Resewn is not yet released for 1.20.4.  I'm eagerly awaiting the day that it is.
In the meantime, I was updating everything today and figured I'd give it a try, and at the very least give you a crash log to maybe help you guys figure out what to point your mixing spoons at, and also provide something the other tickets failed to do.  Logs!

**Environment:**
- Operating System: `Windows 10` (*Latest updates as of February 15*)
- Minecraft `1.20.4`
- [Fabric Loader `0.15.7`](https://fabricmc.net/use/installer/)
- Allocated RAM: `16 Gb`

**Mods List:**
- [ClothConfigAPI 13.0.121](https://modrinth.com/mod/cloth-config/versions?l=fabric&g=1.20.4&c=release)
- [FabricAPI 0.96.4](https://modrinth.com/mod/fabric-api/versions?g=1.20.4&c=release)
- [BetterEndSky 0.2.1](https://modrinth.com/mod/better-end-sky/versions?l=fabric&g=1.20.4)
- [CameraUils 1.0.9-Beta](https://modrinth.com/mod/camera-utils/versions?l=fabric&g=1.20.4)
- CITResewn 1.1.3
- [CITResewn-JSON Lag Patch 1.1.3.2](https://modrinth.com/mod/cit-resewn-jsonlagpatch/versions)
- [GammaUtils 1.7.19](https://modrinth.com/mod/gamma-utils/versions?l=fabric&g=1.20.4)
- [IKnowWhatImDoing 4.1.1](https://modrinth.com/mod/i-know-what-im-doing/versions?l=fabric)
- [LambDynamicLights 2.3.4](https://modrinth.com/mod/lambdynamiclights/versions?l=fabric&g=1.20.4)
- [MaLiLib 0.18.1](https://www.curseforge.com/minecraft/mc-mods/malilib/files/all?page=1&pageSize=20&version=1.20.4&gameVersionTypeId=4)
- [Litematica 0.17.2-BETA](https://www.curseforge.com/minecraft/mc-mods/litematica/files/all?page=1&pageSize=20&version=1.20.4&gameVersionTypeId=4)
- [MiniHUD 0.30.2](https://www.curseforge.com/minecraft/mc-mods/minihud/files/all?page=1&pageSize=20&version=1.20.4&gameVersionTypeId=4)
- [ModMenu 9.0.0](https://modrinth.com/mod/modmenu/versions?l=fabric&g=1.20.4)
- [RainGlow 1.2.0](https://modrinth.com/mod/rainglow/versions?l=fabric&g=1.20.2)
- [Spark 1.10.60](https://spark.lucko.me/download)
- [StatusEffectBars 1.0.4](https://modrinth.com/mod/status-effect-bars/versions?l=fabric&g=1.20.4)
- [Stenhal 1.4.1](https://modrinth.com/mod/stendhal/versions?g=1.20.4)
- [WorldEdit 7.3.0](https://www.curseforge.com/minecraft/mc-mods/worldedit/files/all?page=1&pageSize=20&version=1.20.4&gameVersionTypeId=4)
- [WorldEdit-CUI 01](https://modrinth.com/mod/worldedit-cui/versions)

**Logs:**
[latest.log](https://mclo.gs/lvIHzHN)

**Comment by SHsuperCM** [comment]
Thank you for the details, closing to not have duplicate issues.
