### ISSUE TITLE
Crash report: The game crashed whilst rendering overlay Error: java.lang.IllegalStateException: Failed to load grass color texture

### ISSUE THREAD

**Issue by OxiClient** [SHsuperCM/CITResewn#379]
My minecraft keeps crashing while i'm trying to use CIT Resewn (If I just remove the mod it works fine)

This is my latest log:
[latest.log](https://github.com/SHsuperCM/CITResewn/files/14664252/latest.log)

**Comment by tmkthegoat** [comment]
ME TOO HOW DO YOU FIX?

**Comment by SHsuperCM** [comment]
Try launching again with broken paths turned off, you can turn it off outside of the game by deleting the config for CIT Resewn.
If crashing persists let me know and I'll reopen the issue.
