### ISSUE TITLE
Add an actual `README.md`

### ISSUE THREAD

**Issue by NatoBoram** [SHsuperCM/CITResewn#38]
The [CurseForge](https://www.curseforge.com/minecraft/mc-mods/cit-resewn) page has a nice description, it would be nice if it was copy/pasted to the `README.md`

**Comment by SHsuperCM** [comment]
Normally users shouldn't download from github unless they're already familiar with the project, github is not meant for end users in my opinion. I added the links to the binaries in the readme so people can go to the descriptions which are more end user friendly.
I'm also working on [citresewn.rtfd.io](https://citresewn.rtfd.io/) and when that's done I'm planning to redo both the readme and the Modrinth/Curse descriptions.
