### ISSUE TITLE
How to change skeleton skull item texture

### ISSUE THREAD

**Issue by Crystal-Spider** [SHsuperCM/CITResewn#383]
Hi, I'd like to change the texture of skeleton skulls when they are items in your inventory (e.g. I don't want to change the texture when the skull is placed or when it's on the entity).  
For some context, I'm trying to use Fresh Animations along with Reimagined FA Patch, and with the latter resource pack the skeleton skulls are invisible, both when placed and when in the inventory. I managed to get the placed skulls to appear, and the only way I found to make the item appear too was to revert the Vanilla skeleton texture (basically, Reimagined makes the Vanilla skeleton texture empty so that it doesn't z-fight with its own models, so if I use a png that only has the skeleton head, the skeleton skull item becomes visible again). However, this method makes the Vanilla skeleton appear both for the entity and the placed skulls, with a visible z-fight.

Is there a way with CITR to change only the skeleton skull item texture? I tried doing this:  
![image](https://github.com/SHsuperCM/CITResewn/assets/65339023/f7a27a15-494d-499b-9067-9ef5cc38ef3d)
But it had no effect (the CEM file is to fix the placed-down skulls).

This is the skeleton.png file: 
![skeleton](https://github.com/SHsuperCM/CITResewn/assets/65339023/23a0d737-834d-40f9-9347-68523da878ee)
.
There are no other relevant logs than these:

> [16:19:52] [Worker-ResourceReload-19/INFO]: [citresewn] Loading item CIT models...
> [16:19:53] [Worker-ResourceReload-19/INFO]: [citresewn] Linking baked models to item CITs...

Is what I'm trying to do possible? Am I doing something wrong?  
Thanks in advance

**Comment by SHsuperCM** [comment]
In the hypixel+ resourcepack I've seen that they replace player head items with cits, what they do is replace the model as well.
Try using an item model instead of just a texture in the cit and see if that helps.

**Comment by Crystal-Spider** [comment]
Thanks to your suggestion, I was able to make it work most of it.  
I'm left with this problem:
![image](https://github.com/SHsuperCM/CITResewn/assets/65339023/506bad28-2d27-4bee-aa57-4081ef9f6a3b)
![image](https://github.com/SHsuperCM/CITResewn/assets/65339023/b24a4306-e5fb-43ef-b73c-5dcd5b296a34)
As you can see, the Wither skeleton has a texture inside too, while my skeleton skull is empty inside. Do you happen to know why this is happening and how to fix it?

Also, can CITR be used to change the appearance of the item when worn in the inventory? 
![image](https://github.com/SHsuperCM/CITResewn/assets/65339023/ef06c94b-7d63-47be-98e4-e689bf655ce8)
![image](https://github.com/SHsuperCM/CITResewn/assets/65339023/1e81e5b1-a655-417a-8ad6-1ea2d96f2fc1)
From F5 the head can be seen, but inside the inventory it is invisible.

**Comment by SHsuperCM** [comment]
You might have luck playing with the item display for head in the item model, I am really unsure why it is not showing up in the inventory for you.

Closing the issue for now, glad it helped
