### ISSUE TITLE
CIT Resewn 1.1.4 Doesn't Work

### ISSUE THREAD

**Issue by UltimatChamp** [SHsuperCM/CITResewn#384]

**Comment by SHsuperCM** [comment]
There is no actionable information in this issue.

**Comment by UltimatChamp** [comment]
No info was provided since CIT on 1.20.4 just doesn't work. This was tested in a **close-to-vanilla instance** _(with only CITResewn, Fabric API and tons of CIT resource-packs)_. The resource-packs start working as soon as downgrading the mod to `1.1.3`!

**Comment by SHsuperCM** [comment]
The very minimum of an issue is including the logs and saying what doesnt work.

**Comment by UltimatChamp** [comment]
Logs do not show anything.
Renaming an item using an anvil doesn't work.
Im using the Modrinth version.

**Comment by SHsuperCM** [comment]
> Logs do not show anything.

That's for the developer you are reporting for to decide.

The mod works well on my end, create a proper issue if you want me to look into why it isnt for you.
