### ISSUE TITLE
CIT was reset after every inventory action with latest release

### ISSUE THREAD

**Issue by HowardZHY** [SHsuperCM/CITResewn#385]
1.20.4-1.1.4
Steps to reproduce:
1. Load any CIT Resource pack
2. Open a chest
3. Existing CIT Textures was reset to vanilla texture after EVERY time you move an item
4. Although CIT Textures was re-shown after cache refresh rate, this is a bit annoying

**Comment by SHsuperCM** [comment]
Oh.. woops, yeah I know why this happens. I'll push a fix with 1.1.5 in a bit.
