### ISSUE TITLE
CIT-Armor not loading 1.20.1

### ISSUE THREAD

**Issue by R1gwald** [SHsuperCM/CITResewn#386]
Im currently working on an assets pack and would like to use CIT for specific items. For Items and Armor. By using optifine everything works fine but not in here. Only Item Textures are loading but not the Armor ones. I have no clue what causes this issue.

This is how im currently trying to load my textures. Seems right for me.
https://github.com/R1gwald/SC-Assets/blob/main/SC_Assets/assets/minecraft/optifine/cit/diabox/road_runner.properties

**Comment by SHsuperCM** [comment]
As specified in the docs, general texture replacement for armor cits is currently not a thing, you need to target the texture you want to replace instead of using the normal `texture=`. (for example `texture.diamond_layer_1=`)
