### ISSUE TITLE
[Question] Enchantment texture priorities on multi-enchanted books

### ISSUE THREAD

**Issue by omega9380** [SHsuperCM/CITResewn#389]
I'm using a resource pack that changes the enchanted book textures based on the enchantments.  I was wondering if you could tell me how CITResewn decides which enchantment texture is picked when the CIT is applied to books with multiple enchantments and whether that can be modified in the resource pack.

For example, this book has Aqua Affinity, Protection III, and Mending, and CITResewn chose the texture for Aqua Affinity:

![2024-04-02_19 17 16](https://github.com/SHsuperCM/CITResewn/assets/13081643/0bbfdb6f-732c-42ea-b10c-14dad1564c97)

Whereas this book has Smite IV, Unbreaking III, and Mending, and CITResewn chose the Mending texture:

![2024-04-02_19 17 23](https://github.com/SHsuperCM/CITResewn/assets/13081643/160cbfa7-d522-4667-bb6b-1949734f7968)

I'd like it to prioritize certain textures, for example Mending, and always choose the prioritized texture if that particular enchantment is on the book.

Is this possible in the resource pack?  I'm using Even Better Enchants by Mythitorium, I just updated the textures based on Faithful x64.  Here's an example of the .properties file he used to make this work (in this case the Mending books):

`type=item`
`items=enchanted_book`
`enchantments=mending`
`texture=mending`

Any help would be great.  Keep up the great work on this mod!

**Comment by SHsuperCM** [comment]
As it says on the docs on enchantment cits.

 > If two glints use the same layer, the one with the higher weight will render and the other will not.
