### ISSUE TITLE
Type=armor CITs not working

### ISSUE THREAD

**Issue by fogggyhead** [SHsuperCM/CITResewn#39]
This is probably a user error since armor and elytra textures seem to work for others. However my armor textures aren't being displayed and no errors are shown in logs. 

As an example, this .properties file is in assets/minecraft/optifine/cit/armor:

```
type=armor
items=iron_chestplate
texture=assets/minecraft/textures/models/armor/golem_heart_layer_1.png
nbt.display.Name:ipattern:*Golem Heart Chestplate*
```

Yet doesn't show in game. This was working just fine in optifine.

**Comment by SHsuperCM** [comment]
Type armor requires a layer to be specified, take a look at optifine's cit_single.properties example file:
```properties
# (Required) Replacement textures.  You need a replacement for each texture in
# textures/models/armor for that armor type.
# For diamond armor,
#   texture.diamond_layer_1=my_diamond_armor_1
#   texture.diamond_layer_2=my_diamond_armor_2
# Leather armor has four layers:
#   texture.leather_layer_1=...
#   texture.leather_layer_1_overlay=...
#   texture.leather_layer_2=...
#   texture.leather_layer_2_overlay=...
# If no texture.<name> property is matching, the generic texture will be used.
texture.<name>=<replacement texture>
```

Simpler declaration support is planned but for now you cant just write `texture=` with `type=armor`.

**Comment by SHsuperCM** [comment]
Also docs are coming soon to help figure these sorts of things out
