### ISSUE TITLE
Update to 1.20.6/1.21?

### ISSUE THREAD

**Issue by Vricken** [SHsuperCM/CITResewn#397]
please

**Comment by SHsuperCM** [comment]
I could, but doing so will mean almost no resourcepack will work with the new item components introduced in 1.20.5.

I am currently waiting to see what the plan going forwards with optifine to see if I want to maintain compatability. You can follow the discussion on sp614x/optifine#7658

**Comment by SHsuperCM** [comment]
I'm leaving this issue open until the mod is updated. If anyone else is reading this, please refrain from making additional issues on the matter.

**Comment by Vricken** [comment]
SHsuperCM have you reached a conclusion regarding components?

**Comment by DontTouchMyTea** [comment]
i'd like it for 1.20.6 too, otherwise grimdark battle pack doesn't work 😔

**Comment by ClixzyFN** [comment]
I somehow update the mod here: [](https://github.com/ClixzyFN/CITResewn-1.20.6/releases)

**Comment by SHsuperCM** [comment]
There is a beta available now for version 1.21(.1). 

1.20.5 and 1.20.6 will not be getting a version.

Take note of #447 for updating packs.
