### ISSUE TITLE
Very odd texture artifact

### ISSUE THREAD

**Issue by Raiguri** [SHsuperCM/CITResewn#400]
When I have RP that have texture that isn't 1:1, for example 64x94, I have very odd texture bug on blocks based on distance. Even if this texture isn't used in any model. Plus very strange noise everywhere.

Another interesting thing, based on how much models are in the pack, the effect becomes stronger regardless of whether they have 1:1 textures in them or not.
But the main condition is that there must be at least one 1:1 texture.
Another interesting point, this bug is also triggered if the texture has a size that is not an **even** size.

![image](https://github.com/SHsuperCM/CITResewn/assets/50903186/8e988da6-9321-4aaa-93aa-1d544cd71b81)
![image](https://github.com/SHsuperCM/CITResewn/assets/50903186/4327e0b6-a372-4baa-a4c8-0b5b4867100d)
![image](https://github.com/SHsuperCM/CITResewn/assets/50903186/655dafdd-8249-443b-87b1-c390da43bf9d)
![image](https://github.com/SHsuperCM/CITResewn/assets/50903186/48bf5bc9-4e89-4e3c-958b-aaed777d4994)
![image](https://github.com/SHsuperCM/CITResewn/assets/50903186/09ec8707-748e-4bc3-8cc1-0830e57bb647)

Fabric, 1.20.1
Only cit resewn installed.

**Comment by SHsuperCM** [comment]
All of this makes sense and is expected, you are expanding the texture atlas and doing so creates artifacts if the atlas has odd or too many textures.
Might also have to do with mipmap settings but I wouldnt know, I dont mess with the atlas usually.

This is not an issue specific to the mod. In general you should have even textures sized by powers of two.
