### ISSUE TITLE
will version 1.20.2 receive the mod?

### ISSUE THREAD

**Issue by piscopancer** [SHsuperCM/CITResewn#401]
Even though v1.1.5-1.20.1 works for 1.20.2, that would be nice if you uploaded appropriate version (1.20.2) so as to help ATLauncher correctly recognize this mod and stop saying "could not find"

**Comment by thesh1xx** [comment]
ask them for fixing their weird mod version checker idk

**Comment by SHsuperCM** [comment]
Will be fixed next time a 1.20.1 version is released
