### ISSUE TITLE
purple and black textures

### ISSUE THREAD

**Issue by ddoonnyy** [SHsuperCM/CITResewn#409]
[BrawlRPlast.zip](https://github.com/user-attachments/files/15524965/BrawlRPlast.zip) - Resourcepack

[latest.log](https://github.com/user-attachments/files/15524969/latest.log) - log

Yesterday we switched to 1.20.1 and use Axiom instead of WorldEdit, we had to download alternatives optifine to load textures normally, but faced the problem that half of the textures - normal, and half black and purple. 
![2024-06-02_15 35 29](https://github.com/SHsuperCM/CITResewn/assets/104261067/199d40c4-bf4b-49a1-98c7-8bf27a03a622)

**Comment by SHsuperCM** [comment]
There are a lot of issues in that pack but the one that sticks out the most is using `textures/blocks/` instead of `textures/block/` for textures.
This would've been fine in older versions but in newer versions the folders for textures have to be set in the blocks atlas json.
