### ISSUE TITLE
Fracium Menu Not Opening/working While pressing Equal

### ISSUE THREAD

**Issue by akasaitama** [SHsuperCM/CITResewn#411]
Idk why but fracium not working when I press equal nothing opend and i restart everything and clear data download new version etc etc but still not working please tell what to do.

**Comment by SHsuperCM** [comment]
????
Tf is fracium

**Comment by akasaitama** [comment]
sorry I mean to say francium

**Comment by SHsuperCM** [comment]
Still no idea what that is or how it is related to anything that's here.
