### ISSUE TITLE
Submodels for specific items not applying

### ISSUE THREAD

**Issue by GleamingPulsar** [SHsuperCM/CITResewn#414]
Hullo. As my account suggests I am new to github, and programing in general (and honestly probably am not going to learn after a certain point, anything beyond what is necessary for fun, and for getting linux mint to work is off the table). Wanted to report an issue for a friend as she "doesn't feel like" doing it herself... anyways, from what I can gather there seems to be an issue with certain item's submodels, although the textures seem to being working correctly. I am not sure what files to post here, so I will need other community members to tell me what files I need to upload to find a solution, so I can act as a relay to fix the problem. This issue is specifically with bows and crossbows, although other items *might* be affected. Sorry for being new and not knowing what to ask for, just want to fix a problem me and my friend group have been having with our pvp game that is supposed to have custom item games. o7.

**Comment by GleamingPulsar** [comment]
Judging from what I can analyze from previous threads, the mod author has attempted to fix this at least once, and several other times randomly closed threads related to this?... why...?

**Comment by vred1** [comment]
I am having this issue with bows on my pack. The submodel no longer applies for some reason
The issue only happens when the bow is in a smaller pack.

https://github.com/user-attachments/assets/a54b9bd5-c425-4967-8832-3621919f3b59

**Comment by vred1** [comment]
I managed to fix, Custom Model data was interfering with the custom model bows

**Comment by GleamingPulsar** [comment]
This doesn't seem to be the issue that I was having. It wasn't that custom data wasn't appearing, it was that the textures wouldn't apply to the model correctly, causing an issue where textures would apply seemingly at random, and cause the crossbow to look like a random assortment of pixels when animated (ie being pulled back, or having a arrow/firework loaded).

**Comment by SHsuperCM** [comment]
I'll need the pack and the logs to investigate this issue further as I cannot guess what your properties look like.
In any case I am closing this issue, if you want me to look into it open a new issue following the new issue template.
