### ISSUE TITLE
Directories with UpperCase symbols not work on linux

### ISSUE THREAD

**Issue by AdamCalculator** [SHsuperCM/CITResewn#416]

**Comment by SHsuperCM** [comment]
Nothing to go off of in this issue, there are zero details given.

In general you cannot use capital letters in resourcepacks.

**Comment by AdamCalculator** [comment]
@SHsuperCM

**Comment by SHsuperCM** [comment]
It doesnt work on windows, there is no difference as long as broken paths is disabled in the config. 
And as I said, there is nothing actionable in this issue. No resourcepacks and no logs. So I cant help you here
