### ISSUE TITLE
Could Animatica/AnimaticaReforged makes CIT Resewn unneeded?

### ISSUE THREAD

**Issue by Ynaught** [SHsuperCM/CITResewn#419]
I see that what you need is "Custom Item Texture" and what Animatica advertises is "animated texture format", I just question if there is overlap there. I know MCPatcher offers alot of things so I could just be mixing things up.

**Comment by TanChenyu** [comment]
Of course not. Custom Item Texture and Animated Texture Format are two different features.

**Comment by Ynaught** [comment]
Figured as much. I really need to look into all the individual features MC Patcher adds. It's hard to keep up. >.<
