### ISSUE TITLE
Items don't change appearance in inventories and on the hotbar

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [SHsuperCM/CITResewn#42]
**MC** 1.17.1
**Fabric API** 0.40.1
**CIT Resewn** 0.7.1

Tested with these resource packs:

[Kal's Expanded Armory](https://www.curseforge.com/minecraft/texture-packs/kals-arms-armor-expanded-java)
[xali's Potions](https://www.curseforge.com/minecraft/texture-packs/xalis-potions)
[Improved Elytras+](https://www.curseforge.com/minecraft/texture-packs/improved-elytras)
[Elytras+ - More Elytras!](https://www.curseforge.com/minecraft/texture-packs/elytras-more-elytras)

Examples:

**Elytras change appearance properly when worn and dropped, but not while viewed in the inventory/on the hotbar.**

![2021-10-03_18 07 30](https://user-images.githubusercontent.com/86702831/135762311-38df4ba6-257d-45db-a22f-082f8b41147c.png)
![2021-10-03_18 07 34](https://user-images.githubusercontent.com/86702831/135762355-d0d9bd14-9cbc-419b-81b7-14f637cdc974.png)
![2021-10-03_18 07 43](https://user-images.githubusercontent.com/86702831/135762357-5fba9f7f-82af-4e91-80b9-86fc93a3af2e.png)

**Potions change appearance properly when held and dropped, but not while viewed in the inventory/on the hotbar.**

![2021-10-03_18 08 04](https://user-images.githubusercontent.com/86702831/135762362-bd093c2c-9b94-495d-8c07-998f536ef951.png)
![2021-10-03_18 08 10](https://user-images.githubusercontent.com/86702831/135762365-4465ac52-b32c-46cd-ae76-8538b541d3d4.png)

**Comment by SHsuperCM** [comment]
Can you provide logs?
Also what elytra are you trying to use specifically in that image(and from what resourcepack)

**Comment by Footage2-Amply-Pounce** [comment]
Log: [latest.log](https://github.com/SHsuperCM/CITResewn/files/7274110/latest.log)

That's a vanilla Elytra renamed in an anvil to Rainbow, from [Elytras+ - More Elytras!](https://www.curseforge.com/minecraft/texture-packs/elytras-more-elytras).

Here are also some examples from Kal's Expanded Armory:

**Netherite Helmet renamed in an anvil to Netherite Crown**

![2021-10-03_18 27 16](https://user-images.githubusercontent.com/86702831/135762993-8b6ffefc-0e99-486e-bfb2-96d02f00897b.png)
![2021-10-03_18 27 06](https://user-images.githubusercontent.com/86702831/135762997-b300c34d-8162-42ea-b367-8e192d1ad7fa.png)

**Netherite Helmet renamed in an anvil to Netherite Light Helmet**

![2021-10-03_18 27 17](https://user-images.githubusercontent.com/86702831/135763034-63370a08-290d-4724-9081-64cc20bc63ac.png)
![2021-10-03_18 27 04](https://user-images.githubusercontent.com/86702831/135763042-7976dd22-2e44-4625-b873-eeff819b70cc.png)

**Comment by SHsuperCM** [comment]
Yeah, there is really no way for me to know what is going on there.. The logs say that CITResewn loaded the resourcepack fine but you also have 366 mods running and one of them is probably the cause, probably some mod is doing something weird with the item renderer(the part that draws items in the inventory/hand).

The rainbow elytra is working fine on my end:
![2021-10-03_19 31 10](https://user-images.githubusercontent.com/22007921/135763158-25cebce0-2aaf-4789-b837-962065871d04.png)

**Comment by SHsuperCM** [comment]
I'll need you to pinpoint the problematic mod by removing and adding them until the elytra appears

**Comment by SHsuperCM** [comment]
Just tested the rainbow elytra on my main pack with 112 mods and it works for me, your mod list is way to big for me to comb through.

I'll reopen the issue once the mod is found.

**Comment by Footage2-Amply-Pounce** [comment]
It's [Eating Animation [Fabric]](https://www.curseforge.com/minecraft/mc-mods/eating-animation-fabric) and they are [aware](https://github.com/Theoness1/EatingAnimation/issues/2) of the issue.

Sorry for wasting your time.

**Comment by SHsuperCM** [comment]
It's no problem, thanks for informing me!
