### ISSUE TITLE
1.20.4 not working with specific nbt tags

### ISSUE THREAD

**Issue by idkmandev** [SHsuperCM/CITResewn#423]
nah just kidding but bro at least give a statement on the development of the 1.21 update. Release it whenever you want but TELL US when that's gonna be, or at least tell us how much is done about the update.

1.21 has been out for almost a month, CIT Resewn updated to 1.21 has been overdue for a long time!!!!

**Comment by idkmandev** [comment]
BRO JUST TELL US, WHEN WILL IT COME. THAT'S IT!!!!

**Comment by mpustovoi** [comment]
See https://github.com/SHsuperCM/CITResewn/issues/417
No eta for now
