### ISSUE TITLE
1.19 not compatible with Sodium

### ISSUE THREAD

**Issue by idkmandev** [SHsuperCM/CITResewn#424]
JUST GIVE US A STATEMENT ON THE PROGRESS FOR 1.21. THATS IT, NOTHING ELSE. JUST PROGRESS.

WHY HAVE YOU SAID NOTHING, IT'S BEEN A MONTH SINCE 1.21 UPDATED

**Comment by Evoal** [comment]
chill dude, check [https://github.com/SHsuperCM/CITResewn/issues/397](This)
