### ISSUE TITLE
Custom item textures not working

### ISSUE THREAD

**Issue by vinnyg0621** [SHsuperCM/CITResewn#425]
I have custom textures in the cit folder of my texture pack, and when I renamed an item, it didn't work.
i'm using forge 1.20.1 with connector 1.0.0 beta.44
![Screenshot 2024-07-04 121822](https://github.com/SHsuperCM/CITResewn/assets/57818441/ebf4d208-a19c-4a88-93e9-a9c0019f1c91)
![Screenshot 2024-07-04 121919](https://github.com/SHsuperCM/CITResewn/assets/57818441/60cf1862-1e0f-4945-bbaf-3548c2d65f94)

**Comment by Evoal** [comment]
there's an error in model link

**Comment by SHsuperCM** [comment]
I dont provide support for connector, you can re-open the issue again if you can reproduce it in fabric. Provide logs if you do.
