### ISSUE TITLE
Hand Crossbow Resource Pack

### ISSUE THREAD

**Issue by Xendaka** [SHsuperCM/CITResewn#440]
I've been seeing about getting this resource pack to work without needing OptiFine as of late via your mod, I've gotten one error fixed but now I have a new one acting up.

Here's the Resource Pack and the error I'm getting in the logs
https://www.planetminecraft.com/texture-pack/hand-crossbow-berserk-crossbow/

[26Aug2024 02:24:08.353] [Worker-Main-7/ERROR] [CITResewn/]: {citresewn} Errored while parsing CIT: Unknown type @L1 in minecraft:optifine/cit/hand/hand.properties from file/hand-crossbow
[26Aug2024 02:24:08.354] [Worker-Main-7/ERROR] [CITResewn/]: {citresewn} Errored while parsing CIT: Unknown type @L1 in minecraft:optifine/cit/matagradones/motosierra.properties from file/hand-crossbow
[26Aug2024 02:24:08.354] [Worker-Main-7/ERROR] [CITResewn/]: {citresewn} Errored while parsing CIT: Unknown type @L1 in minecraft:optifine/cit/metalhand/metalhand.properties from file/hand-crossbow

And here's what I see when I look in the properties itself
type=item
matchItems=crossbow
model=hand.json
model.crossbow_pulling_0=hand_reload_0.json
model.crossbow_pulling_1=hand_reload_1.json
model.crossbow_pulling_2=hand_reload_2.json
model.crossbow_arrow=hand_arrow.json
model.crossbow_firework=hand_firework.json
nbt.display.Name=iregex:Ballesta De Mano|Hand Crossbow|ballesta de mano|hand crossbow

**Comment by Xendaka** [comment]
?????

**Comment by SHsuperCM** [comment]
Obviously dont download random shit from the internet, dont know what this user was about but probably nothing good

**Comment by Xendaka** [comment]
Yeah sounds about right, must be one of those scams, anyway do you think you could lend a hand as to what could be wrong?

**Comment by SHsuperCM** [comment]
Please provide the full logs file

**Comment by Xendaka** [comment]
Ok one moment

**Comment by Xendaka** [comment]
[latest.log](https://github.com/user-attachments/files/16747165/latest.log)

**Comment by Xendaka** [comment]
[latest.log](https://github.com/user-attachments/files/16747227/latest.log)

**Comment by SHsuperCM** [comment]
Speaking of weird internet downloads, where did you download the mod from? 🤨 
The mod version doesnt have the correct spaces and defaults is not packed into the citresewn jar for some reason

**Comment by Xendaka** [comment]
I got CIT Resewn on modrith if that is what you mean
[modrith](https://modrinth.com/mod/cit-resewn)

**Comment by Xendaka** [comment]
Ok I think I realize what's up... it seems Sinytra Connector and Forgified Fabric API don't want to work with CIT Resewn itself, infact the "Unknown Type @L1" part always happens when using Forgifed Fabric and Sinytra Connector

**Comment by SHsuperCM** [comment]
Connector is not officially supported

**Comment by Xendaka** [comment]
Understood, on the bright side atleast I managed to find a forge port of CIT Resewn so no need to continue yapping on here.
