### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by OneWorldStudio** [SHsuperCM/CITResewn#442]
Add support Epic Fight mod

**Comment by SHsuperCM** [comment]
What do you mean by add support? it should be supported by default

**Comment by OneWorldStudio** [comment]
I'm using your mod via Connector in place with EpicFight, but it doesn't fix custom armor with shaders

> What do you mean by add support? it should be supported by default

**Comment by SHsuperCM** [comment]
Again I dont know what you mean by fix. 
In any case I dont officially support connector, if you have an issue you can show how to reproduce with fabric I can look into it.
