### ISSUE TITLE
Hot bar and inventory error

### ISSUE THREAD

**Issue by elchicorepoio** [SHsuperCM/CITResewn#448]
The texture is not visible in the hot bar or in the inventory.
type=item
items=rotten_flesh
nbt.CustomModelData=3
![2024-09-05_23 08 11](https://github.com/user-attachments/assets/62cb6686-9e25-4480-ae89-68c011ac244d)
![image](https://github.com/user-attachments/assets/415f7c8a-45a5-4d1b-9564-f5731ff0e039)

**Comment by SHsuperCM** [comment]
Please provide your latest.log

**Comment by SHsuperCM** [comment]
Issue can be reopened when logs are provided.

**Comment by ODF4** [comment]
> The texture is not visible in the hot bar or in the inventory.

I had the exact same issue as you and I was able to solve it by removing the `eating-animation-1.21+1.9.72` mod. Do you happen to have the same mod installed, considering that the affected item is rotten flesh? Have you noticed if this happens with food items, or mob loot, or any other recognizable pattern?

If you're unsure of what mod might be causing this, I recommend that you remove half of your mods at a time to narrow it down and find out which mod might be the culprit.

**Comment by HiWord9** [comment]
> I had the exact same issue as you and I was able to solve it by removing the `eating-animation-1.21+1.9.72` mod. 

Known issue #418

**Comment by ODF4** [comment]
> Known issue #418

I'm glad to see that we're not the only ones experiencing this, thank you for letting us know!
