### ISSUE TITLE
1.21 not accepting * as wildcard.

### ISSUE THREAD

**Issue by CloverCorp** [SHsuperCM/CITResewn#455]
In 1.21 using * as a wildcard seems to just not function and instead treats it as a regular character.

expected output would look something like this
![image](https://github.com/user-attachments/assets/acf745ae-19c9-4b14-8173-8eb6f998b6d7)

the following two images are current results 
![image](https://github.com/user-attachments/assets/63e6f8c3-b52c-4b50-bf96-8a4bb556f99f)
![image](https://github.com/user-attachments/assets/f9e0c903-855b-400c-883b-f4a369ecf7e9)

**Comment by SHsuperCM** [comment]
Show the actual cit's properties please

**Comment by CloverCorp** [comment]
![image](https://github.com/user-attachments/assets/48728284-2c47-4a9a-ab7e-724adadff287)

**Comment by SHsuperCM** [comment]
It would not actually, to use a wildcard you would need to use `pattern:`(or `ipattern:`) or use a more sophisticated pattern with regex.
