### ISSUE TITLE
Suspicious stew, goat horn, compass CIT broken [1.21]

### ISSUE THREAD

**Issue by meowinqq** [SHsuperCM/CITResewn#456]
**Describe the Issue** (clear and concise description of what the bug is, provide logs)
CIT targeting different suspicious stew effects, different goat horn instruments, and compass lodestone dimensions appear to be non-functional. 
Expected behavior (Optifine 1.21 pre9):
> Suspicious stew effects display custom textures
![functionalstew](https://github.com/user-attachments/assets/71e5bee3-6b70-4f9b-b723-f4321ece0154)

> Goat horns display custom textures
![functionalhorn](https://github.com/user-attachments/assets/cbcecd2d-959d-486b-9acc-86a032326bb4)

> Compass connected to lodestone in the overworld displays custom texture and the animation displays correctly 
[no example image]

Behavior in CITResewn:
> Suspicious stew textures remain default
![buggedstew](https://github.com/user-attachments/assets/339f2bbf-3075-45ab-8894-d671569bc135)

> Goat horn textures remain default
![buggedhorn](https://github.com/user-attachments/assets/46b85473-1791-4650-bdd1-96e6a5d647f6)

> Custom compass texture is displayed, but only the first frame of animation remains functional (arrow stuck pointing forward)
[no example image]

Resource pack: [test.zip](https://github.com/user-attachments/files/16933436/test.zip)
[Logs](https://mclo.gs/0WNymJp)

**To Reproduce** (if applicable, explain how someone would go about reproducing this issue, attach a resourcepack if applicable)
- Run latest CITResewn beta for 1.21
- Use attached resource pack

**Checklist** (go through and check these when relevant)
- [x] I have attached the `latest.log` file relevant to this issue
- [x] I have checked the issues and have not found an existing case of this issue
- [x] I am using the latest version of CIT Resewn for my version of minecraft
- [x] I am using the mod on Fabric Loader
- [x] I have disabled broken paths in the mod's config and the issue persists

**Comment by SHsuperCM** [comment]
These are 3 separate issues it seems. 
- [ ] Suspicious Stew
- [ ] Goat Horns
- [ ] Compass

**Comment by normie-chan** [comment]
I also have [this](https://www.planetminecraft.com/texture-pack/colored-axolotl-buckets/) pack that has custom buckets depending upon the axo in the bucket and it only uses the default one for some reason, gonna hope and assume this getting fixed helps that issue as well!

**Comment by meowinqq** [comment]
@normie-chan that pack hasn't been updated to use the component CIT format, nbt data is no longer used in post-1.20.5 CIT -- i was able to get axolotl bucket CIT working just fine w/ the new format in the latest version of this mod :)

**Comment by SHsuperCM** [comment]
The compass is working as intended.
As per [the docs](https://citresewn.shcm.io/cit/cit_item/) when using a submodel with `texture.sub=` you need to target the file name in the override.

You had:
```properties
texture./compass_01=./compass_01
```

When it should be
```properties
texture.compass_01=./compass_01
```
(note the sub part is just the sub model's name without the `/`)

I dont know why it allows the slash in optifine but it does not warrant a parity fix imo as it is an incorrect cit definition.

**Comment by SHsuperCM** [comment]
Other than that the issues will be out in the next beta release (`v1.2.1`)

**Comment by normie-chan** [comment]
@meowinqq could you please make a tutorial on how to do so, I am a noob at this lol. Plus I have a custom texture that I'd rather not have to waste
