### ISSUE TITLE
CIT for Axolotl buckets are not working.

### ISSUE THREAD

**Issue by Kizzycocoa** [SHsuperCM/CITResewn#458]
The "Bucket of Axolotl" entity cannot be retextured based on axolotl colour

the log entries for the errors are as such:
[01:05:14] [Worker-Main-1/ERROR]: {citresewn} Errored while parsing CIT: NBT condition is not supported since 1.21 @L4 in minecraft:optifine/cit/items/axolotl_bucket/axolotl_bucket_blue.properties from file/Kizzcraft_1.21
[01:05:14] [Worker-Main-1/ERROR]: {citresewn} Errored while parsing CIT: NBT condition is not supported since 1.21 @L4 in minecraft:optifine/cit/items/axolotl_bucket/axolotl_bucket_cyan.properties from file/Kizzcraft_1.21
[01:05:14] [Worker-Main-1/ERROR]: {citresewn} Errored while parsing CIT: NBT condition is not supported since 1.21 @L4 in minecraft:optifine/cit/items/axolotl_bucket/axolotl_bucket_gold.properties from file/Kizzcraft_1.21
[01:05:14] [Worker-Main-1/ERROR]: {citresewn} Errored while parsing CIT: NBT condition is not supported since 1.21 @L4 in minecraft:optifine/cit/items/axolotl_bucket/axolotl_bucket_lucy.properties from file/Kizzcraft_1.21
[01:05:14] [Worker-Main-1/ERROR]: {citresewn} Errored while parsing CIT: NBT condition is not supported since 1.21 @L4 in minecraft:optifine/cit/items/axolotl_bucket/axolotl_bucket_wild.properties from file/Kizzcraft_1.21

This is specifically for the following property:

type=item
items=axolotl_bucket
texture=axolotl_bucket_blue
****** nbt.Variant=4 ******

- [ ] I have attached the `latest.log` file relevant to this issue
- [X] I have checked the issues and have not found an existing case of this issue
- [X] I am using the latest version of CIT Resewn for my version of minecraft
- [x] I am using the mod on Fabric Loader
- [X] I have disabled broken paths in the mod's config and the issue persists

**Comment by SHsuperCM** [comment]
As the error says, `nbt.Variant` is just not a thing in 1.21. 
You need to use the new component check for axolotl buckets, specifically `minecraft:bucket_entity_data`.

**Comment by Kizzycocoa** [comment]
@SHsuperCM how precisely do I do that? Could I have an example replacement line for the CIT for this particular bucket? Does this also affect the Age nbt data too (for baby axolotls in buckets)?

**Comment by HiWord9** [comment]
> how precisely do I do that?

I would try to use the ``minecraft:bucket_entity_data`` component in a command (/give for example) and see what is the way it's written.
Or, i guess even better way, that u can take needed bucket with axololt and use the ``/data get entity @s SelectedItem`` command to see how item's components look like. I Hope it will work

**Comment by Kizzycocoa** [comment]
> > how precisely do I do that?
> 
> I would try to use the `minecraft:bucket_entity_data` component in a command (/give for example) and see what is the way it's written. Or, i guess even better way, that u can take needed bucket with axololt and use the `/data get entity @s SelectedItem` command to see how item's components look like. I Hope it will work

So, I got this: {id: "minecraft:axolotl_bucket", count: 1, components: {"minecraft:bucket_entity_data": {Variant: 0, Age: 0, Health: 11.0f}}}

How do I format the CIT? is it as simple as component.Variant=4 ? I don't know what specifically to type.

**Comment by HiWord9** [comment]
> How do I format the CIT? is it as simple as component.Variant=4 ? I don't know what specifically to type.

i dont know either, just try something and see if it works.
As specified in latest components properties write format, it should be ``components.<name>=<value>``, i guess, in ur case it will be ``components.bucket_entity_data.Variant=4``, try it

**Comment by Kizzycocoa** [comment]
> components.bucket_entity_data.Variant

Excellent! That worked perfectly. Thanks a lot! It may be an idea to update the docs with that format, but that 100% works. I think I can reverse-engineer it with the data get command. Thanks again! :)

**Comment by HiWord9** [comment]
> > components.bucket_entity_data.Variant
> 
> Excellent! That worked perfectly. Thanks a lot! It may be an idea to update the docs with that format, but that 100% works. I think I can reverse-engineer it with the data get command. Thanks again! :)

Glad to help! U can find some examples and rules for components write format [here](https://github.com/SHsuperCM/CITResewn/pull/447#issue-2506817185) if anything, i took a look of how enchantments and level are writen and so could help u

**Comment by Kizzycocoa** [comment]
![2024-09-13_22 19 42](https://github.com/user-attachments/assets/fd4a1e5b-9d46-4c67-b2a5-4a630812a9f4)

😃

**Comment by Kizzycocoa** [comment]
> Glad to help! U can find some examples and rules for components write format [here](https://github.com/SHsuperCM/CITResewn/pull/447#issue-2506817185) if anything, i took a look of how enchantments and level are writen and so could help u

Ah, I see. I hadn't seen that, though it still feels a little complex. For those of us less attuned to the new components CIT system, it may be simpler to simply put side by side the results of /data get and the outcome. like so:

{id: "minecraft:axolotl_bucket", count: 1, components: {"minecraft:bucket_entity_data": {Variant: 0, Age: 0, Health: 11.0f}}}
components: {"minecraft:bucket_entity_data": {Variant: 0}}
components.bucket_entity_data.Variant=0

with this, I can 100% understand all future CIT edits I can perform for all other objects, I just need to do /data get, and I'm good to go! 😁

Thanks again for the help!
