### ISSUE TITLE
[Idea] Use the Minecraft DataFixerUpper to update nbt to components

### ISSUE THREAD

**Issue by Thanos1716** [SHsuperCM/CITResewn#459]
At the moment, both OptiFine and CITResewn are appear to hard code the component updating, specifically for `nbt.display.Name` -> `components.minecraft\:custom_name` and `nbt.display.Lore` -> `components.minecraft\:lore`.

I'm not sure how feasible this is, but since Minecraft has to have the ability to update NBT to components included in the DataFixerUpper to update older worlds, perhaps it's possible to hook into that, and request any .properties files that have NBT properties but no component properties to update those NBT paths?

This would allow backwards compatibility for all resource packs below 1.20.5.

**Comment by SHsuperCM** [comment]
As cool as that would be, DFU only works on actual data(the properties dont have item data, only checks for item data) and so it is not really repurposable like that.
