### ISSUE TITLE
type=enchantment broken 

### ISSUE THREAD

**Issue by Cre4to5** [SHsuperCM/CITResewn#460]
**Describe the Issue** (clear and concise description of what the bug is, provide logs)

**To Reproduce** (if applicable, explain how someone would go about reproducing this issue, attach a resourcepack if applicable)

**Checklist** (go through and check these when relevant)
- [ ] I have attached the `latest.log` file relevant to this issue
- [ ] I have checked the issues and have not found an existing case of this issue
- [ ] I am using the latest version of CIT Resewn for my version of minecraft
- [ ] I am using the mod on Fabric Loader
- [ ] I have disabled broken paths in the mod's config and the issue persists

**Comment by SHsuperCM** [comment]
Guessing you opened this one by accident seeing #461
