### ISSUE TITLE
Enchantment Glint broken (v1.2.0+1.21)

### ISSUE THREAD

**Issue by Cre4to5** [SHsuperCM/CITResewn#461]
when using resource pack using cit type=enchantment it works as if texture was blank
![screenshoot](https://github.com/user-attachments/assets/3d865886-66de-4d82-b05f-7a1ff4ba974b)

To Reproduce Download v1.2.0 release and use any texture pack that has cit changing enchantment glint for example pack attached here
[RedGlintForCurses.zip](https://github.com/user-attachments/files/17003770/RedGlintForCurses.zip)
[latest.log](https://github.com/user-attachments/files/17003776/latest.log)

**Checklist** (go through and check these when relevant)
- [x] I have attached the `latest.log` file relevant to this issue
- [x] I have checked the issues and have not found an existing case of this issue
- [x] I am using the latest version of CIT Resewn for my version of minecraft
- [x] I am using the mod on Fabric Loader
- [x] I have disabled broken paths in the mod's config and the issue persists

**Comment by SHsuperCM** [comment]
Like the changelogs say, enchantment glint cit is temporarily disabled for that beta.

Leaving this issue open so others know too.

**Comment by Cre4to5** [comment]
> Like the changelogs say, enchantment glint cit is temporarily disabled for that beta.
> 
> Leaving this issue open so others know too.

May I ask why is that the case?

**Comment by SHsuperCM** [comment]
Simply put, the update broke it. The glints feature is one of high complexity/low demand, so to make the people demanding item type cits simmer down I could release a beta with missing features. (kind of the reason for it to be a beta and not a release)

It will be brought back before v1.2.x is in release stage, dont worry.

**Comment by SHsuperCM** [comment]
Fixed with #476 for v1.2.2
