### ISSUE TITLE
Model texture not loading

### ISSUE THREAD

**Issue by MaraSgit** [SHsuperCM/CITResewn#462]
## **Describe the Issue** (clear and concise description of what the bug is, provide logs)
I was trying to port my old Totem Model to 1.21 and the texture is not loading. I tried to run it in optifine and everything is fine.

### CITResewn
![2024-09-16_08 53 22](https://github.com/user-attachments/assets/d930d521-6efd-408f-9c34-bf69ab61d74b)

### Optifine
![2024-09-16_09 06 35](https://github.com/user-attachments/assets/2d0c8a76-60aa-4fa5-8e97-700db1e8b0e9)

## **To Reproduce** (if applicable, explain how someone would go about reproducing this issue, attach a resourcepack if applicable)
Load the resourcepack in CITResewn

```[08:55:44] [Worker-Main-34/INFO]: [citresewn] Loading item CIT models...
[08:55:44] [Worker-Main-34/INFO]: [citresewn] Linking baked models to item CITs...
[08:55:44] [Worker-Main-34/WARN]: Missing textures in model citresewn_model_path:minecraft/optifine/cit/fox_of_undying/fox_of_undying#inventory:
    minecraft:textures/atlas/blocks.png:minecraft:textures/entity/fox/fox_sleep.png
[08:55:44] [Worker-Main-34/WARN]: Missing textures in model citresewn_model_path:minecraft/optifine/cit/polar_fox_of_undying/polar_fox_of_undying#inventory:
    minecraft:textures/atlas/blocks.png:minecraft:textures/entity/fox/snow_fox_sleep.png
```

## **Checklist** (go through and check these when relevant)
- [x] I have attached the `latest.log` file relevant to this issue
- [x] I have checked the issues and have not found an existing case of this issue
- [x] I am using the latest version of CIT Resewn for my version of minecraft
- [x] I am using the mod on Fabric Loader
- [x] I have disabled broken paths in the mod's config and the issue persists

**Comment by SHsuperCM** [comment]
If I recall correctly 1.20.4 was the version that made resourcepacks require atlases.

Basically whenever you need to use a texture that is not in the items or blocks folders, you need to add it to the blocks atlas.
This is true for textures in entity as well, vanilla minecraft also does this to add entity textures like bells and conduits.

Look at the vanilla resourcepack if you need an example and I think the minecraft wiki explains atlases.
