### ISSUE TITLE
Failing to load in CIT model.

### ISSUE THREAD

**Issue by TrueMelone** [SHsuperCM/CITResewn#463]
The mod failes to load in this model with error "Errored while parsing CIT: Could not resolve a replacement model/texture"
Log including all related files come with it
[latest.log](https://github.com/user-attachments/files/17014635/latest.log)
[Broken Model.zip](https://github.com/user-attachments/files/17014696/Broken.Model.zip)

**Comment by SHsuperCM** [comment]
I am unable to reproduce the issue, the resourcepack works fine for me.

Please make a new issue following the issue template and with a minimal mod set that produces it.
