### ISSUE TITLE
components.enchantments not evaluated correctly 

### ISSUE THREAD

**Issue by EzranTheDragon** [SHsuperCM/CITResewn#465]
**Describe the Issue** 
`components.enchantments.`  is not working as intended and never results in a texture change.

**To Reproduce** 
- On MC 1.21 or 1.21.1 
- Install CIT Resewn, Fabric API and optionally Cloth Config+Mod Menu
- Add and activate the recourcepack [Visual_Enchantments_v1.zip](https://github.com/user-attachments/files/17033932/Visual_Enchantments_v1.zip)
- Enchant a Netherite Pickaxe with Silktouch
- Expectation: The pickaxe is changing the texture, tho it isn't

To see that the Recourcepack itself works comment the `components.enchantments ` out and enable `components.custom_name` this results in the expected behavior when renaming the Pickaxe.
When enabling both components the texture wont change either so they are both accepted as conditions but the enchantment is not fulfilled properly.

`enchantments=` and `enchantmentIDs=` work properly.

**Hardware/System Information** 
Since it appears to work for @SHsuperCM here more Infos about my system that might help:
- Windows 10 Pro
- 32 GB RAM
- RTX 2070 SUPER (Drivers up to Date)
- Java 21.0.2 Adoptium-Temurin 
- no JVM arguments
- prism Launcher

**Checklist** (go through and check these when relevant)
- [x] I have attached the [latest.log](https://github.com/user-attachments/files/17033957/latest.log) file
- [x] I have checked the issues and have not found an existing case of this issue
- [x] I am using the latest version of CIT Resewn for my version of minecraft
- [x] I am using the mod on Fabric Loader
- [x] I have disabled broken paths in the mod's config and the issue persists

**Comment by SHsuperCM** [comment]
Ah.. lmao

My bad, I was testing the issue in dev on latest commit and not on the v1.2.0 beta. 
It appeared fixed for me because this was already fixed for goat horns in #456.

Basically CITs were checking components with `NbtOps` instead of `RegistryOps` meaning it saw the silk touch as its encoding instead of as "`minecraft:silk_touch`".

**Comment by SHsuperCM** [comment]
Fixed in e009f189
