### ISSUE TITLE
nbt legacy not work

### ISSUE THREAD

**Issue by Diclo** [SHsuperCM/CITResewn#468]
MC Version: 1.21
CIT: 1.2.1+1.21
Fabric: 0.16.5
FAPI: 0.102.0+1.21

The textures that use `nbt.CustomModelData` as a condition aren't loading.
[latest.log](https://github.com/user-attachments/files/17082994/latest.log)

**To Reproduce** (if applicable, explain how someone would go about reproducing this issue, attach a resourcepack if applicable)
![imagen](https://github.com/user-attachments/assets/bac58704-e077-43bc-b058-38962918e7ae)
![imagen](https://github.com/user-attachments/assets/9c6deb47-ecfe-4e9d-9086-f275e7ed7c50)
[CatCraft_v8.4.1.zip](https://github.com/user-attachments/files/17083017/CatCraft_v8.4.1.zip)

**Checklist** (go through and check these when relevant)
- [x] I have attached the `latest.log` file relevant to this issue
- [x] I have checked the issues and have not found an existing case of this issue
- [x] I am using the latest version of CIT Resewn for my version of minecraft
- [x] I am using the mod on Fabric Loader
- [ ] I have disabled broken paths in the mod's config and the issue persists

**Comment by SHsuperCM** [comment]
`nbt.CustomModelData` is not a thing in 1.21.

See #447.
