### ISSUE TITLE
Issue with larger CIT packs + weird behaviour

### ISSUE THREAD

**Issue by MayaqqDev** [SHsuperCM/CITResewn#469]
**Describe the Issue** (clear and concise description of what the bug is, provide logs)
Big packs like Hypixel+ cause immense lag in the inventory screen, this from my understanding, and this patch https://github.com/wchristian/CITResewnJSONLagPatch is caused by some unoptimal json parasing (which has been redone from my understand is it might be fixed already) and mainly the cache getting refreshed every tick.

Even when setting the cache tick delay to a higher number, we just move it to a different tick and do not solve this issue.

My question is, why is the cache even dumped on ticks? Shouldn't it be only dumped on texture reload? This issue seems to be a thing for a long time now and it makes the game basically unplayable with packs like Hypixel+.

**To Reproduce** (if applicable, explain how someone would go about reproducing this issue, attach a resourcepack if applicable)

1. Install newest version of CITResewn
2. Join hypixel and its gamemode skyblock
3. Enable a texture pack like hypixel+
4. open inventory
5. suffer

Latest log: https://mclo.gs/EQ5waKW

**Checklist** (go through and check these when relevant)
- [*] I have attached the `latest.log` file relevant to this issue
- [*] I have checked the issues and have not found an existing case of this issue
- [*] I am using the latest version of CIT Resewn for my version of minecraft
- [*] I am using the mod on Fabric Loader
- [*] I have disabled broken paths in the mod's config and the issue persists

**Comment by SHsuperCM** [comment]
> Even when setting the cache tick delay to a higher number, we just move it to a different tick and do not solve this issue.

Absolutely not true, you are not "moving" it to a different tick, you are increasing the interval between cache dumps. 
If you wanted to not dump the cache at all you can just set it to a high number(even higher if you edit the config from the file) and it would have the same effect.

There is not much I can do, if you want to PR something go ahead and do so.
