### ISSUE TITLE
Resource Pack Pathing is Broken

### ISSUE THREAD

**Issue by VendusYT** [SHsuperCM/CITResewn#472]
Hi, I am sorry if this seems a bit pointless to mention but, I have been working on a resource pack in 1.20.1 for a while. And with the most recent update to 1.21.1 I found that my pack I had created for my friends seemed to break in a few places when it came to coding. Either that or something else seemed to be the problem. We use the pack as a server resource pack and the trouble I seem to find us in at the moment is that where I will have a few models / textures load on my end for the numerous files I added in here, on my friends end none of it will load or we will see the armor stands mixed up or some other various problem.

I have attached my log file from loading the pack, the pack itself and a picture of the issue.
[latest.log](https://github.com/user-attachments/files/17137855/latest.log)[
Our Resource Pack](https://1drv.ms/u/s!AvUBmCI0px-rrpRUH2709xkF9EkiLA?e=IS16jo)
[This is our Modpack with the previous beta but, I have tested it with the latest release and gotten the same result](https://1drv.ms/u/s!AvUBmCI0px-rqtEcPzV40VsPcx5kYw?e=kRxQh7)
![Image of Issue](https://github.com/user-attachments/assets/2118ff64-7b8f-45f5-861f-3b546a0f78a6)

**To Reproduce** (if applicable, explain how someone would go about reproducing this issue, attach a resourcepack if applicable)
I'd just say load our modpack replace the citresewn to see what the latest build would do in the mods folder and then load the resource pack.

Many of the items are renamed so Booba for Carved Pumpkin seems to be a good start.
[This is our Name List](https://1drv.ms/x/s!AvUBmCI0px-rn99VficAVNn05JCfQA?e=Cey7pv)

**Checklist** (go through and check these when relevant)
- [ x] I have attached the `latest.log` file relevant to this issue
- [ x] I have checked the issues and have not found an existing case of this issue
- [ x] I am using the latest version of CIT Resewn for my version of minecraft
- [ x] I am using the mod on Fabric Loader
- [ x] I have disabled broken paths in the mod's config and the issue persists

**Comment by Poopooracoocoo** [comment]
It appears you haven't migrated to Item Components

**Comment by VendusYT** [comment]
> Item Components

is there an easy conversion tutorial? or anything that could tell me how to do it?

**Comment by Poopooracoocoo** [comment]
https://optifine.readthedocs.io/cit.html#hand and #447 should help

**Comment by SHsuperCM** [comment]
Using old nbt instead of components, there are a lot of issues with the pack as well. A lot of broken paths in there with all the capital letters and I cannot help until those are gone.

**Comment by VendusYT** [comment]
> Using old nbt instead of components, there are a lot of issues with the pack as well. A lot of broken paths in there with all the capital letters and I cannot help until those are gone.

I have been working on and off on the pack since our previous posts. I got some things working but others are still busted. It looks mostly like its the Item textures / named textures and armors and the armorstands now. I have been trying a few different things and tools but, still coming up a bit short.

Heres the current[ build](https://1drv.ms/u/s!AvUBmCI0px-rsORzZMCtLhAR2Z17Bw?e=JakPz9) Im messing with this weekend.
