### ISSUE TITLE
Elytra texture

### ISSUE THREAD

**Issue by JoeLeBob** [SHsuperCM/CITResewn#474]
### The question

I am making a texture pack & using existing texture packs that change the elytra's model in the cit folder.

The elytra's item does change while the actual elytra model doesn't change at all.

I have tested the exact same texture packs in optifine and they work.

It seems to be an issue with CIT resewn on fabric, is there a way to fix this ?

### Checklist

- [X] I checked the issues(both open and closed) and could not find a duplicate of my question

**Comment by SHsuperCM** [comment]
This is an issue, not a question
