### ISSUE TITLE
Neoforge 1.21.1 support?

### ISSUE THREAD

**Issue by VaporeonScripts** [SHsuperCM/CITResewn#477]
### The feature

will this mod ever get a neoforge port? as it would be good as fabric is dying

### Checklist

- [X] I checked the issues(both open and closed) and could not find a duplicate of my feature

**Comment by SHsuperCM** [comment]
> as fabric is dying

LMFAO

**Comment by VaporeonScripts** [comment]
bruh

**Comment by Dev0Louis** [comment]
Can you give any evidence for fabric dying? The assassination of fabric should have stayed secret and only be known to the most inner circle of the conspiracy! So how do you know of our plans?

**Comment by VaporeonScripts** [comment]
Wth💀anyways u can see that all tech mods stopped with fabric and went to neoforge 1.21.1 and forward,and most mods are going only neoforge
