### ISSUE TITLE
Add to 1.20.6

### ISSUE THREAD

**Issue by krissgame** [SHsuperCM/CITResewn#478]
### The question

Can You add CIT Resewn to version 1.20.6 please? thanks

### Checklist

- [X] I checked the issues(both open and closed) and could not find a duplicate of my question

**Comment by SHsuperCM** [comment]
> For the record, 1.20.5/6 will not be getting a version.

https://github.com/SHsuperCM/CITResewn/pull/447#issuecomment-2330652371
