### ISSUE TITLE
Intense lag and render usage with Wynncraft models

### ISSUE THREAD

**Issue by TYTheBeast** [SHsuperCM/CITResewn#480]
### The issue

I expected CIT Resewn to be a bit more optimized, but spark shows otherwise. It's taking away about half of my FPS, for models that should be no problem for my GPU, simply because of some regex patterns.

### How to reproduce

1. Join Wynncraft
2. Hold an item with a custom model such as a mythic weapon, or have many players with their weapons out on screen
3. FPS suddenly drops

### Logs

https://spark.lucko.me/J8UTbuf8rT

### Checklist

- [X] I checked the issues(both open and closed) and could not find a duplicate of my issue
- [X] I am using the latest version of CIT Resewn for my Minecraft version
- [X] I have disabled Broken Paths and the issue persists
- [X] I am running the mod using Fabric Loader

**Comment by SHsuperCM** [comment]
Logs not valid, issue not reproducible with the steps provided, packs not provided.

The mod doesnt do any regex unless a resourcepack asks it to do regex.
