### ISSUE TITLE
Multiple enchantments tool only shows the resource of one enchantments

### ISSUE THREAD

**Issue by huct8** [SHsuperCM/CITResewn#483]
### The issue

I an using a cit enchantments resourcepack(Ultimacraft-enchantments)。When I  try to enchhant my sword, I find it shows a wrong resource. It only shows one type of enchantments. 
<img width="379" alt="屏幕截图 2024-10-05 192832" src="https://github.com/user-attachments/assets/01194dba-5b83-4808-a82e-1a90f4b853fe">

(only shows Fire Aspect and never shows other enchantments)  

But when I play 1.20.4, it works very well.
<img width="383" alt="屏幕截图 2024-10-05 193528" src="https://github.com/user-attachments/assets/f29b1d6c-48d1-4f81-84e5-c493013de2ab">

(it shows Fire Aspect; Sharpness; Mendiong; Unbreaking; Looting)

### How to reproduce

The wrong is in 1.21.1. And the 1.20.x is all right.
Here is the resourcepack(it over 25mb, this  is the link) .
https://www.curseforge.com/minecraft/texture-packs/ultimacraft-enchantments/files/5598037

### Logs

https://mclo.gs/7XEcFpR

### Checklist

- [X] I checked the issues(both open and closed) and could not find a duplicate of my issue
- [X] I am using the latest version of CIT Resewn for my Minecraft version
- [X] I have disabled Broken Paths and the issue persists
- [X] I am running the mod using Fabric Loader

**Comment by SHsuperCM** [comment]
The resourcepack was not correctly updated as it is using nbt to check for multiple enchantments(which is not a thing in 1.21).
The pack author needs to fix it, see #447 for reference.
