### ISSUE TITLE
How to merge `nbt.display.Lore.*` in new Components?

### ISSUE THREAD

**Issue by AdamCalculator** [SHsuperCM/CITResewn#485]
### The question

components.lore.*=... ?

### Checklist

- [X] I checked the issues(both open and closed) and could not find a duplicate of my question

**Comment by HiWord9** [comment]
> components.lore.*=... ?

Yes, just like that, exactly as u think it might be. You should've checked before leaving an issue here, and you could not wait for response for a whole month. This may be closed now

**Comment by AdamCalculator** [comment]
Yes, in [optifine docs](https://optifine.readthedocs.io/syntax.html#general-behavior) i found it example:

![image](https://github.com/user-attachments/assets/3fc2ed3f-64e2-4bd5-b8ca-def83a47d0f9)
