### ISSUE TITLE
Can I specify biome *tags*?

### ISSUE THREAD

**Issue by ImpulsiveLad** [SHsuperCM/CITResewn#489]
### The question

Biomes seems to take in biomes but can I specific tags instead? I would like cit to work with modded biomes without hand doing it all
`biomes.x=#ocean #forest #desert`

### Checklist

- [X] I checked the issues(both open and closed) and could not find a duplicate of my question

**Comment by SHsuperCM** [comment]
Are you sure you are looking at the right mod? CIT is for Custom Item Textures.. 
:/

**Comment by ImpulsiveLad** [comment]
Yes, CIT allows for custom textures based on the biome
I.E.  a multitude of mods by creepermax123 and ALthegatorMC
![Screenshot 2024-10-17 111616](https://github.com/user-attachments/assets/9db9c4f9-97ae-4795-b3a8-12808eb052ca)
![Screenshot 2024-10-17 141002](https://github.com/user-attachments/assets/206073c7-5096-48ad-a6fa-16f0973ef368)

**Comment by ImpulsiveLad** [comment]
Oh shit wait thats emf and etf mb
