### ISSUE TITLE
Can I number entries in the json?

### ISSUE THREAD

**Issue by ImpulsiveLad** [SHsuperCM/CITResewn#490]
### The question

![Screenshot 2024-10-18 015111](https://github.com/user-attachments/assets/b67bc802-1a0c-4b76-875b-8c7c8c080578)
I am not sure how to make them seperate, do I HAVE to make them all be in separate files? its a pain in the ass as I got 165 I need to number, stopped at 25 and it doesn't seem to be working at all.

### Checklist

- [X] I checked the issues(both open and closed) and could not find a duplicate of my question

**Comment by SHsuperCM** [comment]
I'm not quite sure what you are asking for here? where are these numbers coming from?

**Comment by ImpulsiveLad** [comment]
so I code c# but I think these jsons are code so type is just undefined no? so I have to give it a unique entry so that type!=type

so type.1, type.2 etc and the attached properties are numbered as well?

I am quite disappointed I cannot get it to work.

etf/emf looks very similar and allows it
![Screenshot 2024-10-18 032338](https://github.com/user-attachments/assets/99be135a-96df-4a91-9b51-f0b17e28c5ff)

I would think this would too as its just a lang isn't it?

**Comment by SHsuperCM** [comment]
The old CIT spec does not allow for multiple CITs to be defined in the same properties file. 

At some point there will be a modernized spec that will allow it as it's designed with that in mind, but that is a bit away until I start working on that.
