### ISSUE TITLE
Select textures don't work but others do!

### ISSUE THREAD

**Issue by Tophxt** [SHsuperCM/CITResewn#498]
### The question

I have a texture pack for 1.21 that im making which has a bunch of 3d weapon models that i have made and added as a big pack. In 1.20.1 the textures were working (all of them), now after downloading 1.21 version and the same pack, they dont work. A couple of them work as i will show in images, but the others ones dont and i cant figure out why. Please help! (My discord user is tophat_64 Ping me there if you can)

![image](https://github.com/user-attachments/assets/5600de10-dfeb-4402-8dd7-69af3ea61757)
![image](https://github.com/user-attachments/assets/200744c0-fd3f-4638-b8e1-7350f067f272)
![image](https://github.com/user-attachments/assets/97d67742-f8a8-44b6-a5e0-8b14c53c76e7)
![image](https://github.com/user-attachments/assets/e749296d-f1e5-4233-9d59-c619d425aeb4)

The name of the ones that work are - 
Swords - 
1) 1MoreKill
2) NightFall
3) VoidHeart
4) Puma Blade
Axes - 
1) Abyssal Fury
2) Equilibrium
Ones i would like to work are "LongHat", "ShortHat", "Striker"
(All of them were made in blockbench)

Here is the pack for 1.21 fabric

[!#TopHat's Weapons#!.zip](https://github.com/user-attachments/files/17532012/TopHat.s.Weapons.zip)

### Checklist

- [X] I checked the issues(both open and closed) and could not find a duplicate of my question

**Comment by SHsuperCM** [comment]
Use the issue form for issues
