### ISSUE TITLE
Tridents and Spyglasses are not applying CIT Item correctly

### ISSUE THREAD

**Issue by CrusherD2** [SHsuperCM/CITResewn#50]
Hi, I tried a texturepack called "3.0.3 Visual Enchantments" https://www.curseforge.com/minecraft/texture-packs/visual-enchantments and most of the things worked fine but the trident texture didnt work, could I get some help to solve this or a reason for it not working maybe, the mod is amazing by the way, im happy that most of the things on the pack work thanks to this :D

**Comment by KivBeta** [comment]
i tried this texturepack, and the items don't change the texture in inventory, only changed when holding on hand

**Comment by CrusherD2** [comment]
What could I do in this case?
