### ISSUE TITLE
Sounds for objects!

### ISSUE THREAD

**Issue by Mijtidid** [SHsuperCM/CITResewn#504]
### The feature

I would like to suggest something special for cit. This is adding custom sounds for items of different types. For example, if I have 5 custom totems in a resource pack and I wanted to make unique sounds for these totems that are not similar to each other. I hope this feature will be considered by you! 

### Checklist

- [x] I checked the issues(both open and closed) and could not find a duplicate of my feature

**Comment by Mijtidid** [comment]
So will you make this feature?

**Comment by Mijtidid** [comment]
what does 1 task completed mean?

**Comment by SHsuperCM** [comment]
Means you put a check mark in your issue. 
This has already been suggested before and was on the planned features even before that. I just havent gotten around to adding it.
Closing as it is in planned features already.
