### ISSUE TITLE
Noteblock blockstates problem

### ISSUE THREAD

**Issue by Strawberrycreww** [SHsuperCM/CITResewn#509]
### The question

Hi, using CITResewn since a few days, i have a problem with my texture pack. With optifine all was good but now, note_blocks blockstates doesen't work. I've used blockstates and opitfine modifications in my folders. But i can't underdstand the problem

### Checklist

- [X] I checked the issues(both open and closed) and could not find a duplicate of my question

**Comment by SHsuperCM** [comment]
Issue, not a question.
