### ISSUE TITLE
Trying to add my own custom resource pack and fix some issues on my end?

### ISSUE THREAD

**Issue by sunflowermelli** [SHsuperCM/CITResewn#513]
### The question

Hello, I'm brand new to pack creation of any kind! 

My research into MCPatcher led me to this mod, which I've been using anyways, so I'm trying to make a resource pack containing all the CIT items I use. Some of the items in the mod don't show up in game anyways; namely weapons and entity models(?), so I'm aiming to try and patch that on my end as well so it all shows up.

This is for a private server with friends, entirely cosmetic items just for decoration's sake. (I'm hoping this resource pack can server as a personal 'dollhouse' kinda thing, if that makes any sense?) Any help would be greatly appreciated!

### Checklist

- [X] I checked the issues(both open and closed) and could not find a duplicate of my question

**Comment by SHsuperCM** [comment]
Open an issue(specifically not a question) with it and I'll see it when I have the time, really need you to be specific in what doesnt work as well as providing logs.
