### ISSUE TITLE
Does not work with Ghoulcraft's CIT

### ISSUE THREAD

**Issue by ChapperNi** [SHsuperCM/CITResewn#6]
Just simply doesnt let Ghoulcraft's CIT appear.

**Comment by SHsuperCM** [comment]
After much consideration and a suggestion that was given in #9, I've decided to allow broken paths and block it behind both a config option that defaults to not allow broken paths as well as mark the packs incompatible in the resourcepack selection screen.

This has been implemented in [v0.5.0](https://modrinth.com/mod/cit-resewn/version/6JfMqtLA).

Still this is very experimental and no bugs that derive from the config option being enabled will be resolved.
