### ISSUE TITLE
Chinese Unicode Support

### ISSUE THREAD

**Issue by xMikux** [SHsuperCM/CITResewn#63]
can't load have chinese unicode character on cit properties

https://pastebin.com/vaUNmjHF

**Comment by SHsuperCM** [comment]
Not related to Chinese characters, it's complaining about the space in `sky piercer`.
```
minecraft:optifine/cit/infinityexpansion/sky piercer/sky_piercer.properties
```

Replace the space with an underscore.

https://citresewn.readthedocs.io/usage/help/#non-a-z0-9_-character-in-path-of-location
