### ISSUE TITLE
Wiki about broken paths

### ISSUE THREAD

**Issue by Madis0** [SHsuperCM/CITResewn#67]
A specific wiki page about what the broken paths are, how to detect and fix them would be nice.
I understand the concept but it would be nice to just link the users/resource pack devs to something that explains it throughly.

**Comment by SHsuperCM** [comment]
Yeah, something pointing people to what they need to do would be helpful. 

I dont think a full page would be necessary as this is vanilla standards but I'll definitely update the broken paths section in the config and in the faq pages.
