### ISSUE TITLE
After manually fixing paths, certain CITs still do not display correctly

### ISSUE THREAD

**Issue by Blisschen** [SHsuperCM/CITResewn#69]
Using 1.17.1, you can load in packs by toggling on broken paths and it works more or less correctly. However, certain CITs still do not display, and I'm unable to exactly figure out why. I've manually ruled out using spaces, correct capitalization, double-checked it follows the pack format as listed in ReadTheDocs, checked it's not a .json file vs .png file issue, and still I am unable to manually fix certain CITs.

![itwascalculatedbutboyamidumb](https://user-images.githubusercontent.com/13970843/141850801-f1e2930a-beba-4e72-a72e-847ea2385581.png)

Top two CITs are from Mizuno's 16craft 1.17.1 CIT Beta, bottom two CITs are from Ghoulcraft Mega 10-2020 edition. Oak Fence_a02 is one I've manually attempted to fix the path on, and Oak Fence_a03 is the control CIT. Both still show sideways, and I don't believe it's a NBT name issue at this point anymore. The Mizuno's CIT fences show correct rotation, Ghoulcraft's does not, despite both using identical .json files created vanilla model formatting style with Blockbench. Both .jsons use correct formatting.

![2021-11-15_15 56 07](https://user-images.githubusercontent.com/13970843/141852650-8ab1fda6-fd46-4428-ae0f-f725614e53dd.png)

Is there a fix for this display issue on the pack side, or is this a mod issue? Thank you in advance! 😊

(also quick side note, thanks so much for this mod! It's been one of the best and easies parts of moving to Sodium so far!)

**Comment by SHsuperCM** [comment]
I'll need your logs and the exact resourcepack you are using.

**Comment by Blisschen** [comment]
Sure!

Link with clickable links: https://blisschen.co/faq

Mizuno’s 16craft & CIT & Invisible Item Frame Pack (1.17.1)
∙ mizunomcmemo.blogspot.com/p/resourcepack.html

Ghoulcraft CIT (Mega)
∙ ghoulcraft.com

FreshLX’s Fresh Leaves
∙ planetminecraft.com/texture-pack/fresh-leaves-mizunos-add-on/

FreshLX’s Fresh CIT
∙ planetminecraft.com/texture-pack/fresh-cit-v1-0/

Nox’s Better Carpets & Ropes
∙ planetminecraft.com/member/noxcturnal

Vinny’s Timber Frame CIT 
∙ planetminecraft.com/texture-pack/vinny-s-timber-frames-cit/

Elytra Reality Fairy Wings
∙ planetminecraft.com/texture-pack/elytra-reality-0001/

Hananacraft CIT
∙ planetminecraft.com/texture-pack/hananacraft-v1-0/

Bay Window CITs & More
∙ planetminecraft.com/texture-pack/bay-window-cits/

Mushroom Golems CIT
∙ planetminecraft.com/texture-pack/mushroom-golems/

Pinkgummibaerchen’s Granny’s Corner & Garden Breeze CITs
∙ planetminecraft.com/member/pinkgummi

Blisschen’s ASMR Anvils
∙ planetminecraft.com/texture-pack/blisschen-s-asmr-anvils-remove-those-anvil-sounds

Jicklus 1.16 Orange Autumn Overlay Pack (with private edits)
∙ planetminecraft.com/texture-pack/jicklus-1-14-orange-autumn-addon

And log:
[2021-11-15-4.log](https://github.com/SHsuperCM/CITResewn/files/7548575/2021-11-15-4.log) It's obviously skipping CITs, that doesn't bother me because that's fixable, but I can't find why it's just flat out not displaying these specific table leg CITs correctly sized and positioned.

```[15:44:19] [Worker-Main-5/ERROR]: {citresewn} Skipped CIT: Cannot resolve path for model/texture in [MEGA] Ghoulcraft 10-22-20 -> minecraft:optifine/cit/canopy_dark_cyan.properties

[15:44:20] [Worker-Main-5/ERROR]: {citresewn} Skipped CIT: Unknown item minecraft:block in [MEGA] Ghoulcraft 10-22-20 -> minecraft:optifine/cit/example.properties

[15:44:22] [Worker-Main-5/ERROR]: {citresewn} Skipped CIT: Cannot resolve path for model/texture in [MEGA] Ghoulcraft 10-22-20 -> minecraft:optifine/cit/shelf4_birch.properties

[15:44:22] [Worker-Main-5/ERROR]: {citresewn} Skipped CIT: Cannot resolve path for model/texture in [MEGA] Ghoulcraft 10-22-20 -> minecraft:optifine/cit/shelf4_dark.properties

[15:44:22] [Worker-Main-5/ERROR]: {citresewn} Skipped CIT: Cannot resolve path for model/texture in [MEGA] Ghoulcraft 10-22-20 -> minecraft:optifine/cit/shelf4_oak.properties

[15:44:22] [Worker-Main-5/ERROR]: {citresewn} Skipped CIT: Cannot resolve path for model/texture in [MEGA] Ghoulcraft 10-22-20 -> minecraft:optifine/cit/shelf4_spruce.properties

[15:44:23] [Worker-Main-5/ERROR]: {citresewn} Skipped CIT: Unknown item minecraft:lgray_carpet in [MEGA] Ghoulcraft 10-22-20 -> minecraft:optifine/cit/tablecloth_lgray.properties

[15:44:23] [Worker-Main-5/ERROR]: {citresewn} Skipped CIT: Cannot resolve path for model/texture in [MEGA] Ghoulcraft 10-22-20 -> minecraft:optifine/cit/windowseat_birch_lgray.properties

[15:44:23] [Worker-Main-5/ERROR]: {citresewn} Skipped CIT: Cannot resolve path for model/texture in [MEGA] Ghoulcraft 10-22-20 -> minecraft:optifine/cit/windowseat_dark_lgray.properties

[15:44:23] [Worker-Main-5/ERROR]: {citresewn} Skipped CIT: Cannot resolve path for model/texture in [MEGA] Ghoulcraft 10-22-20 -> minecraft:optifine/cit/windowseat_oak_lgray.properties

[15:44:23] [Worker-Main-5/ERROR]: {citresewn} Skipped CIT: Cannot resolve path for model/texture in [MEGA] Ghoulcraft 10-22-20 -> minecraft:optifine/cit/windowseat_spruce_lgray.properties

[15:44:23] [Worker-Main-5/INFO]: [citresewn] Found 2764 CITs in [MEGA] Ghoulcraft 10-22-20```

**Comment by SHsuperCM** [comment]
Well everything looks fine in the logs(apart from the ones that are skipped for the various reasons ofc)..

Just downloaded ghoulcraft(10-22-20) quickly to check the files. I'm assuming you're supposed to just place the items in item frames with these types of packs. 
Looking in `oak_fence_a02.json` there aren't any display settings for item frames. So dropping the file in blockbench you clearly see that it looks like like it appears to you ingame when the itemframe is on the floor:
![](https://i.vgy.me/6G0wTk.png)

What I did notice is a parent model referenced called `cit_item` which simply does not exist in that pack. It may and may not have the display settings for for the models but it's not there for me to know.

**Comment by SHsuperCM** [comment]
Unless I'm missing something, I have to mark this one as user error because it seems like the model jsons simply don't have the transformations for item frames which is easily done.

If there is something else, please let me know.

**Comment by SHsuperCM** [comment]
Btw, just roughly estimating, I added the following to the fence json and it should look like this:
```json
...
	"display": {
		"fixed": {
			"rotation": [-90, 0, 0],
			"translation": [0, 0, -15],
			"scale": [2, 2, 2]
		}
	}
...
```
![](https://i.vgy.me/7MbtZ5.png)

**Comment by Blisschen** [comment]
The difference is that on the exact same installation, but using Optifine instead of CIT Resewn, these display perfectly fine.

![ApplicationFrameHost_2021-11-16_13-30-20](https://user-images.githubusercontent.com/13970843/142044497-7f9a49c3-fbac-493f-8a1b-3ed8807b5454.png)

So I'm wondering if there's some sort of correction in Optifine so that resource pack creators just didn't need to properly do rotation. But I just checked, and Mizuno's 16craft CIT oak_fence_0.json does not include a display NBT tag, but displays correctly. Ghoulcraft's oak_fence_2.json also does not include the display NBT tag, but does not display correctly.

![image](https://user-images.githubusercontent.com/13970843/142044956-9924b897-acae-4def-855d-393aca75625a.png)
![image](https://user-images.githubusercontent.com/13970843/142044988-92aea615-b63c-460e-8ec6-5b52e3337e2e.png)

So adding display will fix it, but the Mizuno's models work 100% correctly without it. Ghoulcraft's does not, and the only thing I can think of is perhaps how CIT Resewn is handling models is assuming less than Optifine did?

**Comment by SHsuperCM** [comment]
The problem with optifine(and one of the reasons I started CIT Resewn) is that it's closed source.. I wouldnt know if optifine added some extra behavior for these display settings so I cant implement them.

What I do here is basically immitate what cit should be doing using fabric/vanilla  code. How CIT Resewn handles models is by just directing vanilla model loading towards cit models. If optifine does something different it is not my concern in most cases..

**Comment by Blisschen** [comment]
I guess then I'm wondering then why Mizuno's oak_fence_0.json does not include a display NBT tag, but displays correctly while Ghoulcraft's oak_fence_2.json also does not include the display NBT tag, but does not display correctly. Keeping in mind I'm thrilled there's a standalone source to handling CITs (and including backwards compatibility not found in Chime), but one .json works perfectly and one ,json does not, despite them being the same models and including the same information.

I'm doing my best to make sure everything in all of my packs are manually fixed, but I don't get how with two nearly identical table legs with only a texture swap, one works and one does not. (Which I'm sure will make it confusing to explain to Ghouls, as well.)

**Comment by SHsuperCM** [comment]
As I said, the jsons are handled mostly by vanilla code, so the properties only control which json is used. 
Not in front of pc right now but I'd check if Mizuno's have any parent jsons with display or the model is just naturally positioned in a way where display settings arent needed.
This should just be a simple vanilla model issue.

**Comment by Blisschen** [comment]
Thank you, I appreciate you taking the time to have a look!
