### ISSUE TITLE
Conflict with "Customizable Player Models" mod. stuck in a loop on menu.

### ISSUE THREAD

**Issue by AshiraLOL** [SHsuperCM/CITResewn#72]
it always trying to reload resourcepacks.

Conflict with "Customizable Player Models" mod.
https://www.curseforge.com/minecraft/mc-mods/custom-player-mode

log file
[latest.log](https://github.com/SHsuperCM/CITResewn/files/7657838/latest.log)

https://user-images.githubusercontent.com/51751845/144784921-af579bf0-bc2b-4921-9e69-5beb5b6ea5fd.mp4

**Comment by SHsuperCM** [comment]
@SHsuperCM 
Strongly related to #73. Could possibly hotfix using mixin priority until #73 is fixed properly.

**Comment by SHsuperCM** [comment]
Fixed for v0.8.2
