### ISSUE TITLE
Not rendered in the inventory

### ISSUE THREAD

**Issue by Herobrine2143** [SHsuperCM/CITResewn#74]
The mod works as intended when display from your main hand or offhand or even dropped, but it does not render the texture in the inventory and just displays the default texture or from the original texture pack assets instead of the named texture

![2021-12-07_15 43 00](https://user-images.githubusercontent.com/22053132/145050798-3ab914ef-0118-4c32-9b1b-6c33faf96e66.png)
![2021-12-07_15 43 45](https://user-images.githubusercontent.com/22053132/145050824-2abce39a-8978-4d9f-a5ca-c779d0e40297.png)
![2021-12-07_15 43 59](https://user-images.githubusercontent.com/22053132/145050828-ebd8eb79-db8a-4888-99a1-79d53070ec60.png)
![2021-12-07_15 43 02](https://user-images.githubusercontent.com/22053132/145050829-dffce0a4-71da-4d14-baf9-c21ec04d66a8.png)
![2021-12-07_15 43 38](https://user-images.githubusercontent.com/22053132/145050833-f4c2d640-d920-4960-aaf0-fa4d452ba92f.png)

Minecraft Version 1.17.1 | CITResewn Version 0.5.4 | Texture pack - NewDefault+v1.44

**Comment by SHsuperCM** [comment]
Upload your logs. (`.minecraft/logs/latest.log`)

**Comment by SHsuperCM** [comment]
Marking as stale.

If I were to guess, you have Eating Animation installed which is known to cause this bug.
