### ISSUE TITLE
Your Regex is wrong

### ISSUE THREAD

**Issue by Speak2Erase** [SHsuperCM/CITResewn#75]
``[21:28:53] [Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: minecraft:optifine/cit/itembound/!wip/skulls/bob.properties``

The cit pack I'm using works fine using optifine, however cit resewn will refuse to load it, because your regex appears to not match what optifine uses.

I think it should be ``[a-zA-Z/._-\\!]``?

**Comment by SHsuperCM** [comment]
I'm not doing any regex, it's vanilla that stops you from using special characters in paths. This is standard pack formatting for both resourcepacks and datapacks and optifine is just not implemented properly.

Read the FAQ for a fix. 
https://citresewn.readthedocs.io/usage/help/

**Comment by Speak2Erase** [comment]
Alrighty
I thought it would have been your mod since it worked on optifine :/
