### ISSUE TITLE
Bow and Crossbow loading textures don't work

### ISSUE THREAD

**Issue by endoverlord423** [SHsuperCM/CITResewn#76]
using the New Default+ texture pack, the custom bow and crossbow textures work until I try to use them and then they revert back to regular until I stop using them
I believe the issue with this is that they have separate model .json files that are in a folder CITresewn doesn't look in so it doesn't know what to do
when using a bow or crossbow that doesn't have a .json model file they work completely fine
I am using broken paths to make it work with optifine format, without broken paths it doesn't do anything, and if I rename the optifine folder to citresewn the textures are smaller than what they should be

**Comment by SHsuperCM** [comment]
Duplicate of #65
