### ISSUE TITLE
pink trees don't work in Stay True

### ISSUE THREAD

**Issue by Syberiyxx** [SHsuperCM/CITResewn#77]
With optifine, birch trees appear pink with optifine in some biomes with this pack:
https://www.curseforge.com/minecraft/texture-packs/stay-true
![2021-12-10_13 02 05](https://user-images.githubusercontent.com/2048087/145634552-95fc7580-04e6-451b-b572-01b80df56c59.png)

With CITResewn they do not.
![2021-12-10_13 01 07](https://user-images.githubusercontent.com/2048087/145634644-5f75e9cd-614e-4546-9a22-75eae79a233e.png)

**Comment by SHsuperCM** [comment]
This has nothing to do with the mod, CIT Resewn is specifically for CIT, not for all of optifine.
The pack is not doing any CIT and the trees specifically are not CIT.
