### ISSUE TITLE
Custom Container GUI

### ISSUE THREAD

**Issue by PINPAL** [SHsuperCM/CITResewn#80]
As of early last year support was added for custom container GUI according to OptiFine's CIT docs:
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/custom_guis.properties

This feature does not seem to be available in CITReswen and custom GUI's are not rendered.
When loading up the game with OptiFine, these textures are rendered correctly.

Is this feature implemented and if so is there a different format used? I couldn't find anything in the documentation.

**Comment by SHsuperCM** [comment]
CIT Resewn only does CIT. As in, Custom Item Textures.
The [doc repository](https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc) you linked is not just for CIT, there's stuff there for all of optifine's features, and of that there is Custom GUIs, which again, has nothing to do with CIT.
