### ISSUE TITLE
rename and display

### ISSUE THREAD

**Issue by Anonim19992** [SHsuperCM/CITResewn#84]
CITResewn-0.8.1.jar
I noticed 1 moment that this mod does not show renamed items that use ~ (tilde)
Examples:
NeadApTar~
SilinGo~
etc

**Comment by Anonim19992** [comment]
In my case, these are totems

**Comment by SHsuperCM** [comment]
I'll need the pack and your logs

**Comment by Anonim19992** [comment]
https://www.curseforge.com/minecraft/texture-packs/subshield-totems/files - any of the [nb] files.

**Comment by Anonim19992** [comment]
> and your logs

and where can I find them? since I am still very weak in these matters

**Comment by SHsuperCM** [comment]
Close completely and launch the game.

If the pack is not enabled, enable it.

Go to the game's folder and upload `.minecraft/logs/latest.log`

**Comment by Anonim19992** [comment]
[23:01:17] [Worker-Main-10/ERROR]: Non [a-z0-9/._-] character in path of location: minecraft:optifine/cit/totems/6sixchazek6six[nb]/6sixchazek6six[nb]_totem.properties 
etc
[a-z0-9/._-]     =(

**Comment by SHsuperCM** [comment]
The `[` and `]` in the names of the folders/files are breaking pack format. 
More info available here:
https://citresewn.readthedocs.io/usage/help/
https://citresewn.readthedocs.io/usage/config/

**Comment by Anonim19992** [comment]
Question. If 1 resource pack contains both / optifine / and / citresewn / folders, will this resource pack conflict?

**Comment by SHsuperCM** [comment]
If it has the duplicate properties it might, but just having both `optifine` and `citresewn` should work fine.

**Comment by Anonim19992** [comment]
Thank you.
