### ISSUE TITLE
nbt.display.color not work

### ISSUE THREAD

**Issue by jhooc77** [SHsuperCM/CITResewn#85]
type=armor
items=leather_chestplate
texture.leather_layer_1=school_uniform_layer_1
texture.leather_layer_1_overlay=school_uniform_layer_1

nbt.display.color=#ffff0c

It's not work, but in case "nbt.display.Name " was work well.

minecraft version: 1.17
mod version: 0.8.1

**Comment by SHsuperCM** [comment]
* This is a hotfix(hex integers are checked only for `nbt.display.color`), this will be implemented properly in the condition rewrite.

**Comment by SHsuperCM** [comment]
Will be available with v0.8.2
