### ISSUE TITLE
Animated Armor Not Working

### ISSUE THREAD

**Issue by Cinder4198** [SHsuperCM/CITResewn#87]
Armor CIT with an animation file will still only show the unanimated texture of the file. This probably affects all CIT animations, but I don't use any outside of armor.

Optifine:
![2021-12-27_14 02 22](https://user-images.githubusercontent.com/67652147/147504703-3ad20caa-09e6-4a0c-af52-5a96f8192b68.png)

CITResewn:
![2021-12-27_14 18 34](https://user-images.githubusercontent.com/67652147/147504712-7a329361-63f9-463a-9764-969dfa3aa970.png)

**Comment by SHsuperCM** [comment]
This is not a CIT feature but an optifine one.

Theres plans in the far future to add support but not any time soon..
