### ISSUE TITLE
CIT doesn't render in gui, but does in player hand

### ISSUE THREAD

**Issue by DraconicKnight** [SHsuperCM/CITResewn#88]
Recently I've noticed that custom item textures only seem to render when these items are held, in the inventory the render as vanilla items. I've tried to see if I made an error in the .properties file but it looked fine, and the part that confused me the most is the fact that it rendered but only in the hand, even if I tried directing the .properties to a model file instead of right to a texture it still didn't work.

Here's a screenshot, if you look at the hotbar, there are 3 netherite swords, all of which should be rendering as different custom item textures, but none of them do.
![2021-12-29_19 00 45](https://user-images.githubusercontent.com/96853650/147718477-85e9105c-0504-426f-9e33-7f0284405dc4.png)

Here's the .properties for one of the items:
type=item
matchItems=netherite_sword
texture=dracalia.png
nbt.display.Name=ipattern:Dracalia

**Comment by SHsuperCM** [comment]
Upload logs

**Comment by SHsuperCM** [comment]
Before you do that, do you have Eating Animation installed?

**Comment by DraconicKnight** [comment]
Yes, I am using Eating Animations, I took it out after you asked and everything was fine. When the wiki said it broke item CITs, I though it meant the eating animations but I guess I was wrong. I probably should've tried using CIT Resewn without any other mods before thinking it was a bug, my bad.

**Comment by SHsuperCM** [comment]
No worries
