### ISSUE TITLE
Resource reload failed when zipped

### ISSUE THREAD

**Issue by Unconventional10** [SHsuperCM/CITResewn#89]
I get the "Resource Reload Failed" notif when I try and load my zipped resourcepack. Unzipping fixes this problem.
I have a single resourcepack that contains some custom sounds, several CITs, and a reskinned villager.
I have tries Zipping on MacOS and on Linux.

**Comment by SHsuperCM** [comment]
Cant help much without more information.
Please send logs and the pack.

**Comment by Unconventional10** [comment]
Log: [ATLauncher Log](https://paste.atlauncher.com/view/09283dfa-f05e-47f6-b9fa-a66f9ae3991c)
Zip:[Archive.zip](https://github.com/SHsuperCM/CITResewn/files/7796915/Archive.zip)

**Comment by SHsuperCM** [comment]
Not really sure how unzipping it would fix the issue but the logs clearly say what's wrong:
```
[31/12/2021 11:16:08 AM] Caused by: net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: minecraft:optifine/cit/items/machine gun.properties
```
The space in the file name is breaking the path.

It looks like `machine gun.properties` is the exact same file as `machinegun.properties`, deleting the space one should fix the pack.

**Comment by SHsuperCM** [comment]
More info available here:
https://citresewn.readthedocs.io/usage/help/
https://citresewn.readthedocs.io/usage/config/

**Comment by Unconventional10** [comment]
Thanks! I'll make sure to not do that. (I'm really bad at reading logs lol)
