### ISSUE TITLE
Consider preventing broken resourcepacks from loading

### ISSUE THREAD

**Issue by Madis0** [SHsuperCM/CITResewn#9]
Regarding #3, I understand and appreciate the approach you took in not implementing broken behaviour, however a crash is a bad UX either way. 

Have you considered adding a feature that makes broken resource packs behave like vanilla's "incompatible" - disabled on start and show an exclamation mark with a tooltip in resource pack list? 

That way users could easily know 
1) which resource packs are broken
2) what to tell the resource pack makers

without having to try and decipher the crash.

**Comment by SHsuperCM** [comment]
That... is actually not a bad idea... I was thinking to not let these packs load at all so people would understand that the old format is no longer supported, this will definitely help with that..

Maybe also block that behind a config option that defaults to not allow broken packs..

This is something I'll consider more seriously now.

**Comment by SHsuperCM** [comment]
Implemented in [v0.5.0](https://modrinth.com/mod/cit-resewn/version/6JfMqtLA). Thanks for the idea!
