### ISSUE TITLE
texture pack failed to load

### ISSUE THREAD

**Issue by ChrqnosTR** [SHsuperCM/CITResewn#90]
error message indicating unsuccessful loading of texture packs and double loading of the loading bar.
[latest.log](https://github.com/SHsuperCM/CITResewn/files/7799244/latest.log)

https://user-images.githubusercontent.com/96986045/147879867-5f7805f0-affe-49b8-8578-abe3de85b3f1.mp4

**Comment by SHsuperCM** [comment]
```
Non [a-z0-9/._-] character in path of location: minecraft:optifine/cit/wing icons/angel_wings.properties
```
The space in `wing icons` breaks the pack.

**Comment by SHsuperCM** [comment]
More info available here:
https://citresewn.readthedocs.io/usage/help/
https://citresewn.readthedocs.io/usage/config/
