### ISSUE TITLE
CIT Issue

### ISSUE THREAD

**Issue by gamingchairpog** [SHsuperCM/CITResewn#93]
whenever I put a CIT(custom item texture) pack in, the game says 'Failed to load texture" Can someone help?

**Comment by SHsuperCM** [comment]
You'll need to provide logs when requesting assistance with a crash or an error.
\> [Windows](https://fabricmc.net/wiki/player:tutorials:logs_ml:windows)
\> [MacOS](https://fabricmc.net/wiki/player:tutorials:logs_ml:mac)

Please get the latest log. (or a crash report if relevant)

**Comment by gamingchairpog** [comment]
[latest.log](https://github.com/SHsuperCM/CITResewn/files/7839744/latest.log)

**Comment by SHsuperCM** [comment]
Says
```
[14:48:52] [Worker-Main-5/INFO]: [citresewn] No cit packs found.
```
Doesn't show you trying to use any CIT packs packs anywhere else.

Can you launch the game, try to add the pack and close it without going in a world or doing anything else?

**Comment by gamingchairpog** [comment]
No, because as I mentioned when I put in the pack it immediately takes out all the resource packs.

**Comment by gamingchairpog** [comment]
[latest.log](https://github.com/SHsuperCM/CITResewn/files/7839874/latest.log)
I sent the logs again, I hope it works but I doubt it

**Comment by gamingchairpog** [comment]
Thanks, I got a fix for it :)
