### ISSUE TITLE
Nonstandard characters not working in nbt.display.Name 

### ISSUE THREAD

**Issue by tdapost** [SHsuperCM/CITResewn#95]
I had some issues creating a datapack, and as part of my troubleshooting I created 3 datapacks, one with `nbt.display.Name=T`, one with `nbt.display.Name=ï` and one with `nbt.display.Name=☄`. Apart from this they are identical, but only the first one results in a changed texture. According to the logs they are all loaded, and the mod finds cits in all three of them. Are these characters just not supported, or am I still doing somthing wrong?
Datapacks:
[Green Netherite 1.zip](https://github.com/SHsuperCM/CITResewn/files/7877765/Green.Netherite.1.zip)
[Green Netherite 2.zip](https://github.com/SHsuperCM/CITResewn/files/7877766/Green.Netherite.2.zip)
[Green Netherite 3.zip](https://github.com/SHsuperCM/CITResewn/files/7877767/Green.Netherite.3.zip)
Log: 
[latest.log](https://github.com/SHsuperCM/CITResewn/files/7877768/latest.log)

**Comment by SHsuperCM** [comment]
[Fixed in v0.9.1](https://modrinth.com/mod/cit-resewn/version/PnxfNudU).

**Comment by tdapost** [comment]
Thank you so much!
