### ISSUE TITLE
Texture packs doesnt load

### ISSUE THREAD

**Issue by JustFoxx** [SHsuperCM/CITResewn#96]
im trying to load https://www.curseforge.com/minecraft/texture-packs/bettervanillabuilding and https://www.curseforge.com/minecraft/texture-packs/xaeros-minimap-modded-support

**Comment by SHsuperCM** [comment]
Relevant logs file from discord: https://cdn.discordapp.com/attachments/507982463449169932/934744718053638154/message.txt

>  it just stops loading

I've tested the packs and they load fine for me. One of the other(many) mods you have installed is causing this and CIT Resewn just happened to be the last message in the logs when that happened.

Try removing mods until you find the ones responsible. If it is still CIT Resewn but in combination with another mod let me know and I'll reopen the issue.
