### ISSUE TITLE
Support for Elytra Trinket/trinkets cape slot?

### ISSUE THREAD

**Issue by Skeithh** [SHsuperCM/CITResewn#98]
Unsure how possible it'd be, but I found that the CIT elytra model textures do not work when you place the elytra into the trinkets cape slot through [Elytra Trinket](https://www.curseforge.com/minecraft/mc-mods/elytra-trinket-fabric)
If it'd be possible to have support for this, that'd be awesome.

**Comment by SHsuperCM** [comment]
It is possible but probably not within the beta timeline. I can look into adding support after v1 is out and stable.

**Comment by Skeithh** [comment]
Awesome, already happy to know that it'll be looked into :>!

**Comment by Julienraptor01** [comment]
could it be also compatible with colytra ?
https://www.curseforge.com/minecraft/mc-mods/colytra-fabric

**Comment by SHsuperCM** [comment]
Closing issue for the same reasons as #17.
From the issue:
> Aight. As much as I want to add support from CIT Resewn's side, I have decided it'd be better not to for now.
> These mods will have to add support on their side and so there is now an api to facilitate that.
